/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './login';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import12 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import15 from '@angular/core/src/linker/query_list';
import * as import16 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import18 from 'ionic-angular/config/config';
import * as import19 from '@angular/core/src/linker/element_ref';
import * as import20 from 'ionic-angular/components/app/app';
import * as import21 from 'ionic-angular/util/keyboard';
import * as import22 from '@angular/core/src/zone/ng_zone';
import * as import23 from 'ionic-angular/navigation/view-controller';
import * as import24 from 'ionic-angular/components/tabs/tabs';
import * as import25 from 'ionic-angular/util/form';
import * as import26 from 'ionic-angular/components/item/item-reorder';
import * as import27 from 'ionic-angular/platform/platform';
import * as import28 from '@angular/forms/src/directives/ng_control';
import * as import29 from 'ionic-angular/components/grid/grid';
import * as import30 from 'ionic-angular/components/input/input';
import * as import31 from 'ionic-angular/components/item/item';
import * as import32 from 'ionic-angular/components/card/card';
import * as import33 from 'ionic-angular/components/button/button';
import * as import34 from 'ionic-angular/components/content/content';
export class Wrapper_LoginPage {
  context:import0.LoginPage;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.LoginPage(p0);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_LoginPage_Host:import2.RenderComponentType = (null as any);
class _View_LoginPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _LoginPage_0_4:Wrapper_LoginPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage_Host0,renderType_LoginPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-login',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LoginPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LoginPage_0_4 = new Wrapper_LoginPage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._LoginPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._LoginPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.LoginPage) && (0 === requestNodeIndex))) { return this._LoginPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LoginPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoginPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_LoginPage_Host === (null as any))) { (renderType_LoginPage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_LoginPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginPageNgFactory:import10.ComponentFactory<import0.LoginPage> = new import10.ComponentFactory<import0.LoginPage>('page-login',viewFactory_LoginPage_Host0,import0.LoginPage);
const styles_LoginPage:any[] = ([] as any[]);
var renderType_LoginPage:import2.RenderComponentType = (null as any);
class _View_LoginPage0 extends import1.AppView<import0.LoginPage> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import3.AppElement;
  _Content_1_4:import11.Wrapper_Content;
  _text_2:any;
  _el_3:any;
  _Grid_3_3:import12.Wrapper_Grid;
  _text_4:any;
  _el_5:any;
  _Row_5_3:import12.Wrapper_Row;
  _text_6:any;
  _el_7:any;
  _Col_7_3:import12.Wrapper_Col;
  _el_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _Grid_15_3:import12.Wrapper_Grid;
  _text_16:any;
  _el_17:any;
  _Row_17_3:import12.Wrapper_Row;
  _text_18:any;
  _el_19:any;
  _Col_19_3:import12.Wrapper_Col;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _Card_34_3:import13.Wrapper_Card;
  _text_35:any;
  _el_36:any;
  _CardContent_36_3:import13.Wrapper_CardContent;
  _text_37:any;
  _el_38:any;
  /*private*/ _appEl_38:import3.AppElement;
  _Item_38_4:import14.Wrapper_Item;
  _ItemContent_38_5:import14.Wrapper_ItemContent;
  _query_Label_38_0:import15.QueryList<any>;
  _query_Button_38_1:import15.QueryList<any>;
  _query_Icon_38_2:import15.QueryList<any>;
  _text_39:any;
  _el_40:any;
  /*private*/ _appEl_40:import3.AppElement;
  _TextInput_40_4:import16.Wrapper_TextInput;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  /*private*/ _appEl_43:import3.AppElement;
  _Item_43_4:import14.Wrapper_Item;
  _ItemContent_43_5:import14.Wrapper_ItemContent;
  _query_Label_43_0:import15.QueryList<any>;
  _query_Button_43_1:import15.QueryList<any>;
  _query_Icon_43_2:import15.QueryList<any>;
  _text_44:any;
  _el_45:any;
  /*private*/ _appEl_45:import3.AppElement;
  _TextInput_45_4:import16.Wrapper_TextInput;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  /*private*/ _appEl_50:import3.AppElement;
  _Button_50_4:import17.Wrapper_Button;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _el_55:any;
  /*private*/ _appEl_55:import3.AppElement;
  _Button_55_4:import17.Wrapper_Button;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  /*private*/ _expr_0:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage0,renderType_LoginPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_1,'padding','');
    this._appEl_1 = new import3.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import11.viewFactory_Content0(this.viewUtils,this.injector(1),this._appEl_1);
    this._Content_1_4 = new import11.Wrapper_Content(this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import20.App),this.parentInjector.get(import21.Keyboard),this.parentInjector.get(import22.NgZone),this.parentInjector.get(import23.ViewController,(null as any)),this.parentInjector.get(import24.Tabs,(null as any)));
    this._appEl_1.initComponent(this._Content_1_4.context,([] as any[]),compView_1);
    this._text_2 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_3 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this._Grid_3_3 = new import12.Wrapper_Grid();
    this._text_4 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'ion-row',(null as any));
    this._Row_5_3 = new import12.Wrapper_Row();
    this._text_6 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'ion-col',(null as any));
    this._Col_7_3 = new import12.Wrapper_Col();
    this._el_8 = this.renderer.createElement(this._el_7,'div',(null as any));
    this._el_9 = this.renderer.createElement(this._el_8,'br',(null as any));
    this._text_10 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_11 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_13,'src','assets/img/logo.png');
    this.renderer.setElementAttribute(this._el_13,'style','display:block;margin: auto;');
    this._text_14 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this._Grid_15_3 = new import12.Wrapper_Grid();
    this._text_16 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'ion-row',(null as any));
    this._Row_17_3 = new import12.Wrapper_Row();
    this._text_18 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'ion-col',(null as any));
    this._Col_19_3 = new import12.Wrapper_Col();
    this._text_20 = this.renderer.createText(this._el_19,'\n                ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'div',(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n                    ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'br',(null as any));
    this._text_24 = this.renderer.createText(this._el_21,'\n                ',(null as any));
    this._text_25 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._text_26 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._text_27 = this.renderer.createText(this._el_15,'\n    ',(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_29,'src','assets/img/facebook.png');
    this.renderer.setElementAttribute(this._el_29,'style','display:block;margin: auto;');
    this._text_30 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_31 = this.renderer.createElement((null as any),'h3',(null as any));
    this.renderer.setElementAttribute(this._el_31,'style','text-align: center; color:#c8c8c8');
    this._text_32 = this.renderer.createText(this._el_31,' OR ',(null as any));
    this._text_33 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_34 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_34_3 = new import13.Wrapper_Card(this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_34),this.renderer);
    this._text_35 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_34,'ion-card-content',(null as any));
    this._CardContent_36_3 = new import13.Wrapper_CardContent(this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_36),this.renderer);
    this._text_37 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_36,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','item item-block');
    this._appEl_38 = new import3.AppElement(38,36,this,this._el_38);
    var compView_38:any = import14.viewFactory_Item0(this.viewUtils,this.injector(38),this._appEl_38);
    this._Item_38_4 = new import14.Wrapper_Item(this.parentInjector.get(import25.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_38),this.renderer,this.parentInjector.get(import26.ItemReorder,(null as any)));
    this._ItemContent_38_5 = new import14.Wrapper_ItemContent();
    this._query_Label_38_0 = new import15.QueryList<any>();
    this._query_Button_38_1 = new import15.QueryList<any>();
    this._query_Icon_38_2 = new import15.QueryList<any>();
    this._appEl_38.initComponent(this._Item_38_4.context,([] as any[]),compView_38);
    this._text_39 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_40 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_40,'placeholder','Email Address');
    this.renderer.setElementAttribute(this._el_40,'type','email');
    this._appEl_40 = new import3.AppElement(40,38,this,this._el_40);
    var compView_40:any = import16.viewFactory_TextInput0(this.viewUtils,this.injector(40),this._appEl_40);
    this._TextInput_40_4 = new import16.Wrapper_TextInput(this.parentInjector.get(import18.Config),this.parentInjector.get(import25.Form),this._Item_38_4.context,this.parentInjector.get(import20.App),this.parentInjector.get(import27.Platform),new import19.ElementRef(this._el_40),this.renderer,this._Content_1_4.context,this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import28.NgControl,(null as any)));
    this._appEl_40.initComponent(this._TextInput_40_4.context,([] as any[]),compView_40);
    compView_40.create(this._TextInput_40_4.context,([] as any[]),(null as any));
    this._text_41 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_38_0.reset(([] as any[]));
    this._Item_38_4.context.contentLabel = this._query_Label_38_0.first;
    compView_38.create(this._Item_38_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_39,
        this._text_41
      ]
      ),
      ([] as any[]).concat([this._el_40]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_42 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_36,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','item item-block');
    this._appEl_43 = new import3.AppElement(43,36,this,this._el_43);
    var compView_43:any = import14.viewFactory_Item0(this.viewUtils,this.injector(43),this._appEl_43);
    this._Item_43_4 = new import14.Wrapper_Item(this.parentInjector.get(import25.Form),this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_43),this.renderer,this.parentInjector.get(import26.ItemReorder,(null as any)));
    this._ItemContent_43_5 = new import14.Wrapper_ItemContent();
    this._query_Label_43_0 = new import15.QueryList<any>();
    this._query_Button_43_1 = new import15.QueryList<any>();
    this._query_Icon_43_2 = new import15.QueryList<any>();
    this._appEl_43.initComponent(this._Item_43_4.context,([] as any[]),compView_43);
    this._text_44 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_45 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_45,'placeholder','Password');
    this.renderer.setElementAttribute(this._el_45,'type','password');
    this._appEl_45 = new import3.AppElement(45,43,this,this._el_45);
    var compView_45:any = import16.viewFactory_TextInput0(this.viewUtils,this.injector(45),this._appEl_45);
    this._TextInput_45_4 = new import16.Wrapper_TextInput(this.parentInjector.get(import18.Config),this.parentInjector.get(import25.Form),this._Item_43_4.context,this.parentInjector.get(import20.App),this.parentInjector.get(import27.Platform),new import19.ElementRef(this._el_45),this.renderer,this._Content_1_4.context,this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import28.NgControl,(null as any)));
    this._appEl_45.initComponent(this._TextInput_45_4.context,([] as any[]),compView_45);
    compView_45.create(this._TextInput_45_4.context,([] as any[]),(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_43_0.reset(([] as any[]));
    this._Item_43_4.context.contentLabel = this._query_Label_43_0.first;
    compView_43.create(this._Item_43_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_44,
        this._text_46
      ]
      ),
      ([] as any[]).concat([this._el_45]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_47 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._text_48 = this.renderer.createText(this._el_34,'\n    ',(null as any));
    this._text_49 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_50 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_50,'block','');
    this.renderer.setElementAttribute(this._el_50,'ion-button','');
    this.renderer.setElementAttribute(this._el_50,'style','color:#ffffff;background-color:#f85394;font-weight: bold;');
    this._appEl_50 = new import3.AppElement(50,1,this,this._el_50);
    var compView_50:any = import17.viewFactory_Button0(this.viewUtils,this.injector(50),this._appEl_50);
    this._Button_50_4 = new import17.Wrapper_Button((null as any),'',this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_50),this.renderer);
    this._appEl_50.initComponent(this._Button_50_4.context,([] as any[]),compView_50);
    this._text_51 = this.renderer.createText((null as any),'Login',(null as any));
    compView_50.create(this._Button_50_4.context,[([] as any[]).concat([this._text_51])],(null as any));
    this._text_52 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_53 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_53,'style','align-items: center;');
    this._text_54 = this.renderer.createText(this._el_53,'\n        ',(null as any));
    this._el_55 = this.renderer.createElement(this._el_53,'button',(null as any));
    this.renderer.setElementAttribute(this._el_55,'clear','');
    this.renderer.setElementAttribute(this._el_55,'ion-button','');
    this.renderer.setElementAttribute(this._el_55,'style','color:#fa8cb4;font-weight: bold;');
    this._appEl_55 = new import3.AppElement(55,53,this,this._el_55);
    var compView_55:any = import17.viewFactory_Button0(this.viewUtils,this.injector(55),this._appEl_55);
    this._Button_55_4 = new import17.Wrapper_Button((null as any),'',this.parentInjector.get(import18.Config),new import19.ElementRef(this._el_55),this.renderer);
    this._appEl_55.initComponent(this._Button_55_4.context,([] as any[]),compView_55);
    this._text_56 = this.renderer.createText((null as any),'Forgot Password?',(null as any));
    compView_55.create(this._Button_55_4.context,[([] as any[]).concat([this._text_56])],(null as any));
    this._text_57 = this.renderer.createText(this._el_53,'\n    ',(null as any));
    this._text_58 = this.renderer.createText((null as any),'\n',(null as any));
    compView_1.create(this._Content_1_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_2,
        this._el_3,
        this._text_12,
        this._el_13,
        this._text_14,
        this._el_15,
        this._text_28,
        this._el_29,
        this._text_30,
        this._el_31,
        this._text_33,
        this._el_34,
        this._text_49,
        this._el_50,
        this._text_52,
        this._el_53,
        this._text_58
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._el_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._text_58
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import29.Col) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Col_7_3.context; }
    if (((token === import29.Row) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Row_5_3.context; }
    if (((token === import29.Grid) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Grid_3_3.context; }
    if (((token === import29.Col) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Col_19_3.context; }
    if (((token === import29.Row) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Row_17_3.context; }
    if (((token === import29.Grid) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Grid_15_3.context; }
    if (((token === import30.TextInput) && (40 === requestNodeIndex))) { return this._TextInput_40_4.context; }
    if (((token === import31.Item) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Item_38_4.context; }
    if (((token === import31.ItemContent) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._ItemContent_38_5.context; }
    if (((token === import30.TextInput) && (45 === requestNodeIndex))) { return this._TextInput_45_4.context; }
    if (((token === import31.Item) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._Item_43_4.context; }
    if (((token === import31.ItemContent) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._ItemContent_43_5.context; }
    if (((token === import32.CardContent) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._CardContent_36_3.context; }
    if (((token === import32.Card) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Card_34_3.context; }
    if (((token === import33.Button) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._Button_50_4.context; }
    if (((token === import33.Button) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._Button_55_4.context; }
    if (((token === import34.Content) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._Content_1_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Content_1_4.detectChangesInternal(this,this._el_1,throwOnChange)) { this._appEl_1.componentView.markAsCheckOnce(); }
    this._Grid_3_3.detectChangesInternal(this,this._el_3,throwOnChange);
    this._Row_5_3.detectChangesInternal(this,this._el_5,throwOnChange);
    this._Col_7_3.detectChangesInternal(this,this._el_7,throwOnChange);
    this._Grid_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    this._Row_17_3.detectChangesInternal(this,this._el_17,throwOnChange);
    this._Col_19_3.detectChangesInternal(this,this._el_19,throwOnChange);
    this._Card_34_3.detectChangesInternal(this,this._el_34,throwOnChange);
    this._CardContent_36_3.detectChangesInternal(this,this._el_36,throwOnChange);
    if (this._Item_38_4.detectChangesInternal(this,this._el_38,throwOnChange)) { this._appEl_38.componentView.markAsCheckOnce(); }
    this._ItemContent_38_5.detectChangesInternal(this,this._el_38,throwOnChange);
    const currVal_1:any = 'Email Address';
    this._TextInput_40_4.check_placeholder(currVal_1,throwOnChange,false);
    const currVal_2:any = 'email';
    this._TextInput_40_4.check_type(currVal_2,throwOnChange,false);
    this._TextInput_40_4.detectChangesInternal(this,this._el_40,throwOnChange);
    if (this._Item_43_4.detectChangesInternal(this,this._el_43,throwOnChange)) { this._appEl_43.componentView.markAsCheckOnce(); }
    this._ItemContent_43_5.detectChangesInternal(this,this._el_43,throwOnChange);
    const currVal_3:any = 'Password';
    this._TextInput_45_4.check_placeholder(currVal_3,throwOnChange,false);
    const currVal_4:any = 'password';
    this._TextInput_45_4.check_type(currVal_4,throwOnChange,false);
    this._TextInput_45_4.detectChangesInternal(this,this._el_45,throwOnChange);
    const currVal_5:any = '';
    this._Button_50_4.check_block(currVal_5,throwOnChange,false);
    if (this._Button_50_4.detectChangesInternal(this,this._el_50,throwOnChange)) { this._appEl_50.componentView.markAsCheckOnce(); }
    const currVal_6:any = '';
    this._Button_55_4.check_clear(currVal_6,throwOnChange,false);
    if (this._Button_55_4.detectChangesInternal(this,this._el_55,throwOnChange)) { this._appEl_55.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_38_1.dirty) {
        this._query_Button_38_1.reset(([] as any[]));
        this._Item_38_4.context._buttons = this._query_Button_38_1;
        this._query_Button_38_1.notifyOnChanges();
      }
      if (this._query_Icon_38_2.dirty) {
        this._query_Icon_38_2.reset(([] as any[]));
        this._Item_38_4.context._icons = this._query_Icon_38_2;
        this._query_Icon_38_2.notifyOnChanges();
      }
      if (this._query_Button_43_1.dirty) {
        this._query_Button_43_1.reset(([] as any[]));
        this._Item_43_4.context._buttons = this._query_Button_43_1;
        this._query_Button_43_1.notifyOnChanges();
      }
      if (this._query_Icon_43_2.dirty) {
        this._query_Icon_43_2.reset(([] as any[]));
        this._Item_43_4.context._icons = this._query_Icon_43_2;
        this._query_Icon_43_2.notifyOnChanges();
      }
      this._TextInput_40_4.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_38_4.context.ngAfterContentInit(); }
      this._TextInput_45_4.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_43_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_50_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_55_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Content_1_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_1,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._TextInput_40_4.context.ngOnDestroy();
    this._TextInput_45_4.context.ngOnDestroy();
    this._Content_1_4.context.ngOnDestroy();
  }
}
export function viewFactory_LoginPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.LoginPage> {
  if ((renderType_LoginPage === (null as any))) { (renderType_LoginPage = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_LoginPage,{})); }
  return new _View_LoginPage0(viewUtils,parentInjector,declarationEl);
}