/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './login';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from 'ionic-native/dist/es5/plugins/facebook';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from 'ionic-angular/navigation/nav-controller';
import * as import10 from 'ionic-angular/components/alert/alert';
import * as import11 from '@angular/http/src/http';
import * as import12 from 'ionic-angular/util/events';
import * as import13 from 'ionic-angular/components/loading/loading';
import * as import14 from '@angular/core/src/metadata/view';
import * as import15 from '@angular/core/src/linker/component_factory';
import * as import16 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import20 from '@angular/core/src/linker/query_list';
import * as import21 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import22 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import25 from 'ionic-angular/config/config';
import * as import26 from '@angular/core/src/linker/element_ref';
import * as import27 from 'ionic-angular/components/app/app';
import * as import28 from 'ionic-angular/util/keyboard';
import * as import29 from '@angular/core/src/zone/ng_zone';
import * as import30 from 'ionic-angular/navigation/view-controller';
import * as import31 from 'ionic-angular/components/tabs/tabs';
import * as import32 from 'ionic-angular/util/form';
import * as import33 from 'ionic-angular/components/item/item-reorder';
import * as import34 from 'ionic-angular/platform/platform';
import * as import35 from 'ionic-angular/components/grid/grid';
import * as import36 from '@angular/forms/src/directives/ng_model';
import * as import37 from '@angular/forms/src/directives/ng_control';
import * as import38 from '@angular/forms/src/directives/ng_control_status';
import * as import39 from 'ionic-angular/components/input/input';
import * as import40 from 'ionic-angular/components/item/item';
import * as import41 from 'ionic-angular/components/card/card';
import * as import42 from 'ionic-angular/components/button/button';
import * as import43 from 'ionic-angular/components/content/content';
export class Wrapper_LoginPage {
  context:import0.LoginPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any) {
    this.changed = false;
    this.context = new import0.LoginPage(p0,p1,p2,p3,p4);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
var renderType_LoginPage_Host:import2.RenderComponentType = (null as any);
class _View_LoginPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _LoginPage_0_4:Wrapper_LoginPage;
  __Facebook_0_5:import4.Facebook;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage_Host0,renderType_LoginPage_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  get _Facebook_0_5():import4.Facebook {
    if ((this.__Facebook_0_5 == (null as any))) { (this.__Facebook_0_5 = new import4.Facebook()); }
    return this.__Facebook_0_5;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-login',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_LoginPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._LoginPage_0_4 = new Wrapper_LoginPage(this.parentInjector.get(import9.NavController),this.parentInjector.get(import10.AlertController),this.parentInjector.get(import11.Http),this.parentInjector.get(import12.Events),this.parentInjector.get(import13.LoadingController));
    this._appEl_0.initComponent(this._LoginPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._LoginPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.LoginPage) && (0 === requestNodeIndex))) { return this._LoginPage_0_4.context; }
    if (((token === import4.Facebook) && (0 === requestNodeIndex))) { return this._Facebook_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._LoginPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_LoginPage_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_LoginPage_Host === (null as any))) { (renderType_LoginPage_Host = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_LoginPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const LoginPageNgFactory:import15.ComponentFactory<import0.LoginPage> = new import15.ComponentFactory<import0.LoginPage>('page-login',viewFactory_LoginPage_Host0,import0.LoginPage);
const styles_LoginPage:any[] = ([] as any[]);
var renderType_LoginPage:import2.RenderComponentType = (null as any);
class _View_LoginPage0 extends import1.AppView<import0.LoginPage> {
  _text_0:any;
  _el_1:any;
  /*private*/ _appEl_1:import3.AppElement;
  _Content_1_4:import16.Wrapper_Content;
  _text_2:any;
  _el_3:any;
  _Grid_3_3:import17.Wrapper_Grid;
  _text_4:any;
  _el_5:any;
  _Row_5_3:import17.Wrapper_Row;
  _text_6:any;
  _el_7:any;
  _Col_7_3:import17.Wrapper_Col;
  _el_8:any;
  _el_9:any;
  _text_10:any;
  _text_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _el_15:any;
  _Grid_15_3:import17.Wrapper_Grid;
  _text_16:any;
  _el_17:any;
  _Row_17_3:import17.Wrapper_Row;
  _text_18:any;
  _el_19:any;
  _Col_19_3:import17.Wrapper_Col;
  _text_20:any;
  _el_21:any;
  _text_22:any;
  _el_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _text_27:any;
  _text_28:any;
  _el_29:any;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _el_34:any;
  _Card_34_3:import18.Wrapper_Card;
  _text_35:any;
  _el_36:any;
  _CardContent_36_3:import18.Wrapper_CardContent;
  _text_37:any;
  _el_38:any;
  /*private*/ _appEl_38:import3.AppElement;
  _Item_38_4:import19.Wrapper_Item;
  _ItemContent_38_5:import19.Wrapper_ItemContent;
  _query_Label_38_0:import20.QueryList<any>;
  _query_Button_38_1:import20.QueryList<any>;
  _query_Icon_38_2:import20.QueryList<any>;
  _text_39:any;
  _el_40:any;
  /*private*/ _appEl_40:import3.AppElement;
  _NgModel_40_4:import21.Wrapper_NgModel;
  _NgControl_40_5:any;
  _NgControlStatus_40_6:import22.Wrapper_NgControlStatus;
  _TextInput_40_7:import23.Wrapper_TextInput;
  _text_41:any;
  _text_42:any;
  _el_43:any;
  /*private*/ _appEl_43:import3.AppElement;
  _Item_43_4:import19.Wrapper_Item;
  _ItemContent_43_5:import19.Wrapper_ItemContent;
  _query_Label_43_0:import20.QueryList<any>;
  _query_Button_43_1:import20.QueryList<any>;
  _query_Icon_43_2:import20.QueryList<any>;
  _text_44:any;
  _el_45:any;
  /*private*/ _appEl_45:import3.AppElement;
  _NgModel_45_4:import21.Wrapper_NgModel;
  _NgControl_45_5:any;
  _NgControlStatus_45_6:import22.Wrapper_NgControlStatus;
  _TextInput_45_7:import23.Wrapper_TextInput;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _el_50:any;
  /*private*/ _appEl_50:import3.AppElement;
  _Button_50_4:import24.Wrapper_Button;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  /*private*/ _appEl_53:import3.AppElement;
  _Button_53_4:import24.Wrapper_Button;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _el_60:any;
  _Row_60_3:import17.Wrapper_Row;
  _text_61:any;
  _el_62:any;
  _text_63:any;
  _el_64:any;
  /*private*/ _appEl_64:import3.AppElement;
  _Button_64_4:import24.Wrapper_Button;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _el_70:any;
  _text_71:any;
  _text_72:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_14:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_LoginPage0,renderType_LoginPage,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_1,'padding','');
    this._appEl_1 = new import3.AppElement(1,(null as any),this,this._el_1);
    var compView_1:any = import16.viewFactory_Content0(this.viewUtils,this.injector(1),this._appEl_1);
    this._Content_1_4 = new import16.Wrapper_Content(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import27.App),this.parentInjector.get(import28.Keyboard),this.parentInjector.get(import29.NgZone),this.parentInjector.get(import30.ViewController,(null as any)),this.parentInjector.get(import31.Tabs,(null as any)));
    this._appEl_1.initComponent(this._Content_1_4.context,([] as any[]),compView_1);
    this._text_2 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_3 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this._Grid_3_3 = new import17.Wrapper_Grid();
    this._text_4 = this.renderer.createText(this._el_3,'\n        ',(null as any));
    this._el_5 = this.renderer.createElement(this._el_3,'ion-row',(null as any));
    this._Row_5_3 = new import17.Wrapper_Row();
    this._text_6 = this.renderer.createText(this._el_5,'\n            ',(null as any));
    this._el_7 = this.renderer.createElement(this._el_5,'ion-col',(null as any));
    this._Col_7_3 = new import17.Wrapper_Col();
    this._el_8 = this.renderer.createElement(this._el_7,'div',(null as any));
    this._el_9 = this.renderer.createElement(this._el_8,'br',(null as any));
    this._text_10 = this.renderer.createText(this._el_5,'\n        ',(null as any));
    this._text_11 = this.renderer.createText(this._el_3,'\n    ',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_13,'src','assets/img/logo.png');
    this.renderer.setElementAttribute(this._el_13,'style','display:block;margin: auto;');
    this._text_14 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_15 = this.renderer.createElement((null as any),'ion-grid',(null as any));
    this._Grid_15_3 = new import17.Wrapper_Grid();
    this._text_16 = this.renderer.createText(this._el_15,'\n        ',(null as any));
    this._el_17 = this.renderer.createElement(this._el_15,'ion-row',(null as any));
    this._Row_17_3 = new import17.Wrapper_Row();
    this._text_18 = this.renderer.createText(this._el_17,'\n            ',(null as any));
    this._el_19 = this.renderer.createElement(this._el_17,'ion-col',(null as any));
    this._Col_19_3 = new import17.Wrapper_Col();
    this._text_20 = this.renderer.createText(this._el_19,'\n                ',(null as any));
    this._el_21 = this.renderer.createElement(this._el_19,'div',(null as any));
    this._text_22 = this.renderer.createText(this._el_21,'\n                    ',(null as any));
    this._el_23 = this.renderer.createElement(this._el_21,'br',(null as any));
    this._text_24 = this.renderer.createText(this._el_21,'\n                ',(null as any));
    this._text_25 = this.renderer.createText(this._el_19,'\n            ',(null as any));
    this._text_26 = this.renderer.createText(this._el_17,'\n        ',(null as any));
    this._text_27 = this.renderer.createText(this._el_15,'\n    ',(null as any));
    this._text_28 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_29 = this.renderer.createElement((null as any),'img',(null as any));
    this.renderer.setElementAttribute(this._el_29,'src','assets/img/facebook.png');
    this.renderer.setElementAttribute(this._el_29,'style','display:block;margin: auto;');
    this._text_30 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_31 = this.renderer.createElement((null as any),'h3',(null as any));
    this.renderer.setElementAttribute(this._el_31,'style','text-align: center; color:#c8c8c8');
    this._text_32 = this.renderer.createText(this._el_31,' OR ',(null as any));
    this._text_33 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_34 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_34_3 = new import18.Wrapper_Card(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_34),this.renderer);
    this._text_35 = this.renderer.createText(this._el_34,'\n        ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_34,'ion-card-content',(null as any));
    this._CardContent_36_3 = new import18.Wrapper_CardContent(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_36),this.renderer);
    this._text_37 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._el_38 = this.renderer.createElement(this._el_36,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_38,'class','item item-block');
    this._appEl_38 = new import3.AppElement(38,36,this,this._el_38);
    var compView_38:any = import19.viewFactory_Item0(this.viewUtils,this.injector(38),this._appEl_38);
    this._Item_38_4 = new import19.Wrapper_Item(this.parentInjector.get(import32.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_38),this.renderer,this.parentInjector.get(import33.ItemReorder,(null as any)));
    this._ItemContent_38_5 = new import19.Wrapper_ItemContent();
    this._query_Label_38_0 = new import20.QueryList<any>();
    this._query_Button_38_1 = new import20.QueryList<any>();
    this._query_Icon_38_2 = new import20.QueryList<any>();
    this._appEl_38.initComponent(this._Item_38_4.context,([] as any[]),compView_38);
    this._text_39 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_40 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_40,'placeholder','Email Address');
    this.renderer.setElementAttribute(this._el_40,'type','email');
    this._appEl_40 = new import3.AppElement(40,38,this,this._el_40);
    var compView_40:any = import23.viewFactory_TextInput0(this.viewUtils,this.injector(40),this._appEl_40);
    this._NgModel_40_4 = new import21.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_40_5 = this._NgModel_40_4.context;
    this._NgControlStatus_40_6 = new import22.Wrapper_NgControlStatus(this._NgControl_40_5);
    this._TextInput_40_7 = new import23.Wrapper_TextInput(this.parentInjector.get(import25.Config),this.parentInjector.get(import32.Form),this._Item_38_4.context,this.parentInjector.get(import27.App),this.parentInjector.get(import34.Platform),new import26.ElementRef(this._el_40),this.renderer,this._Content_1_4.context,this.parentInjector.get(import9.NavController,(null as any)),this._NgControl_40_5);
    this._appEl_40.initComponent(this._TextInput_40_7.context,([] as any[]),compView_40);
    compView_40.create(this._TextInput_40_7.context,([] as any[]),(null as any));
    this._text_41 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_38_0.reset(([] as any[]));
    this._Item_38_4.context.contentLabel = this._query_Label_38_0.first;
    compView_38.create(this._Item_38_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_39,
        this._text_41
      ]
      ),
      ([] as any[]).concat([this._el_40]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_42 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_36,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','item item-block');
    this._appEl_43 = new import3.AppElement(43,36,this,this._el_43);
    var compView_43:any = import19.viewFactory_Item0(this.viewUtils,this.injector(43),this._appEl_43);
    this._Item_43_4 = new import19.Wrapper_Item(this.parentInjector.get(import32.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_43),this.renderer,this.parentInjector.get(import33.ItemReorder,(null as any)));
    this._ItemContent_43_5 = new import19.Wrapper_ItemContent();
    this._query_Label_43_0 = new import20.QueryList<any>();
    this._query_Button_43_1 = new import20.QueryList<any>();
    this._query_Icon_43_2 = new import20.QueryList<any>();
    this._appEl_43.initComponent(this._Item_43_4.context,([] as any[]),compView_43);
    this._text_44 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_45 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_45,'placeholder','Password');
    this.renderer.setElementAttribute(this._el_45,'type','password');
    this._appEl_45 = new import3.AppElement(45,43,this,this._el_45);
    var compView_45:any = import23.viewFactory_TextInput0(this.viewUtils,this.injector(45),this._appEl_45);
    this._NgModel_45_4 = new import21.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_45_5 = this._NgModel_45_4.context;
    this._NgControlStatus_45_6 = new import22.Wrapper_NgControlStatus(this._NgControl_45_5);
    this._TextInput_45_7 = new import23.Wrapper_TextInput(this.parentInjector.get(import25.Config),this.parentInjector.get(import32.Form),this._Item_43_4.context,this.parentInjector.get(import27.App),this.parentInjector.get(import34.Platform),new import26.ElementRef(this._el_45),this.renderer,this._Content_1_4.context,this.parentInjector.get(import9.NavController,(null as any)),this._NgControl_45_5);
    this._appEl_45.initComponent(this._TextInput_45_7.context,([] as any[]),compView_45);
    compView_45.create(this._TextInput_45_7.context,([] as any[]),(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_43_0.reset(([] as any[]));
    this._Item_43_4.context.contentLabel = this._query_Label_43_0.first;
    compView_43.create(this._Item_43_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_44,
        this._text_46
      ]
      ),
      ([] as any[]).concat([this._el_45]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_47 = this.renderer.createText(this._el_36,'\n            ',(null as any));
    this._text_48 = this.renderer.createText(this._el_34,'\n    ',(null as any));
    this._text_49 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_50 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_50,'block','');
    this.renderer.setElementAttribute(this._el_50,'ion-button','');
    this.renderer.setElementAttribute(this._el_50,'style','color:#ffffff;background-color:#f85394;font-weight: bold;');
    this._appEl_50 = new import3.AppElement(50,1,this,this._el_50);
    var compView_50:any = import24.viewFactory_Button0(this.viewUtils,this.injector(50),this._appEl_50);
    this._Button_50_4 = new import24.Wrapper_Button((null as any),'',this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_50),this.renderer);
    this._appEl_50.initComponent(this._Button_50_4.context,([] as any[]),compView_50);
    this._text_51 = this.renderer.createText((null as any),'Login',(null as any));
    compView_50.create(this._Button_50_4.context,[([] as any[]).concat([this._text_51])],(null as any));
    this._text_52 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_53 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_53,'clear','');
    this.renderer.setElementAttribute(this._el_53,'ion-button','');
    this.renderer.setElementAttribute(this._el_53,'style','color:#fa8cb4;font-weight: bold;left:50%;-webkit-transform:translateX(-50%);transform: translateX(-50%);');
    this._appEl_53 = new import3.AppElement(53,1,this,this._el_53);
    var compView_53:any = import24.viewFactory_Button0(this.viewUtils,this.injector(53),this._appEl_53);
    this._Button_53_4 = new import24.Wrapper_Button((null as any),'',this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_53),this.renderer);
    this._appEl_53.initComponent(this._Button_53_4.context,([] as any[]),compView_53);
    this._text_54 = this.renderer.createText((null as any),'Forgot Password?',(null as any));
    compView_53.create(this._Button_53_4.context,[([] as any[]).concat([this._text_54])],(null as any));
    this._text_55 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_56 = this.renderer.createElement((null as any),'br',(null as any));
    this._text_57 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_58 = this.renderer.createElement((null as any),'br',(null as any));
    this._text_59 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_60 = this.renderer.createElement((null as any),'ion-row',(null as any));
    this._Row_60_3 = new import17.Wrapper_Row();
    this._text_61 = this.renderer.createText(this._el_60,'\n            ',(null as any));
    this._el_62 = this.renderer.createElement(this._el_60,'p',(null as any));
    this.renderer.setElementAttribute(this._el_62,'style','color:#9b9b9b;font-weight: bold;');
    this._text_63 = this.renderer.createText(this._el_62,'Don\'t have a account?',(null as any));
    this._el_64 = this.renderer.createElement(this._el_60,'button',(null as any));
    this.renderer.setElementAttribute(this._el_64,'clear','');
    this.renderer.setElementAttribute(this._el_64,'ion-button','');
    this.renderer.setElementAttribute(this._el_64,'style','font-weight:bold;font-size:13px;color:#fa8cb4;');
    this._appEl_64 = new import3.AppElement(64,60,this,this._el_64);
    var compView_64:any = import24.viewFactory_Button0(this.viewUtils,this.injector(64),this._appEl_64);
    this._Button_64_4 = new import24.Wrapper_Button((null as any),'',this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_64),this.renderer);
    this._appEl_64.initComponent(this._Button_64_4.context,([] as any[]),compView_64);
    this._text_65 = this.renderer.createText((null as any),' Sign up ',(null as any));
    compView_64.create(this._Button_64_4.context,[([] as any[]).concat([this._text_65])],(null as any));
    this._text_66 = this.renderer.createText(this._el_60,'\n        ',(null as any));
    this._text_67 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_68 = this.renderer.createElement((null as any),'hr',(null as any));
    this._text_69 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_70 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_70,'style','color:#c8c8c8;font-size:12px;');
    this._text_71 = this.renderer.createText(this._el_70,'By using HOROSCOPE APP,you agree to our Terms of Services and Privacy Policy ',(null as any));
    this._text_72 = this.renderer.createText((null as any),'\n',(null as any));
    compView_1.create(this._Content_1_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_2,
        this._el_3,
        this._text_12,
        this._el_13,
        this._text_14,
        this._el_15,
        this._text_28,
        this._el_29,
        this._text_30,
        this._el_31,
        this._text_33,
        this._el_34,
        this._text_49,
        this._el_50,
        this._text_52,
        this._el_53,
        this._text_55,
        this._el_56,
        this._text_57,
        this._el_58,
        this._text_59,
        this._el_60,
        this._text_67,
        this._el_68,
        this._text_69,
        this._el_70,
        this._text_72
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_29,'click',this.eventHandler(this._handle_click_29_0.bind(this)));
    var disposable_1:Function = this.renderer.listen(this._el_40,'ngModelChange',this.eventHandler(this._handle_ngModelChange_40_0.bind(this)));
    const subscription_0:any = this._NgModel_40_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_40_0.bind(this)));
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_5 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    this._expr_7 = import8.UNINITIALIZED;
    this._expr_8 = import8.UNINITIALIZED;
    this._expr_9 = import8.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_45,'ngModelChange',this.eventHandler(this._handle_ngModelChange_45_0.bind(this)));
    const subscription_1:any = this._NgModel_45_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_45_0.bind(this)));
    this._expr_14 = import8.UNINITIALIZED;
    this._expr_15 = import8.UNINITIALIZED;
    this._expr_16 = import8.UNINITIALIZED;
    this._expr_17 = import8.UNINITIALIZED;
    this._expr_18 = import8.UNINITIALIZED;
    this._expr_19 = import8.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_50,'click',this.eventHandler(this._handle_click_50_0.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_53,'click',this.eventHandler(this._handle_click_53_0.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_64,'click',this.eventHandler(this._handle_click_64_0.bind(this)));
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._el_7,
      this._el_8,
      this._el_9,
      this._text_10,
      this._text_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._el_15,
      this._text_16,
      this._el_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._el_21,
      this._text_22,
      this._el_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._text_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._el_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._text_72
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import35.Col) && ((7 <= requestNodeIndex) && (requestNodeIndex <= 9)))) { return this._Col_7_3.context; }
    if (((token === import35.Row) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Row_5_3.context; }
    if (((token === import35.Grid) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 11)))) { return this._Grid_3_3.context; }
    if (((token === import35.Col) && ((19 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Col_19_3.context; }
    if (((token === import35.Row) && ((17 <= requestNodeIndex) && (requestNodeIndex <= 26)))) { return this._Row_17_3.context; }
    if (((token === import35.Grid) && ((15 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Grid_15_3.context; }
    if (((token === import36.NgModel) && (40 === requestNodeIndex))) { return this._NgModel_40_4.context; }
    if (((token === import37.NgControl) && (40 === requestNodeIndex))) { return this._NgControl_40_5; }
    if (((token === import38.NgControlStatus) && (40 === requestNodeIndex))) { return this._NgControlStatus_40_6.context; }
    if (((token === import39.TextInput) && (40 === requestNodeIndex))) { return this._TextInput_40_7.context; }
    if (((token === import40.Item) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._Item_38_4.context; }
    if (((token === import40.ItemContent) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 41)))) { return this._ItemContent_38_5.context; }
    if (((token === import36.NgModel) && (45 === requestNodeIndex))) { return this._NgModel_45_4.context; }
    if (((token === import37.NgControl) && (45 === requestNodeIndex))) { return this._NgControl_45_5; }
    if (((token === import38.NgControlStatus) && (45 === requestNodeIndex))) { return this._NgControlStatus_45_6.context; }
    if (((token === import39.TextInput) && (45 === requestNodeIndex))) { return this._TextInput_45_7.context; }
    if (((token === import40.Item) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._Item_43_4.context; }
    if (((token === import40.ItemContent) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._ItemContent_43_5.context; }
    if (((token === import41.CardContent) && ((36 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._CardContent_36_3.context; }
    if (((token === import41.Card) && ((34 <= requestNodeIndex) && (requestNodeIndex <= 48)))) { return this._Card_34_3.context; }
    if (((token === import42.Button) && ((50 <= requestNodeIndex) && (requestNodeIndex <= 51)))) { return this._Button_50_4.context; }
    if (((token === import42.Button) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 54)))) { return this._Button_53_4.context; }
    if (((token === import42.Button) && ((64 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._Button_64_4.context; }
    if (((token === import35.Row) && ((60 <= requestNodeIndex) && (requestNodeIndex <= 66)))) { return this._Row_60_3.context; }
    if (((token === import43.Content) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 72)))) { return this._Content_1_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    if (this._Content_1_4.detectChangesInternal(this,this._el_1,throwOnChange)) { this._appEl_1.componentView.markAsCheckOnce(); }
    this._Grid_3_3.detectChangesInternal(this,this._el_3,throwOnChange);
    this._Row_5_3.detectChangesInternal(this,this._el_5,throwOnChange);
    this._Col_7_3.detectChangesInternal(this,this._el_7,throwOnChange);
    this._Grid_15_3.detectChangesInternal(this,this._el_15,throwOnChange);
    this._Row_17_3.detectChangesInternal(this,this._el_17,throwOnChange);
    this._Col_19_3.detectChangesInternal(this,this._el_19,throwOnChange);
    this._Card_34_3.detectChangesInternal(this,this._el_34,throwOnChange);
    this._CardContent_36_3.detectChangesInternal(this,this._el_36,throwOnChange);
    if (this._Item_38_4.detectChangesInternal(this,this._el_38,throwOnChange)) { this._appEl_38.componentView.markAsCheckOnce(); }
    this._ItemContent_38_5.detectChangesInternal(this,this._el_38,throwOnChange);
    const currVal_3:any = this.context.email;
    this._NgModel_40_4.check_model(currVal_3,throwOnChange,false);
    this._NgModel_40_4.detectChangesInternal(this,this._el_40,throwOnChange);
    this._NgControlStatus_40_6.detectChangesInternal(this,this._el_40,throwOnChange);
    const currVal_10:any = 'Email Address';
    this._TextInput_40_7.check_placeholder(currVal_10,throwOnChange,false);
    const currVal_11:any = 'email';
    this._TextInput_40_7.check_type(currVal_11,throwOnChange,false);
    this._TextInput_40_7.detectChangesInternal(this,this._el_40,throwOnChange);
    if (this._Item_43_4.detectChangesInternal(this,this._el_43,throwOnChange)) { this._appEl_43.componentView.markAsCheckOnce(); }
    this._ItemContent_43_5.detectChangesInternal(this,this._el_43,throwOnChange);
    const currVal_13:any = this.context.password;
    this._NgModel_45_4.check_model(currVal_13,throwOnChange,false);
    this._NgModel_45_4.detectChangesInternal(this,this._el_45,throwOnChange);
    this._NgControlStatus_45_6.detectChangesInternal(this,this._el_45,throwOnChange);
    const currVal_20:any = 'Password';
    this._TextInput_45_7.check_placeholder(currVal_20,throwOnChange,false);
    const currVal_21:any = 'password';
    this._TextInput_45_7.check_type(currVal_21,throwOnChange,false);
    this._TextInput_45_7.detectChangesInternal(this,this._el_45,throwOnChange);
    const currVal_23:any = '';
    this._Button_50_4.check_block(currVal_23,throwOnChange,false);
    if (this._Button_50_4.detectChangesInternal(this,this._el_50,throwOnChange)) { this._appEl_50.componentView.markAsCheckOnce(); }
    const currVal_25:any = '';
    this._Button_53_4.check_clear(currVal_25,throwOnChange,false);
    if (this._Button_53_4.detectChangesInternal(this,this._el_53,throwOnChange)) { this._appEl_53.componentView.markAsCheckOnce(); }
    this._Row_60_3.detectChangesInternal(this,this._el_60,throwOnChange);
    const currVal_27:any = '';
    this._Button_64_4.check_clear(currVal_27,throwOnChange,false);
    if (this._Button_64_4.detectChangesInternal(this,this._el_64,throwOnChange)) { this._appEl_64.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_38_1.dirty) {
        this._query_Button_38_1.reset(([] as any[]));
        this._Item_38_4.context._buttons = this._query_Button_38_1;
        this._query_Button_38_1.notifyOnChanges();
      }
      if (this._query_Icon_38_2.dirty) {
        this._query_Icon_38_2.reset(([] as any[]));
        this._Item_38_4.context._icons = this._query_Icon_38_2;
        this._query_Icon_38_2.notifyOnChanges();
      }
      if (this._query_Button_43_1.dirty) {
        this._query_Button_43_1.reset(([] as any[]));
        this._Item_43_4.context._buttons = this._query_Button_43_1;
        this._query_Button_43_1.notifyOnChanges();
      }
      if (this._query_Icon_43_2.dirty) {
        this._query_Icon_43_2.reset(([] as any[]));
        this._Item_43_4.context._icons = this._query_Icon_43_2;
        this._query_Icon_43_2.notifyOnChanges();
      }
      this._TextInput_40_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_38_4.context.ngAfterContentInit(); }
      this._TextInput_45_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_43_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_50_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_53_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_64_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Content_1_4.context._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementClass(this._el_1,'statusbar-padding',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_4:any = this._NgControlStatus_40_6.context.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_40,'ng-untouched',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = this._NgControlStatus_40_6.context.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_40,'ng-touched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatus_40_6.context.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_40,'ng-pristine',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_40_6.context.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_40,'ng-dirty',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_40_6.context.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_40,'ng-valid',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_40_6.context.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_40,'ng-invalid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_14:any = this._NgControlStatus_45_6.context.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_14,currVal_14)) {
      this.renderer.setElementClass(this._el_45,'ng-untouched',currVal_14);
      this._expr_14 = currVal_14;
    }
    const currVal_15:any = this._NgControlStatus_45_6.context.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_45,'ng-touched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_45_6.context.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_45,'ng-pristine',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_45_6.context.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_45,'ng-dirty',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_45_6.context.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_45,'ng-valid',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_45_6.context.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_45,'ng-invalid',currVal_19);
      this._expr_19 = currVal_19;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
  destroyInternal():void {
    this._NgModel_40_4.context.ngOnDestroy();
    this._TextInput_40_7.context.ngOnDestroy();
    this._NgModel_45_4.context.ngOnDestroy();
    this._TextInput_45_7.context.ngOnDestroy();
    this._Content_1_4.context.ngOnDestroy();
  }
  private _handle_click_29_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.loginFB()) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_40_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.email = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_45_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.password = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_50_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.loginEmail()) !== false);
    return (true && pd_0);
  }
  private _handle_click_53_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.forgotPassword()) !== false);
    return (true && pd_0);
  }
  private _handle_click_64_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.gotoSignUp()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_LoginPage0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<import0.LoginPage> {
  if ((renderType_LoginPage === (null as any))) { (renderType_LoginPage = viewUtils.createRenderComponentType('',0,import14.ViewEncapsulation.None,styles_LoginPage,{})); }
  return new _View_LoginPage0(viewUtils,parentInjector,declarationEl);
}