/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './home';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from 'ionic-angular/navigation/nav-params';
import * as import10 from 'ionic-angular/components/app/app';
import * as import11 from 'ionic-angular/components/alert/alert';
import * as import12 from 'ionic-angular/util/events';
import * as import13 from '@angular/http/src/http';
import * as import14 from 'ionic-angular/components/loading/loading';
import * as import15 from '@angular/core/src/metadata/view';
import * as import16 from '@angular/core/src/linker/component_factory';
import * as import17 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/refresher/refresher.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/refresher/refresher-content.ngfactory';
import * as import23 from '../../node_modules/@angular/common/src/directives/ng_if.ngfactory';
import * as import24 from 'ionic-angular/config/config';
import * as import25 from '@angular/core/src/linker/element_ref';
import * as import26 from 'ionic-angular/navigation/view-controller';
import * as import27 from 'ionic-angular/components/toolbar/toolbar';
import * as import28 from 'ionic-angular/util/keyboard';
import * as import29 from '@angular/core/src/zone/ng_zone';
import * as import30 from 'ionic-angular/components/tabs/tabs';
import * as import31 from 'ionic-angular/gestures/gesture-controller';
import * as import32 from '@angular/core/src/linker/template_ref';
import * as import33 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import34 from 'ionic-angular/components/navbar/navbar';
import * as import35 from 'ionic-angular/components/refresher/refresher-content';
import * as import36 from 'ionic-angular/components/refresher/refresher';
import * as import37 from '@angular/common/src/directives/ng_if';
import * as import38 from 'ionic-angular/components/content/content';
import * as import39 from '@angular/core/src/security';
import * as import40 from '../../node_modules/ionic-angular/components/grid/grid.ngfactory';
import * as import41 from 'ionic-angular/components/grid/grid';
export class Wrapper_HomePage {
  context:import0.HomePage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any,p6:any) {
    this.changed = false;
    this.context = new import0.HomePage(p0,p1,p2,p3,p4,p5,p6);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_HomePage_Host:import2.RenderComponentType = (null as any);
class _View_HomePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _HomePage_0_4:Wrapper_HomePage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HomePage_Host0,renderType_HomePage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-home',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_HomePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._HomePage_0_4 = new Wrapper_HomePage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.NavParams),this.parentInjector.get(import10.App),this.parentInjector.get(import11.AlertController),this.parentInjector.get(import12.Events),this.parentInjector.get(import13.Http),this.parentInjector.get(import14.LoadingController));
    this._appEl_0.initComponent(this._HomePage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._HomePage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.HomePage) && (0 === requestNodeIndex))) { return this._HomePage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._HomePage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HomePage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_HomePage_Host === (null as any))) { (renderType_HomePage_Host = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_HomePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const HomePageNgFactory:import16.ComponentFactory<import0.HomePage> = new import16.ComponentFactory<import0.HomePage>('page-home',viewFactory_HomePage_Host0,import0.HomePage);
const styles_HomePage:any[] = ([] as any[]);
var renderType_HomePage:import2.RenderComponentType = (null as any);
class _View_HomePage0 extends import1.AppView<import0.HomePage> {
  _el_0:any;
  _Header_0_3:import17.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import18.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import19.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import20.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  _Refresher_11_3:import21.Wrapper_Refresher;
  _text_12:any;
  _el_13:any;
  /*private*/ _appEl_13:import3.AppElement;
  _RefresherContent_13_4:import22.Wrapper_RefresherContent;
  _text_14:any;
  _text_15:any;
  _text_16:any;
  _anchor_17:any;
  /*private*/ _appEl_17:import3.AppElement;
  _TemplateRef_17_5:any;
  _NgIf_17_6:import23.Wrapper_NgIf;
  _text_18:any;
  _text_19:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_11:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HomePage0,renderType_HomePage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import17.Wrapper_Header(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import26.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n  ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'hideBackButton','');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import18.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import18.Wrapper_Navbar(this.parentInjector.get(import10.App),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import19.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import19.Wrapper_ToolbarTitle(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import27.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'Today',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'class','star-dark-bg');
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import20.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import20.Wrapper_Content(this.parentInjector.get(import24.Config),new import25.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import10.App),this.parentInjector.get(import28.Keyboard),this.parentInjector.get(import29.NgZone),this.parentInjector.get(import26.ViewController,(null as any)),this.parentInjector.get(import30.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'ion-refresher',(null as any));
    this._Refresher_11_3 = new import21.Wrapper_Refresher(this._Content_9_4.context,this.parentInjector.get(import29.NgZone),this.parentInjector.get(import31.GestureController));
    this._text_12 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'ion-refresher-content',(null as any));
    this.renderer.setElementAttribute(this._el_13,'pullMin','100');
    this.renderer.setElementAttribute(this._el_13,'pullingIcon','arrow-dropdown');
    this.renderer.setElementAttribute(this._el_13,'pullingText','Pull to refresh');
    this.renderer.setElementAttribute(this._el_13,'refreshingSpinner','circles');
    this.renderer.setElementAttribute(this._el_13,'refreshingText','Refreshing...');
    this._appEl_13 = new import3.AppElement(13,11,this,this._el_13);
    var compView_13:any = import22.viewFactory_RefresherContent0(this.viewUtils,this.injector(13),this._appEl_13);
    this._RefresherContent_13_4 = new import22.Wrapper_RefresherContent(this._Refresher_11_3.context,this.parentInjector.get(import24.Config));
    this._appEl_13.initComponent(this._RefresherContent_13_4.context,([] as any[]),compView_13);
    this._text_14 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_13.create(this._RefresherContent_13_4.context,([] as any[]),(null as any));
    this._text_15 = this.renderer.createText(this._el_11,'\n  ',(null as any));
    this._text_16 = this.renderer.createText((null as any),'\n  ',(null as any));
    this._anchor_17 = this.renderer.createTemplateAnchor((null as any),(null as any));
    this._appEl_17 = new import3.AppElement(17,9,this,this._anchor_17);
    this._TemplateRef_17_5 = new import32.TemplateRef_(this._appEl_17,viewFactory_HomePage1);
    this._NgIf_17_6 = new import23.Wrapper_NgIf(this._appEl_17.vcRef,this._TemplateRef_17_5);
    this._text_18 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._text_16,
        this._appEl_17,
        this._text_18
      ]
      ),
      ([] as any[]).concat([this._el_11])
    ]
    ,(null as any));
    this._text_19 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_11,'ionRefresh',this.eventHandler(this._handle_ionRefresh_11_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    const subscription_0:any = this._Refresher_11_3.context.ionRefresh.subscribe(this.eventHandler(this._handle_ionRefresh_11_0.bind(this)));
    this._expr_11 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._text_16,
      this._anchor_17,
      this._text_18,
      this._text_19
    ]
    ,[disposable_0],[subscription_0]);
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import33.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import34.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import27.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import35.RefresherContent) && ((13 <= requestNodeIndex) && (requestNodeIndex <= 14)))) { return this._RefresherContent_13_4.context; }
    if (((token === import36.Refresher) && ((11 <= requestNodeIndex) && (requestNodeIndex <= 15)))) { return this._Refresher_11_3.context; }
    if (((token === import32.TemplateRef) && (17 === requestNodeIndex))) { return this._TemplateRef_17_5; }
    if (((token === import37.NgIf) && (17 === requestNodeIndex))) { return this._NgIf_17_6.context; }
    if (((token === import38.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 18)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_0:any = '';
    this._Navbar_2_4.check_hideBackButton(currVal_0,throwOnChange,false);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    this._Refresher_11_3.detectChangesInternal(this,this._el_11,throwOnChange);
    const currVal_7:any = 'arrow-dropdown';
    this._RefresherContent_13_4.check_pullingIcon(currVal_7,throwOnChange,false);
    const currVal_8:any = 'Pull to refresh';
    this._RefresherContent_13_4.check_pullingText(currVal_8,throwOnChange,false);
    const currVal_9:any = 'circles';
    this._RefresherContent_13_4.check_refreshingSpinner(currVal_9,throwOnChange,false);
    const currVal_10:any = 'Refreshing...';
    this._RefresherContent_13_4.check_refreshingText(currVal_10,throwOnChange,false);
    this._RefresherContent_13_4.detectChangesInternal(this,this._el_13,throwOnChange);
    const currVal_12:any = this.context.isDataAvailable;
    this._NgIf_17_6.check_ngIf(currVal_12,throwOnChange,false);
    this._NgIf_17_6.detectChangesInternal(this,this._anchor_17,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_1:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_9_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_5:any = (this._Refresher_11_3.context.state !== 'inactive');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_11,'refresher-active',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._Refresher_11_3.context._top;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementStyle(this._el_11,'top',((this.viewUtils.sanitizer.sanitize(import39.SecurityContext.STYLE,currVal_6) == (null as any))? (null as any): this.viewUtils.sanitizer.sanitize(import39.SecurityContext.STYLE,currVal_6).toString()));
      this._expr_6 = currVal_6;
    }
    const currVal_11:any = this._RefresherContent_13_4.context.r.state;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementAttribute(this._el_13,'state',((currVal_11 == (null as any))? (null as any): currVal_11.toString()));
      this._expr_11 = currVal_11;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Refresher_11_3.context.ngOnDestroy();
    this._Content_9_4.context.ngOnDestroy();
  }
  private _handle_ionRefresh_11_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.doRefresh($event)) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_HomePage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.HomePage> {
  if ((renderType_HomePage === (null as any))) { (renderType_HomePage = viewUtils.createRenderComponentType('',0,import15.ViewEncapsulation.None,styles_HomePage,{})); }
  return new _View_HomePage0(viewUtils,parentInjector,declarationEl);
}
class _View_HomePage1 extends import1.AppView<any> {
  _el_0:any;
  _text_1:any;
  _el_2:any;
  _Row_2_3:import40.Wrapper_Row;
  _text_3:any;
  _el_4:any;
  _Col_4_3:import40.Wrapper_Col;
  _text_5:any;
  _el_6:any;
  _text_7:any;
  _el_8:any;
  _text_9:any;
  _text_10:any;
  _text_11:any;
  _el_12:any;
  _Col_12_3:import40.Wrapper_Col;
  _text_13:any;
  _el_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _text_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _Row_22_3:import40.Wrapper_Row;
  _text_23:any;
  _el_24:any;
  _Col_24_3:import40.Wrapper_Col;
  _text_25:any;
  _el_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _el_31:any;
  _text_32:any;
  _text_33:any;
  _text_34:any;
  _el_35:any;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _text_42:any;
  _text_43:any;
  _text_44:any;
  _text_45:any;
  _el_46:any;
  _Row_46_3:import40.Wrapper_Row;
  _text_47:any;
  _el_48:any;
  _Col_48_3:import40.Wrapper_Col;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _el_52:any;
  _text_53:any;
  _el_54:any;
  _el_55:any;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _el_70:any;
  _Row_70_3:import40.Wrapper_Row;
  _text_71:any;
  _el_72:any;
  _Col_72_3:import40.Wrapper_Col;
  _text_73:any;
  _el_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _el_78:any;
  _el_79:any;
  _text_80:any;
  _text_81:any;
  _text_82:any;
  _el_83:any;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _el_87:any;
  _text_88:any;
  _text_89:any;
  _text_90:any;
  _text_91:any;
  _text_92:any;
  _text_93:any;
  _el_94:any;
  _Row_94_3:import40.Wrapper_Row;
  _text_95:any;
  _el_96:any;
  _Col_96_3:import40.Wrapper_Col;
  _text_97:any;
  _el_98:any;
  _text_99:any;
  _el_100:any;
  _text_101:any;
  _el_102:any;
  _el_103:any;
  _text_104:any;
  _text_105:any;
  _text_106:any;
  _el_107:any;
  _text_108:any;
  _el_109:any;
  _text_110:any;
  _el_111:any;
  _text_112:any;
  _text_113:any;
  _text_114:any;
  _text_115:any;
  _text_116:any;
  _text_117:any;
  _el_118:any;
  _Row_118_3:import40.Wrapper_Row;
  _text_119:any;
  _el_120:any;
  _Col_120_3:import40.Wrapper_Col;
  _text_121:any;
  _el_122:any;
  _text_123:any;
  _el_124:any;
  _text_125:any;
  _el_126:any;
  _el_127:any;
  _text_128:any;
  _text_129:any;
  _text_130:any;
  _el_131:any;
  _text_132:any;
  _el_133:any;
  _text_134:any;
  _el_135:any;
  _text_136:any;
  _text_137:any;
  _text_138:any;
  _text_139:any;
  _text_140:any;
  _text_141:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_HomePage1,renderType_HomePage,import6.ViewType.EMBEDDED,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_0,'class','homePage');
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','header-wrapper');
    this._Row_2_3 = new import40.Wrapper_Row();
    this._text_3 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_4 = this.renderer.createElement(this._el_2,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_4,'class','col-40');
    this._Col_4_3 = new import40.Wrapper_Col();
    this._text_5 = this.renderer.createText(this._el_4,'\n        ',(null as any));
    this._el_6 = this.renderer.createElement(this._el_4,'div',(null as any));
    this.renderer.setElementAttribute(this._el_6,'class','zodiac-single');
    this._text_7 = this.renderer.createText(this._el_6,'\n          ',(null as any));
    this._el_8 = this.renderer.createElement(this._el_6,'img',(null as any));
    this._text_9 = this.renderer.createText(this._el_6,'\n        ',(null as any));
    this._text_10 = this.renderer.createText(this._el_4,'\n      ',(null as any));
    this._text_11 = this.renderer.createText(this._el_2,'\n      ',(null as any));
    this._el_12 = this.renderer.createElement(this._el_2,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_12,'class','col-60 flex-vertical-center');
    this._Col_12_3 = new import40.Wrapper_Col();
    this._text_13 = this.renderer.createText(this._el_12,'\n        ',(null as any));
    this._el_14 = this.renderer.createElement(this._el_12,'div',(null as any));
    this.renderer.setElementAttribute(this._el_14,'class','title');
    this._text_15 = this.renderer.createText(this._el_14,'\n          ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'h4',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'',(null as any));
    this._text_18 = this.renderer.createText(this._el_14,'\n        ',(null as any));
    this._text_19 = this.renderer.createText(this._el_12,'\n      ',(null as any));
    this._text_20 = this.renderer.createText(this._el_2,'\n    ',(null as any));
    this._text_21 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_0,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','content-section');
    this._Row_22_3 = new import40.Wrapper_Row();
    this._text_23 = this.renderer.createText(this._el_22,'\n      ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_24,'padding','');
    this._Col_24_3 = new import40.Wrapper_Col();
    this._text_25 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._el_26 = this.renderer.createElement(this._el_24,'div',(null as any));
    this.renderer.setElementAttribute(this._el_26,'class','title-wrapper');
    this._text_27 = this.renderer.createText(this._el_26,'\n          ',(null as any));
    this._el_28 = this.renderer.createElement(this._el_26,'i',(null as any));
    this.renderer.setElementAttribute(this._el_28,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_28,'class','fa fa-2 fa-briefcase white-color');
    this._text_29 = this.renderer.createText(this._el_26,'\n          ',(null as any));
    this._el_30 = this.renderer.createElement(this._el_26,'span',(null as any));
    this.renderer.setElementAttribute(this._el_30,'class','pink-title t-uppercase');
    this._el_31 = this.renderer.createElement(this._el_30,'strong',(null as any));
    this._text_32 = this.renderer.createText(this._el_31,' Work ',(null as any));
    this._text_33 = this.renderer.createText(this._el_26,'\n        ',(null as any));
    this._text_34 = this.renderer.createText(this._el_24,'\n        ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_24,'div',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','content-wrapper');
    this._text_36 = this.renderer.createText(this._el_35,'\n          ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'div',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','work');
    this._text_38 = this.renderer.createText(this._el_37,'\n            ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'p',(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'',(null as any));
    this._text_41 = this.renderer.createText(this._el_37,'\n          ',(null as any));
    this._text_42 = this.renderer.createText(this._el_35,'\n        ',(null as any));
    this._text_43 = this.renderer.createText(this._el_24,'\n      ',(null as any));
    this._text_44 = this.renderer.createText(this._el_22,'\n    ',(null as any));
    this._text_45 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_0,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_46,'class','content-section');
    this._Row_46_3 = new import40.Wrapper_Row();
    this._text_47 = this.renderer.createText(this._el_46,'\n      ',(null as any));
    this._el_48 = this.renderer.createElement(this._el_46,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_48,'padding','');
    this._Col_48_3 = new import40.Wrapper_Col();
    this._text_49 = this.renderer.createText(this._el_48,'\n        ',(null as any));
    this._el_50 = this.renderer.createElement(this._el_48,'div',(null as any));
    this.renderer.setElementAttribute(this._el_50,'class','title-wrapper');
    this._text_51 = this.renderer.createText(this._el_50,'\n          ',(null as any));
    this._el_52 = this.renderer.createElement(this._el_50,'i',(null as any));
    this.renderer.setElementAttribute(this._el_52,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_52,'class','fa fa-2 fa-money white-color');
    this._text_53 = this.renderer.createText(this._el_50,'\n          ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_50,'span',(null as any));
    this.renderer.setElementAttribute(this._el_54,'class','pink-title t-uppercase');
    this._el_55 = this.renderer.createElement(this._el_54,'strong',(null as any));
    this._text_56 = this.renderer.createText(this._el_55,' Finance ',(null as any));
    this._text_57 = this.renderer.createText(this._el_50,'\n        ',(null as any));
    this._text_58 = this.renderer.createText(this._el_48,'\n        ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_48,'div',(null as any));
    this.renderer.setElementAttribute(this._el_59,'class','content-wrapper');
    this._text_60 = this.renderer.createText(this._el_59,'\n          ',(null as any));
    this._el_61 = this.renderer.createElement(this._el_59,'div',(null as any));
    this.renderer.setElementAttribute(this._el_61,'class','finance');
    this._text_62 = this.renderer.createText(this._el_61,'\n            ',(null as any));
    this._el_63 = this.renderer.createElement(this._el_61,'p',(null as any));
    this._text_64 = this.renderer.createText(this._el_63,'',(null as any));
    this._text_65 = this.renderer.createText(this._el_61,'\n          ',(null as any));
    this._text_66 = this.renderer.createText(this._el_59,'\n        ',(null as any));
    this._text_67 = this.renderer.createText(this._el_48,'\n      ',(null as any));
    this._text_68 = this.renderer.createText(this._el_46,'\n    ',(null as any));
    this._text_69 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_70 = this.renderer.createElement(this._el_0,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_70,'class','content-section');
    this._Row_70_3 = new import40.Wrapper_Row();
    this._text_71 = this.renderer.createText(this._el_70,'\n      ',(null as any));
    this._el_72 = this.renderer.createElement(this._el_70,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_72,'padding','');
    this._Col_72_3 = new import40.Wrapper_Col();
    this._text_73 = this.renderer.createText(this._el_72,'\n        ',(null as any));
    this._el_74 = this.renderer.createElement(this._el_72,'div',(null as any));
    this.renderer.setElementAttribute(this._el_74,'class','title-wrapper');
    this._text_75 = this.renderer.createText(this._el_74,'\n          ',(null as any));
    this._el_76 = this.renderer.createElement(this._el_74,'i',(null as any));
    this.renderer.setElementAttribute(this._el_76,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_76,'class','fa fa-2 fa-heart white-color');
    this._text_77 = this.renderer.createText(this._el_74,'\n          ',(null as any));
    this._el_78 = this.renderer.createElement(this._el_74,'span',(null as any));
    this.renderer.setElementAttribute(this._el_78,'class','pink-title t-uppercase');
    this._el_79 = this.renderer.createElement(this._el_78,'strong',(null as any));
    this._text_80 = this.renderer.createText(this._el_79,' Love ',(null as any));
    this._text_81 = this.renderer.createText(this._el_74,'\n        ',(null as any));
    this._text_82 = this.renderer.createText(this._el_72,'\n        ',(null as any));
    this._el_83 = this.renderer.createElement(this._el_72,'div',(null as any));
    this.renderer.setElementAttribute(this._el_83,'class','content-wrapper');
    this._text_84 = this.renderer.createText(this._el_83,'\n          ',(null as any));
    this._el_85 = this.renderer.createElement(this._el_83,'div',(null as any));
    this.renderer.setElementAttribute(this._el_85,'class','love');
    this._text_86 = this.renderer.createText(this._el_85,'\n            ',(null as any));
    this._el_87 = this.renderer.createElement(this._el_85,'p',(null as any));
    this._text_88 = this.renderer.createText(this._el_87,'',(null as any));
    this._text_89 = this.renderer.createText(this._el_85,'\n          ',(null as any));
    this._text_90 = this.renderer.createText(this._el_83,'\n        ',(null as any));
    this._text_91 = this.renderer.createText(this._el_72,'\n      ',(null as any));
    this._text_92 = this.renderer.createText(this._el_70,'\n    ',(null as any));
    this._text_93 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_94 = this.renderer.createElement(this._el_0,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_94,'class','content-section');
    this._Row_94_3 = new import40.Wrapper_Row();
    this._text_95 = this.renderer.createText(this._el_94,'\n      ',(null as any));
    this._el_96 = this.renderer.createElement(this._el_94,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_96,'padding','');
    this._Col_96_3 = new import40.Wrapper_Col();
    this._text_97 = this.renderer.createText(this._el_96,'\n        ',(null as any));
    this._el_98 = this.renderer.createElement(this._el_96,'div',(null as any));
    this.renderer.setElementAttribute(this._el_98,'class','title-wrapper');
    this._text_99 = this.renderer.createText(this._el_98,'\n          ',(null as any));
    this._el_100 = this.renderer.createElement(this._el_98,'i',(null as any));
    this.renderer.setElementAttribute(this._el_100,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_100,'class','fa fa-2 fa-heartbeat white-color');
    this._text_101 = this.renderer.createText(this._el_98,'\n          ',(null as any));
    this._el_102 = this.renderer.createElement(this._el_98,'span',(null as any));
    this.renderer.setElementAttribute(this._el_102,'class','pink-title t-uppercase');
    this._el_103 = this.renderer.createElement(this._el_102,'strong',(null as any));
    this._text_104 = this.renderer.createText(this._el_103,' Healthy ',(null as any));
    this._text_105 = this.renderer.createText(this._el_98,'\n        ',(null as any));
    this._text_106 = this.renderer.createText(this._el_96,'\n        ',(null as any));
    this._el_107 = this.renderer.createElement(this._el_96,'div',(null as any));
    this.renderer.setElementAttribute(this._el_107,'class','content-wrapper');
    this._text_108 = this.renderer.createText(this._el_107,'\n          ',(null as any));
    this._el_109 = this.renderer.createElement(this._el_107,'div',(null as any));
    this.renderer.setElementAttribute(this._el_109,'class','healthy');
    this._text_110 = this.renderer.createText(this._el_109,'\n            ',(null as any));
    this._el_111 = this.renderer.createElement(this._el_109,'p',(null as any));
    this._text_112 = this.renderer.createText(this._el_111,'',(null as any));
    this._text_113 = this.renderer.createText(this._el_109,'\n          ',(null as any));
    this._text_114 = this.renderer.createText(this._el_107,'\n        ',(null as any));
    this._text_115 = this.renderer.createText(this._el_96,'\n      ',(null as any));
    this._text_116 = this.renderer.createText(this._el_94,'\n    ',(null as any));
    this._text_117 = this.renderer.createText(this._el_0,'\n\n    ',(null as any));
    this._el_118 = this.renderer.createElement(this._el_0,'ion-row',(null as any));
    this.renderer.setElementAttribute(this._el_118,'class','content-section');
    this._Row_118_3 = new import40.Wrapper_Row();
    this._text_119 = this.renderer.createText(this._el_118,'\n      ',(null as any));
    this._el_120 = this.renderer.createElement(this._el_118,'ion-col',(null as any));
    this.renderer.setElementAttribute(this._el_120,'padding','');
    this._Col_120_3 = new import40.Wrapper_Col();
    this._text_121 = this.renderer.createText(this._el_120,'\n        ',(null as any));
    this._el_122 = this.renderer.createElement(this._el_120,'div',(null as any));
    this.renderer.setElementAttribute(this._el_122,'class','title-wrapper');
    this._text_123 = this.renderer.createText(this._el_122,'\n          ',(null as any));
    this._el_124 = this.renderer.createElement(this._el_122,'i',(null as any));
    this.renderer.setElementAttribute(this._el_124,'aria-hidden','true');
    this.renderer.setElementAttribute(this._el_124,'class','fa fa-2 fa-diamond white-color');
    this._text_125 = this.renderer.createText(this._el_122,'\n          ',(null as any));
    this._el_126 = this.renderer.createElement(this._el_122,'span',(null as any));
    this.renderer.setElementAttribute(this._el_126,'class','pink-title t-uppercase');
    this._el_127 = this.renderer.createElement(this._el_126,'strong',(null as any));
    this._text_128 = this.renderer.createText(this._el_127,' Luck ',(null as any));
    this._text_129 = this.renderer.createText(this._el_122,'\n        ',(null as any));
    this._text_130 = this.renderer.createText(this._el_120,'\n        ',(null as any));
    this._el_131 = this.renderer.createElement(this._el_120,'div',(null as any));
    this.renderer.setElementAttribute(this._el_131,'class','content-wrapper');
    this._text_132 = this.renderer.createText(this._el_131,'\n          ',(null as any));
    this._el_133 = this.renderer.createElement(this._el_131,'div',(null as any));
    this.renderer.setElementAttribute(this._el_133,'class','luck');
    this._text_134 = this.renderer.createText(this._el_133,'\n            ',(null as any));
    this._el_135 = this.renderer.createElement(this._el_133,'p',(null as any));
    this._text_136 = this.renderer.createText(this._el_135,'',(null as any));
    this._text_137 = this.renderer.createText(this._el_133,'\n          ',(null as any));
    this._text_138 = this.renderer.createText(this._el_131,'\n        ',(null as any));
    this._text_139 = this.renderer.createText(this._el_120,'\n      ',(null as any));
    this._text_140 = this.renderer.createText(this._el_118,'\n    ',(null as any));
    this._text_141 = this.renderer.createText(this._el_0,'\n\n  ',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_3 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this.init(([] as any[]).concat([this._el_0]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._el_6,
      this._text_7,
      this._el_8,
      this._text_9,
      this._text_10,
      this._text_11,
      this._el_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._text_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._el_31,
      this._text_32,
      this._text_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._text_42,
      this._text_43,
      this._text_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._el_70,
      this._text_71,
      this._el_72,
      this._text_73,
      this._el_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._el_78,
      this._el_79,
      this._text_80,
      this._text_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._text_89,
      this._text_90,
      this._text_91,
      this._text_92,
      this._text_93,
      this._el_94,
      this._text_95,
      this._el_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._el_100,
      this._text_101,
      this._el_102,
      this._el_103,
      this._text_104,
      this._text_105,
      this._text_106,
      this._el_107,
      this._text_108,
      this._el_109,
      this._text_110,
      this._el_111,
      this._text_112,
      this._text_113,
      this._text_114,
      this._text_115,
      this._text_116,
      this._text_117,
      this._el_118,
      this._text_119,
      this._el_120,
      this._text_121,
      this._el_122,
      this._text_123,
      this._el_124,
      this._text_125,
      this._el_126,
      this._el_127,
      this._text_128,
      this._text_129,
      this._text_130,
      this._el_131,
      this._text_132,
      this._el_133,
      this._text_134,
      this._el_135,
      this._text_136,
      this._text_137,
      this._text_138,
      this._text_139,
      this._text_140,
      this._text_141
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import41.Col) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 10)))) { return this._Col_4_3.context; }
    if (((token === import41.Col) && ((12 <= requestNodeIndex) && (requestNodeIndex <= 19)))) { return this._Col_12_3.context; }
    if (((token === import41.Row) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 20)))) { return this._Row_2_3.context; }
    if (((token === import41.Col) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 43)))) { return this._Col_24_3.context; }
    if (((token === import41.Row) && ((22 <= requestNodeIndex) && (requestNodeIndex <= 44)))) { return this._Row_22_3.context; }
    if (((token === import41.Col) && ((48 <= requestNodeIndex) && (requestNodeIndex <= 67)))) { return this._Col_48_3.context; }
    if (((token === import41.Row) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 68)))) { return this._Row_46_3.context; }
    if (((token === import41.Col) && ((72 <= requestNodeIndex) && (requestNodeIndex <= 91)))) { return this._Col_72_3.context; }
    if (((token === import41.Row) && ((70 <= requestNodeIndex) && (requestNodeIndex <= 92)))) { return this._Row_70_3.context; }
    if (((token === import41.Col) && ((96 <= requestNodeIndex) && (requestNodeIndex <= 115)))) { return this._Col_96_3.context; }
    if (((token === import41.Row) && ((94 <= requestNodeIndex) && (requestNodeIndex <= 116)))) { return this._Row_94_3.context; }
    if (((token === import41.Col) && ((120 <= requestNodeIndex) && (requestNodeIndex <= 139)))) { return this._Col_120_3.context; }
    if (((token === import41.Row) && ((118 <= requestNodeIndex) && (requestNodeIndex <= 140)))) { return this._Row_118_3.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Row_2_3.detectChangesInternal(this,this._el_2,throwOnChange);
    this._Col_4_3.detectChangesInternal(this,this._el_4,throwOnChange);
    this._Col_12_3.detectChangesInternal(this,this._el_12,throwOnChange);
    this._Row_22_3.detectChangesInternal(this,this._el_22,throwOnChange);
    this._Col_24_3.detectChangesInternal(this,this._el_24,throwOnChange);
    this._Row_46_3.detectChangesInternal(this,this._el_46,throwOnChange);
    this._Col_48_3.detectChangesInternal(this,this._el_48,throwOnChange);
    this._Row_70_3.detectChangesInternal(this,this._el_70,throwOnChange);
    this._Col_72_3.detectChangesInternal(this,this._el_72,throwOnChange);
    this._Row_94_3.detectChangesInternal(this,this._el_94,throwOnChange);
    this._Col_96_3.detectChangesInternal(this,this._el_96,throwOnChange);
    this._Row_118_3.detectChangesInternal(this,this._el_118,throwOnChange);
    this._Col_120_3.detectChangesInternal(this,this._el_120,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = import4.interpolate(1,'',this.parent.context.imgsign,'');
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_8,'src',this.viewUtils.sanitizer.sanitize(import39.SecurityContext.URL,currVal_0));
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = import4.interpolate(1,'',this.parent.context.result.title,'');
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setText(this._text_17,currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = import4.interpolate(1,' ',this.parent.context.result.work,' ');
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setText(this._text_40,currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = import4.interpolate(1,' ',this.parent.context.result.finance,' ');
    if (import4.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setText(this._text_64,currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import4.interpolate(1,' ',this.parent.context.result.love,' ');
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setText(this._text_88,currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_5:any = import4.interpolate(1,' ',this.parent.context.result.healthy,' ');
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setText(this._text_112,currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = import4.interpolate(1,' ',this.parent.context.result.luck,' ');
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setText(this._text_136,currVal_6);
      this._expr_6 = currVal_6;
    }
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_HomePage1(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  return new _View_HomePage1(viewUtils,parentInjector,declarationEl);
}