/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from '@angular/core/src/linker/ng_module_factory';
import * as import1 from './app.module';
import * as import2 from '@angular/common/src/common_module';
import * as import3 from '@angular/core/src/application_module';
import * as import4 from '@angular/platform-browser/src/browser';
import * as import5 from '@angular/http/src/http_module';
import * as import6 from '@angular/forms/src/directives';
import * as import7 from '@angular/forms/src/form_providers';
import * as import8 from 'ionic-angular/module';
import * as import9 from '@ionic/cloud-angular/dist/es5/index';
import * as import10 from '@angular/common/src/localization';
import * as import11 from 'ionic-angular/util/ionic-error-handler';
import * as import12 from 'ionic-angular/components/app/app';
import * as import13 from '@angular/core/src/application_init';
import * as import14 from '@angular/core/src/testability/testability';
import * as import15 from '@angular/core/src/application_ref';
import * as import16 from '@angular/core/src/linker/compiler';
import * as import17 from 'ionic-angular/gestures/gesture-config';
import * as import18 from '@angular/platform-browser/src/dom/events/event_manager';
import * as import19 from '@angular/platform-browser/src/dom/shared_styles_host';
import * as import20 from '@angular/platform-browser/src/dom/dom_renderer';
import * as import21 from '@angular/platform-browser/src/security/dom_sanitization_service';
import * as import22 from '@angular/core/src/linker/view_utils';
import * as import23 from '@angular/platform-browser/src/browser/title';
import * as import24 from '@angular/http/src/backends/browser_xhr';
import * as import25 from '@angular/http/src/base_response_options';
import * as import26 from '@angular/http/src/backends/xhr_backend';
import * as import27 from '@angular/http/src/base_request_options';
import * as import28 from '@angular/forms/src/directives/radio_control_value_accessor';
import * as import29 from '@angular/forms/src/form_builder';
import * as import30 from 'ionic-angular/components/action-sheet/action-sheet';
import * as import31 from 'ionic-angular/components/alert/alert';
import * as import32 from 'ionic-angular/util/events';
import * as import33 from 'ionic-angular/util/form';
import * as import34 from 'ionic-angular/util/haptic';
import * as import35 from 'ionic-angular/gestures/gesture-controller';
import * as import36 from 'ionic-angular/util/keyboard';
import * as import37 from 'ionic-angular/components/loading/loading';
import * as import38 from '@angular/common/src/location/location';
import * as import39 from 'ionic-angular/components/menu/menu-controller';
import * as import40 from 'ionic-angular/components/modal/modal';
import * as import41 from 'ionic-angular/components/picker/picker';
import * as import42 from 'ionic-angular/components/popover/popover';
import * as import43 from 'ionic-angular/components/tap-click/tap-click';
import * as import44 from 'ionic-angular/components/toast/toast';
import * as import45 from 'ionic-angular/transitions/transition-controller';
import * as import46 from '@angular/core/src/di/injector';
import * as import47 from '../node_modules/ionic-angular/components/action-sheet/action-sheet-component.ngfactory';
import * as import48 from '../node_modules/ionic-angular/components/alert/alert-component.ngfactory';
import * as import49 from '../node_modules/ionic-angular/components/app/app-root.ngfactory';
import * as import50 from '../node_modules/ionic-angular/components/loading/loading-component.ngfactory';
import * as import51 from '../node_modules/ionic-angular/components/modal/modal-component.ngfactory';
import * as import52 from '../node_modules/ionic-angular/components/picker/picker-component.ngfactory';
import * as import53 from '../node_modules/ionic-angular/components/popover/popover-component.ngfactory';
import * as import54 from '../node_modules/ionic-angular/components/toast/toast-component.ngfactory';
import * as import55 from './app.component.ngfactory';
import * as import56 from '../pages/browse/browse.ngfactory';
import * as import57 from '../pages/horoscope/horoscope.ngfactory';
import * as import58 from '../pages/profile/profile.ngfactory';
import * as import59 from '../pages/home/home.ngfactory';
import * as import60 from '../pages/tabs/tabs.ngfactory';
import * as import61 from '../pages/login/login.ngfactory';
import * as import62 from '../pages/signup/signup.ngfactory';
import * as import63 from '../pages/privacy-policy/privacy-policy.ngfactory';
import * as import64 from '../pages/terms-of-services/terms-of-services.ngfactory';
import * as import65 from '../pages/tutorial/tutorial.ngfactory';
import * as import66 from '@angular/core/src/application_tokens';
import * as import67 from '@angular/platform-browser/src/dom/events/dom_events';
import * as import68 from '@angular/platform-browser/src/dom/events/key_events';
import * as import69 from '@angular/platform-browser/src/dom/events/hammer_gestures';
import * as import70 from '@angular/core/src/zone/ng_zone';
import * as import71 from '@angular/platform-browser/src/dom/debug/ng_probe';
import * as import72 from './app.component';
import * as import73 from '@angular/common/src/location/platform_location';
import * as import74 from '@angular/common/src/location/location_strategy';
import * as import75 from 'ionic-angular/navigation/url-serializer';
import * as import76 from 'ionic-angular/navigation/deep-linker';
import * as import77 from 'ionic-angular/platform/query-params';
import * as import78 from 'ionic-angular/platform/platform-registry';
import * as import79 from 'ionic-angular/platform/platform';
import * as import80 from 'ionic-angular/config/config';
import * as import81 from 'ionic-angular/config/mode-registry';
import * as import82 from 'ionic-angular/transitions/transition-registry';
import * as import83 from '@angular/core/src/console';
import * as import84 from '@angular/core/src/i18n/tokens';
import * as import85 from '@angular/core/src/error_handler';
import * as import86 from '@angular/platform-browser/src/dom/dom_tokens';
import * as import87 from '@angular/platform-browser/src/dom/animation_driver';
import * as import88 from '@angular/core/src/render/api';
import * as import89 from '@angular/core/src/security';
import * as import90 from '@angular/core/src/change_detection/differs/iterable_differs';
import * as import91 from '@angular/core/src/change_detection/differs/keyvalue_differs';
import * as import92 from '@angular/http/src/interfaces';
import * as import93 from '@angular/http/src/http';
import * as import94 from 'ionic-angular/components/app/app-root';
class AppModuleInjector extends import0.NgModuleInjector<import1.AppModule> {
  _CommonModule_0:import2.CommonModule;
  _ApplicationModule_1:import3.ApplicationModule;
  _BrowserModule_2:import4.BrowserModule;
  _HttpModule_3:import5.HttpModule;
  _InternalFormsSharedModule_4:import6.InternalFormsSharedModule;
  _FormsModule_5:import7.FormsModule;
  _ReactiveFormsModule_6:import7.ReactiveFormsModule;
  _IonicModule_7:import8.IonicModule;
  _CloudModule_8:import9.CloudModule;
  _AppModule_9:import1.AppModule;
  __LOCALE_ID_10:any;
  __NgLocalization_11:import10.NgLocaleLocalization;
  _ErrorHandler_12:import11.IonicErrorHandler;
  _ConfigToken_13:any;
  _UrlToken_14:any;
  _QueryParams_15:any;
  _PlatformConfigToken_16:any;
  _UserAgentToken_17:any;
  _NavigatorPlatformToken_18:any;
  _DocumentDirToken_19:any;
  _DocLangToken_20:any;
  _Platform_21:any;
  _Config_22:any;
  _App_23:import12.App;
  _APP_INITIALIZER_24:any[];
  _ApplicationInitStatus_25:import13.ApplicationInitStatus;
  _Testability_26:import14.Testability;
  _ApplicationRef__27:import15.ApplicationRef_;
  __ApplicationRef_28:any;
  __Compiler_29:import16.Compiler;
  __APP_ID_30:any;
  __DOCUMENT_31:any;
  __HAMMER_GESTURE_CONFIG_32:import17.IonicGestureConfig;
  __EVENT_MANAGER_PLUGINS_33:any[];
  __EventManager_34:import18.EventManager;
  __DomSharedStylesHost_35:import19.DomSharedStylesHost;
  __AnimationDriver_36:any;
  __DomRootRenderer_37:import20.DomRootRenderer_;
  __RootRenderer_38:any;
  __DomSanitizer_39:import21.DomSanitizerImpl;
  __Sanitizer_40:any;
  __ViewUtils_41:import22.ViewUtils;
  __IterableDiffers_42:any;
  __KeyValueDiffers_43:any;
  __SharedStylesHost_44:any;
  __Title_45:import23.Title;
  __BrowserXhr_46:import24.BrowserXhr;
  __ResponseOptions_47:import25.BaseResponseOptions;
  __XSRFStrategy_48:any;
  __XHRBackend_49:import26.XHRBackend;
  __RequestOptions_50:import27.BaseRequestOptions;
  __Http_51:any;
  __RadioControlRegistry_52:import28.RadioControlRegistry;
  __FormBuilder_53:import29.FormBuilder;
  __AppRootToken_54:any;
  __DeepLinkConfigToken_55:any;
  __ActionSheetController_56:import30.ActionSheetController;
  __AlertController_57:import31.AlertController;
  __Events_58:import32.Events;
  __Form_59:import33.Form;
  __Haptic_60:import34.Haptic;
  __GestureController_61:import35.GestureController;
  __Keyboard_62:import36.Keyboard;
  __LoadingController_63:import37.LoadingController;
  __LocationStrategy_64:any;
  __Location_65:import38.Location;
  __MenuController_66:import39.MenuController;
  __ModalController_67:import40.ModalController;
  __PickerController_68:import41.PickerController;
  __PopoverController_69:import42.PopoverController;
  __TapClick_70:import43.TapClick;
  __ToastController_71:import44.ToastController;
  __TransitionController_72:import45.TransitionController;
  __UrlSerializer_73:any;
  __DeepLinker_74:any;
  __CloudSettingsToken_75:any;
  __DIContainer_76:any;
  __Auth_77:any;
  __Client_78:any;
  __Config_79:any;
  __Database_80:any;
  __Deploy_81:any;
  __Push_82:any;
  __User_83:any;
  __FacebookAuth_84:any;
  __GoogleAuth_85:any;
  constructor(parent:import46.Injector) {
    super(parent,[
      import47.ActionSheetCmpNgFactory,
      import48.AlertCmpNgFactory,
      import49.IonicAppNgFactory,
      import50.LoadingCmpNgFactory,
      import51.ModalCmpNgFactory,
      import52.PickerCmpNgFactory,
      import53.PopoverCmpNgFactory,
      import54.ToastCmpNgFactory,
      import55.MyAppNgFactory,
      import55.MyAppNgFactory,
      import56.BrowsePageNgFactory,
      import57.HoroscopePageNgFactory,
      import58.ProfilePageNgFactory,
      import59.HomePageNgFactory,
      import60.TabsPageNgFactory,
      import61.LoginPageNgFactory,
      import62.SignupPageNgFactory,
      import63.PrivacyPolicyPageNgFactory,
      import64.TermsOfServicesPageNgFactory,
      import65.TutorialPageNgFactory,
      import49.IonicAppNgFactory
    ]
    ,[import49.IonicAppNgFactory]);
  }
  get _LOCALE_ID_10():any {
    if ((this.__LOCALE_ID_10 == (null as any))) { (this.__LOCALE_ID_10 = 'en-US'); }
    return this.__LOCALE_ID_10;
  }
  get _NgLocalization_11():import10.NgLocaleLocalization {
    if ((this.__NgLocalization_11 == (null as any))) { (this.__NgLocalization_11 = new import10.NgLocaleLocalization(this._LOCALE_ID_10)); }
    return this.__NgLocalization_11;
  }
  get _ApplicationRef_28():any {
    if ((this.__ApplicationRef_28 == (null as any))) { (this.__ApplicationRef_28 = this._ApplicationRef__27); }
    return this.__ApplicationRef_28;
  }
  get _Compiler_29():import16.Compiler {
    if ((this.__Compiler_29 == (null as any))) { (this.__Compiler_29 = new import16.Compiler()); }
    return this.__Compiler_29;
  }
  get _APP_ID_30():any {
    if ((this.__APP_ID_30 == (null as any))) { (this.__APP_ID_30 = import66._appIdRandomProviderFactory()); }
    return this.__APP_ID_30;
  }
  get _DOCUMENT_31():any {
    if ((this.__DOCUMENT_31 == (null as any))) { (this.__DOCUMENT_31 = import4._document()); }
    return this.__DOCUMENT_31;
  }
  get _HAMMER_GESTURE_CONFIG_32():import17.IonicGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_32 == (null as any))) { (this.__HAMMER_GESTURE_CONFIG_32 = new import17.IonicGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_32;
  }
  get _EVENT_MANAGER_PLUGINS_33():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_33 == (null as any))) { (this.__EVENT_MANAGER_PLUGINS_33 = [
      new import67.DomEventsPlugin(),
      new import68.KeyEventsPlugin(),
      new import69.HammerGesturesPlugin(this._HAMMER_GESTURE_CONFIG_32)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_33;
  }
  get _EventManager_34():import18.EventManager {
    if ((this.__EventManager_34 == (null as any))) { (this.__EventManager_34 = new import18.EventManager(this._EVENT_MANAGER_PLUGINS_33,this.parent.get(import70.NgZone))); }
    return this.__EventManager_34;
  }
  get _DomSharedStylesHost_35():import19.DomSharedStylesHost {
    if ((this.__DomSharedStylesHost_35 == (null as any))) { (this.__DomSharedStylesHost_35 = new import19.DomSharedStylesHost(this._DOCUMENT_31)); }
    return this.__DomSharedStylesHost_35;
  }
  get _AnimationDriver_36():any {
    if ((this.__AnimationDriver_36 == (null as any))) { (this.__AnimationDriver_36 = import4._resolveDefaultAnimationDriver()); }
    return this.__AnimationDriver_36;
  }
  get _DomRootRenderer_37():import20.DomRootRenderer_ {
    if ((this.__DomRootRenderer_37 == (null as any))) { (this.__DomRootRenderer_37 = new import20.DomRootRenderer_(this._DOCUMENT_31,this._EventManager_34,this._DomSharedStylesHost_35,this._AnimationDriver_36)); }
    return this.__DomRootRenderer_37;
  }
  get _RootRenderer_38():any {
    if ((this.__RootRenderer_38 == (null as any))) { (this.__RootRenderer_38 = import71._createConditionalRootRenderer(this._DomRootRenderer_37,this.parent.get(import71.NgProbeToken,(null as any)))); }
    return this.__RootRenderer_38;
  }
  get _DomSanitizer_39():import21.DomSanitizerImpl {
    if ((this.__DomSanitizer_39 == (null as any))) { (this.__DomSanitizer_39 = new import21.DomSanitizerImpl()); }
    return this.__DomSanitizer_39;
  }
  get _Sanitizer_40():any {
    if ((this.__Sanitizer_40 == (null as any))) { (this.__Sanitizer_40 = this._DomSanitizer_39); }
    return this.__Sanitizer_40;
  }
  get _ViewUtils_41():import22.ViewUtils {
    if ((this.__ViewUtils_41 == (null as any))) { (this.__ViewUtils_41 = new import22.ViewUtils(this._RootRenderer_38,this._APP_ID_30,this._Sanitizer_40)); }
    return this.__ViewUtils_41;
  }
  get _IterableDiffers_42():any {
    if ((this.__IterableDiffers_42 == (null as any))) { (this.__IterableDiffers_42 = import3._iterableDiffersFactory()); }
    return this.__IterableDiffers_42;
  }
  get _KeyValueDiffers_43():any {
    if ((this.__KeyValueDiffers_43 == (null as any))) { (this.__KeyValueDiffers_43 = import3._keyValueDiffersFactory()); }
    return this.__KeyValueDiffers_43;
  }
  get _SharedStylesHost_44():any {
    if ((this.__SharedStylesHost_44 == (null as any))) { (this.__SharedStylesHost_44 = this._DomSharedStylesHost_35); }
    return this.__SharedStylesHost_44;
  }
  get _Title_45():import23.Title {
    if ((this.__Title_45 == (null as any))) { (this.__Title_45 = new import23.Title()); }
    return this.__Title_45;
  }
  get _BrowserXhr_46():import24.BrowserXhr {
    if ((this.__BrowserXhr_46 == (null as any))) { (this.__BrowserXhr_46 = new import24.BrowserXhr()); }
    return this.__BrowserXhr_46;
  }
  get _ResponseOptions_47():import25.BaseResponseOptions {
    if ((this.__ResponseOptions_47 == (null as any))) { (this.__ResponseOptions_47 = new import25.BaseResponseOptions()); }
    return this.__ResponseOptions_47;
  }
  get _XSRFStrategy_48():any {
    if ((this.__XSRFStrategy_48 == (null as any))) { (this.__XSRFStrategy_48 = import5._createDefaultCookieXSRFStrategy()); }
    return this.__XSRFStrategy_48;
  }
  get _XHRBackend_49():import26.XHRBackend {
    if ((this.__XHRBackend_49 == (null as any))) { (this.__XHRBackend_49 = new import26.XHRBackend(this._BrowserXhr_46,this._ResponseOptions_47,this._XSRFStrategy_48)); }
    return this.__XHRBackend_49;
  }
  get _RequestOptions_50():import27.BaseRequestOptions {
    if ((this.__RequestOptions_50 == (null as any))) { (this.__RequestOptions_50 = new import27.BaseRequestOptions()); }
    return this.__RequestOptions_50;
  }
  get _Http_51():any {
    if ((this.__Http_51 == (null as any))) { (this.__Http_51 = import5.httpFactory(this._XHRBackend_49,this._RequestOptions_50)); }
    return this.__Http_51;
  }
  get _RadioControlRegistry_52():import28.RadioControlRegistry {
    if ((this.__RadioControlRegistry_52 == (null as any))) { (this.__RadioControlRegistry_52 = new import28.RadioControlRegistry()); }
    return this.__RadioControlRegistry_52;
  }
  get _FormBuilder_53():import29.FormBuilder {
    if ((this.__FormBuilder_53 == (null as any))) { (this.__FormBuilder_53 = new import29.FormBuilder()); }
    return this.__FormBuilder_53;
  }
  get _AppRootToken_54():any {
    if ((this.__AppRootToken_54 == (null as any))) { (this.__AppRootToken_54 = import72.MyApp); }
    return this.__AppRootToken_54;
  }
  get _DeepLinkConfigToken_55():any {
    if ((this.__DeepLinkConfigToken_55 == (null as any))) { (this.__DeepLinkConfigToken_55 = (null as any)); }
    return this.__DeepLinkConfigToken_55;
  }
  get _ActionSheetController_56():import30.ActionSheetController {
    if ((this.__ActionSheetController_56 == (null as any))) { (this.__ActionSheetController_56 = new import30.ActionSheetController(this._App_23)); }
    return this.__ActionSheetController_56;
  }
  get _AlertController_57():import31.AlertController {
    if ((this.__AlertController_57 == (null as any))) { (this.__AlertController_57 = new import31.AlertController(this._App_23)); }
    return this.__AlertController_57;
  }
  get _Events_58():import32.Events {
    if ((this.__Events_58 == (null as any))) { (this.__Events_58 = new import32.Events()); }
    return this.__Events_58;
  }
  get _Form_59():import33.Form {
    if ((this.__Form_59 == (null as any))) { (this.__Form_59 = new import33.Form()); }
    return this.__Form_59;
  }
  get _Haptic_60():import34.Haptic {
    if ((this.__Haptic_60 == (null as any))) { (this.__Haptic_60 = new import34.Haptic(this._Platform_21)); }
    return this.__Haptic_60;
  }
  get _GestureController_61():import35.GestureController {
    if ((this.__GestureController_61 == (null as any))) { (this.__GestureController_61 = new import35.GestureController(this._App_23)); }
    return this.__GestureController_61;
  }
  get _Keyboard_62():import36.Keyboard {
    if ((this.__Keyboard_62 == (null as any))) { (this.__Keyboard_62 = new import36.Keyboard(this._Config_22,this._Form_59,this.parent.get(import70.NgZone))); }
    return this.__Keyboard_62;
  }
  get _LoadingController_63():import37.LoadingController {
    if ((this.__LoadingController_63 == (null as any))) { (this.__LoadingController_63 = new import37.LoadingController(this._App_23)); }
    return this.__LoadingController_63;
  }
  get _LocationStrategy_64():any {
    if ((this.__LocationStrategy_64 == (null as any))) { (this.__LocationStrategy_64 = import8.provideLocationStrategy(this.parent.get(import73.PlatformLocation),this.parent.get(import74.APP_BASE_HREF,(null as any)),this._Config_22)); }
    return this.__LocationStrategy_64;
  }
  get _Location_65():import38.Location {
    if ((this.__Location_65 == (null as any))) { (this.__Location_65 = new import38.Location(this._LocationStrategy_64)); }
    return this.__Location_65;
  }
  get _MenuController_66():import39.MenuController {
    if ((this.__MenuController_66 == (null as any))) { (this.__MenuController_66 = new import39.MenuController()); }
    return this.__MenuController_66;
  }
  get _ModalController_67():import40.ModalController {
    if ((this.__ModalController_67 == (null as any))) { (this.__ModalController_67 = new import40.ModalController(this._App_23)); }
    return this.__ModalController_67;
  }
  get _PickerController_68():import41.PickerController {
    if ((this.__PickerController_68 == (null as any))) { (this.__PickerController_68 = new import41.PickerController(this._App_23)); }
    return this.__PickerController_68;
  }
  get _PopoverController_69():import42.PopoverController {
    if ((this.__PopoverController_69 == (null as any))) { (this.__PopoverController_69 = new import42.PopoverController(this._App_23)); }
    return this.__PopoverController_69;
  }
  get _TapClick_70():import43.TapClick {
    if ((this.__TapClick_70 == (null as any))) { (this.__TapClick_70 = new import43.TapClick(this._Config_22,this._App_23,this.parent.get(import70.NgZone))); }
    return this.__TapClick_70;
  }
  get _ToastController_71():import44.ToastController {
    if ((this.__ToastController_71 == (null as any))) { (this.__ToastController_71 = new import44.ToastController(this._App_23)); }
    return this.__ToastController_71;
  }
  get _TransitionController_72():import45.TransitionController {
    if ((this.__TransitionController_72 == (null as any))) { (this.__TransitionController_72 = new import45.TransitionController(this._Config_22)); }
    return this.__TransitionController_72;
  }
  get _UrlSerializer_73():any {
    if ((this.__UrlSerializer_73 == (null as any))) { (this.__UrlSerializer_73 = import75.setupUrlSerializer(this._DeepLinkConfigToken_55)); }
    return this.__UrlSerializer_73;
  }
  get _DeepLinker_74():any {
    if ((this.__DeepLinker_74 == (null as any))) { (this.__DeepLinker_74 = import76.setupDeepLinker(this._App_23,this._UrlSerializer_73,this._Location_65)); }
    return this.__DeepLinker_74;
  }
  get _CloudSettingsToken_75():any {
    if ((this.__CloudSettingsToken_75 == (null as any))) { (this.__CloudSettingsToken_75 = {
      core: {app_id: 'e1187cb0'},
      push: {
        sender_id: '397348636938',
        pluginConfig: {
          ios: {
            alert: true,
            badge: true,
            sound: true
          }
          ,
          android: {iconColor: '#343434'}
        }

      }

    }
    ); }
    return this.__CloudSettingsToken_75;
  }
  get _DIContainer_76():any {
    if ((this.__DIContainer_76 == (null as any))) { (this.__DIContainer_76 = import9.provideContainer(this._CloudSettingsToken_75)); }
    return this.__DIContainer_76;
  }
  get _Auth_77():any {
    if ((this.__Auth_77 == (null as any))) { (this.__Auth_77 = import9.provideAuth(this._DIContainer_76)); }
    return this.__Auth_77;
  }
  get _Client_78():any {
    if ((this.__Client_78 == (null as any))) { (this.__Client_78 = import9.provideClient(this._DIContainer_76)); }
    return this.__Client_78;
  }
  get _Config_79():any {
    if ((this.__Config_79 == (null as any))) { (this.__Config_79 = import9.provideConfig(this._DIContainer_76)); }
    return this.__Config_79;
  }
  get _Database_80():any {
    if ((this.__Database_80 == (null as any))) { (this.__Database_80 = import9.provideDatabase(this._DIContainer_76)); }
    return this.__Database_80;
  }
  get _Deploy_81():any {
    if ((this.__Deploy_81 == (null as any))) { (this.__Deploy_81 = import9.provideDeploy(this._DIContainer_76)); }
    return this.__Deploy_81;
  }
  get _Push_82():any {
    if ((this.__Push_82 == (null as any))) { (this.__Push_82 = import9.providePush(this._DIContainer_76)); }
    return this.__Push_82;
  }
  get _User_83():any {
    if ((this.__User_83 == (null as any))) { (this.__User_83 = import9.provideUser(this._DIContainer_76)); }
    return this.__User_83;
  }
  get _FacebookAuth_84():any {
    if ((this.__FacebookAuth_84 == (null as any))) { (this.__FacebookAuth_84 = import9.provideFacebookAuth(this._DIContainer_76)); }
    return this.__FacebookAuth_84;
  }
  get _GoogleAuth_85():any {
    if ((this.__GoogleAuth_85 == (null as any))) { (this.__GoogleAuth_85 = import9.provideGoogleAuth(this._DIContainer_76)); }
    return this.__GoogleAuth_85;
  }
  createInternal():import1.AppModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ApplicationModule_1 = new import3.ApplicationModule();
    this._BrowserModule_2 = new import4.BrowserModule(this.parent.get(import4.BrowserModule,(null as any)));
    this._HttpModule_3 = new import5.HttpModule();
    this._InternalFormsSharedModule_4 = new import6.InternalFormsSharedModule();
    this._FormsModule_5 = new import7.FormsModule();
    this._ReactiveFormsModule_6 = new import7.ReactiveFormsModule();
    this._IonicModule_7 = new import8.IonicModule();
    this._CloudModule_8 = new import9.CloudModule();
    this._AppModule_9 = new import1.AppModule();
    this._ErrorHandler_12 = new import11.IonicErrorHandler();
    this._ConfigToken_13 = (null as any);
    this._UrlToken_14 = import8.provideLocationHref();
    this._QueryParams_15 = import77.setupQueryParams(this._UrlToken_14);
    this._PlatformConfigToken_16 = import78.providePlatformConfigs();
    this._UserAgentToken_17 = import8.provideUserAgent();
    this._NavigatorPlatformToken_18 = import8.provideNavigatorPlatform();
    this._DocumentDirToken_19 = import8.provideDocumentDirection();
    this._DocLangToken_20 = import8.provideDocumentLang();
    this._Platform_21 = import79.setupPlatform(this._PlatformConfigToken_16,this._QueryParams_15,this._UserAgentToken_17,this._NavigatorPlatformToken_18,this._DocumentDirToken_19,this._DocLangToken_20,this.parent.get(import70.NgZone));
    this._Config_22 = import80.setupConfig(this._ConfigToken_13,this._QueryParams_15,this._Platform_21);
    this._App_23 = new import12.App(this._Config_22,this._Platform_21);
    this._APP_INITIALIZER_24 = [
      import81.registerModeConfigs(this._Config_22),
      import82.registerTransitions(this._Config_22),
      import32.setupProvideEvents(this._Platform_21),
      import43.setupTapClick(this._Config_22,this._App_23,this.parent.get(import70.NgZone))
    ]
    ;
    this._ApplicationInitStatus_25 = new import13.ApplicationInitStatus(this._APP_INITIALIZER_24);
    this._Testability_26 = new import14.Testability(this.parent.get(import70.NgZone));
    this._ApplicationRef__27 = new import15.ApplicationRef_(this.parent.get(import70.NgZone),this.parent.get(import83.Console),this,this._ErrorHandler_12,this,this._ApplicationInitStatus_25,this.parent.get(import14.TestabilityRegistry,(null as any)),this._Testability_26);
    return this._AppModule_9;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import3.ApplicationModule)) { return this._ApplicationModule_1; }
    if ((token === import4.BrowserModule)) { return this._BrowserModule_2; }
    if ((token === import5.HttpModule)) { return this._HttpModule_3; }
    if ((token === import6.InternalFormsSharedModule)) { return this._InternalFormsSharedModule_4; }
    if ((token === import7.FormsModule)) { return this._FormsModule_5; }
    if ((token === import7.ReactiveFormsModule)) { return this._ReactiveFormsModule_6; }
    if ((token === import8.IonicModule)) { return this._IonicModule_7; }
    if ((token === import9.CloudModule)) { return this._CloudModule_8; }
    if ((token === import1.AppModule)) { return this._AppModule_9; }
    if ((token === import84.LOCALE_ID)) { return this._LOCALE_ID_10; }
    if ((token === import10.NgLocalization)) { return this._NgLocalization_11; }
    if ((token === import85.ErrorHandler)) { return this._ErrorHandler_12; }
    if ((token === import80.ConfigToken)) { return this._ConfigToken_13; }
    if ((token === import77.UrlToken)) { return this._UrlToken_14; }
    if ((token === import77.QueryParams)) { return this._QueryParams_15; }
    if ((token === import78.PlatformConfigToken)) { return this._PlatformConfigToken_16; }
    if ((token === import79.UserAgentToken)) { return this._UserAgentToken_17; }
    if ((token === import79.NavigatorPlatformToken)) { return this._NavigatorPlatformToken_18; }
    if ((token === import79.DocumentDirToken)) { return this._DocumentDirToken_19; }
    if ((token === import79.DocLangToken)) { return this._DocLangToken_20; }
    if ((token === import79.Platform)) { return this._Platform_21; }
    if ((token === import80.Config)) { return this._Config_22; }
    if ((token === import12.App)) { return this._App_23; }
    if ((token === import13.APP_INITIALIZER)) { return this._APP_INITIALIZER_24; }
    if ((token === import13.ApplicationInitStatus)) { return this._ApplicationInitStatus_25; }
    if ((token === import14.Testability)) { return this._Testability_26; }
    if ((token === import15.ApplicationRef_)) { return this._ApplicationRef__27; }
    if ((token === import15.ApplicationRef)) { return this._ApplicationRef_28; }
    if ((token === import16.Compiler)) { return this._Compiler_29; }
    if ((token === import66.APP_ID)) { return this._APP_ID_30; }
    if ((token === import86.DOCUMENT)) { return this._DOCUMENT_31; }
    if ((token === import69.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_32; }
    if ((token === import18.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_33; }
    if ((token === import18.EventManager)) { return this._EventManager_34; }
    if ((token === import19.DomSharedStylesHost)) { return this._DomSharedStylesHost_35; }
    if ((token === import87.AnimationDriver)) { return this._AnimationDriver_36; }
    if ((token === import20.DomRootRenderer)) { return this._DomRootRenderer_37; }
    if ((token === import88.RootRenderer)) { return this._RootRenderer_38; }
    if ((token === import21.DomSanitizer)) { return this._DomSanitizer_39; }
    if ((token === import89.Sanitizer)) { return this._Sanitizer_40; }
    if ((token === import22.ViewUtils)) { return this._ViewUtils_41; }
    if ((token === import90.IterableDiffers)) { return this._IterableDiffers_42; }
    if ((token === import91.KeyValueDiffers)) { return this._KeyValueDiffers_43; }
    if ((token === import19.SharedStylesHost)) { return this._SharedStylesHost_44; }
    if ((token === import23.Title)) { return this._Title_45; }
    if ((token === import24.BrowserXhr)) { return this._BrowserXhr_46; }
    if ((token === import25.ResponseOptions)) { return this._ResponseOptions_47; }
    if ((token === import92.XSRFStrategy)) { return this._XSRFStrategy_48; }
    if ((token === import26.XHRBackend)) { return this._XHRBackend_49; }
    if ((token === import27.RequestOptions)) { return this._RequestOptions_50; }
    if ((token === import93.Http)) { return this._Http_51; }
    if ((token === import28.RadioControlRegistry)) { return this._RadioControlRegistry_52; }
    if ((token === import29.FormBuilder)) { return this._FormBuilder_53; }
    if ((token === import94.AppRootToken)) { return this._AppRootToken_54; }
    if ((token === import75.DeepLinkConfigToken)) { return this._DeepLinkConfigToken_55; }
    if ((token === import30.ActionSheetController)) { return this._ActionSheetController_56; }
    if ((token === import31.AlertController)) { return this._AlertController_57; }
    if ((token === import32.Events)) { return this._Events_58; }
    if ((token === import33.Form)) { return this._Form_59; }
    if ((token === import34.Haptic)) { return this._Haptic_60; }
    if ((token === import35.GestureController)) { return this._GestureController_61; }
    if ((token === import36.Keyboard)) { return this._Keyboard_62; }
    if ((token === import37.LoadingController)) { return this._LoadingController_63; }
    if ((token === import74.LocationStrategy)) { return this._LocationStrategy_64; }
    if ((token === import38.Location)) { return this._Location_65; }
    if ((token === import39.MenuController)) { return this._MenuController_66; }
    if ((token === import40.ModalController)) { return this._ModalController_67; }
    if ((token === import41.PickerController)) { return this._PickerController_68; }
    if ((token === import42.PopoverController)) { return this._PopoverController_69; }
    if ((token === import43.TapClick)) { return this._TapClick_70; }
    if ((token === import44.ToastController)) { return this._ToastController_71; }
    if ((token === import45.TransitionController)) { return this._TransitionController_72; }
    if ((token === import75.UrlSerializer)) { return this._UrlSerializer_73; }
    if ((token === import76.DeepLinker)) { return this._DeepLinker_74; }
    if ((token === import9.CloudSettingsToken)) { return this._CloudSettingsToken_75; }
    if ((token === import9.DIContainer)) { return this._DIContainer_76; }
    if ((token === import9.Auth)) { return this._Auth_77; }
    if ((token === import9.Client)) { return this._Client_78; }
    if ((token === import9.Config)) { return this._Config_79; }
    if ((token === import9.Database)) { return this._Database_80; }
    if ((token === import9.Deploy)) { return this._Deploy_81; }
    if ((token === import9.Push)) { return this._Push_82; }
    if ((token === import9.User)) { return this._User_83; }
    if ((token === import9.FacebookAuth)) { return this._FacebookAuth_84; }
    if ((token === import9.GoogleAuth)) { return this._GoogleAuth_85; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ApplicationRef__27.ngOnDestroy();
  }
}
export const AppModuleNgFactory:import0.NgModuleFactory<import1.AppModule> = new import0.NgModuleFactory(AppModuleInjector,import1.AppModule);