/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './signup';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/http/src/http';
import * as import10 from 'ionic-angular/components/alert/alert';
import * as import11 from 'ionic-angular/components/loading/loading';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import21 from '@angular/core/src/linker/query_list';
import * as import22 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import23 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import25 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import26 from 'ionic-angular/config/config';
import * as import27 from '@angular/core/src/linker/element_ref';
import * as import28 from 'ionic-angular/navigation/view-controller';
import * as import29 from 'ionic-angular/components/app/app';
import * as import30 from 'ionic-angular/components/toolbar/toolbar';
import * as import31 from 'ionic-angular/util/keyboard';
import * as import32 from '@angular/core/src/zone/ng_zone';
import * as import33 from 'ionic-angular/components/tabs/tabs';
import * as import34 from 'ionic-angular/util/form';
import * as import35 from 'ionic-angular/components/item/item-reorder';
import * as import36 from 'ionic-angular/platform/platform';
import * as import37 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import38 from 'ionic-angular/components/navbar/navbar';
import * as import39 from 'ionic-angular/components/icon/icon';
import * as import40 from '@angular/forms/src/directives/ng_model';
import * as import41 from '@angular/forms/src/directives/ng_control';
import * as import42 from '@angular/forms/src/directives/ng_control_status';
import * as import43 from 'ionic-angular/components/input/input';
import * as import44 from 'ionic-angular/components/item/item';
import * as import45 from 'ionic-angular/components/card/card';
import * as import46 from 'ionic-angular/components/button/button';
import * as import47 from 'ionic-angular/components/content/content';
export class Wrapper_SignupPage {
  context:import0.SignupPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this.changed = false;
    this.context = new import0.SignupPage(p0,p1,p2,p3);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_SignupPage_Host:import2.RenderComponentType = (null as any);
class _View_SignupPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _SignupPage_0_4:Wrapper_SignupPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SignupPage_Host0,renderType_SignupPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-signup',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SignupPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SignupPage_0_4 = new Wrapper_SignupPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.Http),this.parentInjector.get(import10.AlertController),this.parentInjector.get(import11.LoadingController));
    this._appEl_0.initComponent(this._SignupPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._SignupPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SignupPage) && (0 === requestNodeIndex))) { return this._SignupPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SignupPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SignupPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_SignupPage_Host === (null as any))) { (renderType_SignupPage_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_SignupPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const SignupPageNgFactory:import13.ComponentFactory<import0.SignupPage> = new import13.ComponentFactory<import0.SignupPage>('page-signup',viewFactory_SignupPage_Host0,import0.SignupPage);
const styles_SignupPage:any[] = ([] as any[]);
var renderType_SignupPage:import2.RenderComponentType = (null as any);
class _View_SignupPage0 extends import1.AppView<import0.SignupPage> {
  _el_0:any;
  _Header_0_3:import14.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import15.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import16.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import17.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _text_13:any;
  _el_14:any;
  _Card_14_3:import18.Wrapper_Card;
  _text_15:any;
  _el_16:any;
  _CardContent_16_3:import18.Wrapper_CardContent;
  _text_17:any;
  _el_18:any;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _Icon_22_3:import19.Wrapper_Icon;
  _text_23:any;
  _el_24:any;
  /*private*/ _appEl_24:import3.AppElement;
  _Item_24_4:import20.Wrapper_Item;
  _ItemContent_24_5:import20.Wrapper_ItemContent;
  _query_Label_24_0:import21.QueryList<any>;
  _query_Button_24_1:import21.QueryList<any>;
  _query_Icon_24_2:import21.QueryList<any>;
  _text_25:any;
  _el_26:any;
  /*private*/ _appEl_26:import3.AppElement;
  _NgModel_26_4:import22.Wrapper_NgModel;
  _NgControl_26_5:any;
  _NgControlStatus_26_6:import23.Wrapper_NgControlStatus;
  _TextInput_26_7:import24.Wrapper_TextInput;
  _text_27:any;
  _text_28:any;
  _text_29:any;
  _text_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _Card_33_3:import18.Wrapper_Card;
  _text_34:any;
  _el_35:any;
  _CardContent_35_3:import18.Wrapper_CardContent;
  _text_36:any;
  _el_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _el_41:any;
  _Icon_41_3:import19.Wrapper_Icon;
  _text_42:any;
  _el_43:any;
  /*private*/ _appEl_43:import3.AppElement;
  _Item_43_4:import20.Wrapper_Item;
  _ItemContent_43_5:import20.Wrapper_ItemContent;
  _query_Label_43_0:import21.QueryList<any>;
  _query_Button_43_1:import21.QueryList<any>;
  _query_Icon_43_2:import21.QueryList<any>;
  _text_44:any;
  _el_45:any;
  /*private*/ _appEl_45:import3.AppElement;
  _NgModel_45_4:import22.Wrapper_NgModel;
  _NgControl_45_5:any;
  _NgControlStatus_45_6:import23.Wrapper_NgControlStatus;
  _TextInput_45_7:import24.Wrapper_TextInput;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _el_52:any;
  _Card_52_3:import18.Wrapper_Card;
  _text_53:any;
  _el_54:any;
  _CardContent_54_3:import18.Wrapper_CardContent;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _el_58:any;
  _text_59:any;
  _el_60:any;
  _Icon_60_3:import19.Wrapper_Icon;
  _text_61:any;
  _el_62:any;
  /*private*/ _appEl_62:import3.AppElement;
  _Item_62_4:import20.Wrapper_Item;
  _ItemContent_62_5:import20.Wrapper_ItemContent;
  _query_Label_62_0:import21.QueryList<any>;
  _query_Button_62_1:import21.QueryList<any>;
  _query_Icon_62_2:import21.QueryList<any>;
  _text_63:any;
  _el_64:any;
  /*private*/ _appEl_64:import3.AppElement;
  _NgModel_64_4:import22.Wrapper_NgModel;
  _NgControl_64_5:any;
  _NgControlStatus_64_6:import23.Wrapper_NgControlStatus;
  _TextInput_64_7:import24.Wrapper_TextInput;
  _text_65:any;
  _text_66:any;
  _text_67:any;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _Card_71_3:import18.Wrapper_Card;
  _text_72:any;
  _el_73:any;
  _CardContent_73_3:import18.Wrapper_CardContent;
  _text_74:any;
  _el_75:any;
  _text_76:any;
  _el_77:any;
  _text_78:any;
  _el_79:any;
  _Icon_79_3:import19.Wrapper_Icon;
  _text_80:any;
  _el_81:any;
  /*private*/ _appEl_81:import3.AppElement;
  _Item_81_4:import20.Wrapper_Item;
  _ItemContent_81_5:import20.Wrapper_ItemContent;
  _query_Label_81_0:import21.QueryList<any>;
  _query_Button_81_1:import21.QueryList<any>;
  _query_Icon_81_2:import21.QueryList<any>;
  _text_82:any;
  _el_83:any;
  /*private*/ _appEl_83:import3.AppElement;
  _NgModel_83_4:import22.Wrapper_NgModel;
  _NgControl_83_5:any;
  _NgControlStatus_83_6:import23.Wrapper_NgControlStatus;
  _TextInput_83_7:import24.Wrapper_TextInput;
  _text_84:any;
  _text_85:any;
  _text_86:any;
  _text_87:any;
  _text_88:any;
  _text_89:any;
  _el_90:any;
  _text_91:any;
  _el_92:any;
  /*private*/ _appEl_92:import3.AppElement;
  _Button_92_4:import25.Wrapper_Button;
  _text_93:any;
  _text_94:any;
  _text_95:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_12:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_31:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_33:any;
  /*private*/ _expr_34:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_43:any;
  /*private*/ _expr_44:any;
  /*private*/ _expr_45:any;
  /*private*/ _expr_46:any;
  /*private*/ _expr_47:any;
  /*private*/ _expr_48:any;
  /*private*/ _expr_52:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SignupPage0,renderType_SignupPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import14.Wrapper_Header(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import28.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import15.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import15.Wrapper_Navbar(this.parentInjector.get(import29.App),this.parentInjector.get(import28.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import16.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import16.Wrapper_ToolbarTitle(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import30.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'SIGN UP',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'padding','');
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import17.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import17.Wrapper_Content(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import29.App),this.parentInjector.get(import31.Keyboard),this.parentInjector.get(import32.NgZone),this.parentInjector.get(import28.ViewController,(null as any)),this.parentInjector.get(import33.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'h5',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','light-gray-color');
    this.renderer.setElementAttribute(this._el_11,'text-center','');
    this._text_12 = this.renderer.createText(this._el_11,'Please fill up details below',(null as any));
    this._text_13 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_14 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_14_3 = new import18.Wrapper_Card(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_14),this.renderer);
    this._text_15 = this.renderer.createText(this._el_14,'\n        ',(null as any));
    this._el_16 = this.renderer.createElement(this._el_14,'ion-card-content',(null as any));
    this.renderer.setElementAttribute(this._el_16,'class','field-with-icon');
    this._CardContent_16_3 = new import18.Wrapper_CardContent(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_16),this.renderer);
    this._text_17 = this.renderer.createText(this._el_16,'\n            ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'div',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','row');
    this._text_19 = this.renderer.createText(this._el_18,'\n              ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'div',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','col border-bottom');
    this._text_21 = this.renderer.createText(this._el_20,'\n                ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','medium');
    this.renderer.setElementAttribute(this._el_22,'name','ios-person-outline');
    this.renderer.setElementAttribute(this._el_22,'role','img');
    this._Icon_22_3 = new import19.Wrapper_Icon(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_22),this.renderer);
    this._text_23 = this.renderer.createText(this._el_20,'\n                ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_20,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','item item-block');
    this._appEl_24 = new import3.AppElement(24,20,this,this._el_24);
    var compView_24:any = import20.viewFactory_Item0(this.viewUtils,this.injector(24),this._appEl_24);
    this._Item_24_4 = new import20.Wrapper_Item(this.parentInjector.get(import34.Form),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_24),this.renderer,this.parentInjector.get(import35.ItemReorder,(null as any)));
    this._ItemContent_24_5 = new import20.Wrapper_ItemContent();
    this._query_Label_24_0 = new import21.QueryList<any>();
    this._query_Button_24_1 = new import21.QueryList<any>();
    this._query_Icon_24_2 = new import21.QueryList<any>();
    this._appEl_24.initComponent(this._Item_24_4.context,([] as any[]),compView_24);
    this._text_25 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._el_26 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_26,'placeholder','Name');
    this.renderer.setElementAttribute(this._el_26,'type','text');
    this._appEl_26 = new import3.AppElement(26,24,this,this._el_26);
    var compView_26:any = import24.viewFactory_TextInput0(this.viewUtils,this.injector(26),this._appEl_26);
    this._NgModel_26_4 = new import22.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_26_5 = this._NgModel_26_4.context;
    this._NgControlStatus_26_6 = new import23.Wrapper_NgControlStatus(this._NgControl_26_5);
    this._TextInput_26_7 = new import24.Wrapper_TextInput(this.parentInjector.get(import26.Config),this.parentInjector.get(import34.Form),this._Item_24_4.context,this.parentInjector.get(import29.App),this.parentInjector.get(import36.Platform),new import27.ElementRef(this._el_26),this.renderer,this._Content_9_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_26_5);
    this._appEl_26.initComponent(this._TextInput_26_7.context,([] as any[]),compView_26);
    compView_26.create(this._TextInput_26_7.context,([] as any[]),(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._query_Label_24_0.reset(([] as any[]));
    this._Item_24_4.context.contentLabel = this._query_Label_24_0.first;
    compView_24.create(this._Item_24_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_25,
        this._text_27
      ]
      ),
      ([] as any[]).concat([this._el_26]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_28 = this.renderer.createText(this._el_20,'\n              ',(null as any));
    this._text_29 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._text_30 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._text_31 = this.renderer.createText(this._el_14,'\n    ',(null as any));
    this._text_32 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_33 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_33_3 = new import18.Wrapper_Card(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_33),this.renderer);
    this._text_34 = this.renderer.createText(this._el_33,'\n        ',(null as any));
    this._el_35 = this.renderer.createElement(this._el_33,'ion-card-content',(null as any));
    this.renderer.setElementAttribute(this._el_35,'class','field-with-icon');
    this._CardContent_35_3 = new import18.Wrapper_CardContent(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_35),this.renderer);
    this._text_36 = this.renderer.createText(this._el_35,'\n          ',(null as any));
    this._el_37 = this.renderer.createElement(this._el_35,'div',(null as any));
    this.renderer.setElementAttribute(this._el_37,'class','row');
    this._text_38 = this.renderer.createText(this._el_37,'\n            ',(null as any));
    this._el_39 = this.renderer.createElement(this._el_37,'div',(null as any));
    this.renderer.setElementAttribute(this._el_39,'class','col border-bottom');
    this._text_40 = this.renderer.createText(this._el_39,'\n              ',(null as any));
    this._el_41 = this.renderer.createElement(this._el_39,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_41,'class','medium');
    this.renderer.setElementAttribute(this._el_41,'name','ios-mail-outline');
    this.renderer.setElementAttribute(this._el_41,'role','img');
    this._Icon_41_3 = new import19.Wrapper_Icon(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_41),this.renderer);
    this._text_42 = this.renderer.createText(this._el_39,'\n              ',(null as any));
    this._el_43 = this.renderer.createElement(this._el_39,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_43,'class','item item-block');
    this._appEl_43 = new import3.AppElement(43,39,this,this._el_43);
    var compView_43:any = import20.viewFactory_Item0(this.viewUtils,this.injector(43),this._appEl_43);
    this._Item_43_4 = new import20.Wrapper_Item(this.parentInjector.get(import34.Form),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_43),this.renderer,this.parentInjector.get(import35.ItemReorder,(null as any)));
    this._ItemContent_43_5 = new import20.Wrapper_ItemContent();
    this._query_Label_43_0 = new import21.QueryList<any>();
    this._query_Button_43_1 = new import21.QueryList<any>();
    this._query_Icon_43_2 = new import21.QueryList<any>();
    this._appEl_43.initComponent(this._Item_43_4.context,([] as any[]),compView_43);
    this._text_44 = this.renderer.createText((null as any),'\n                  ',(null as any));
    this._el_45 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_45,'placeholder','Email Address');
    this.renderer.setElementAttribute(this._el_45,'type','email');
    this._appEl_45 = new import3.AppElement(45,43,this,this._el_45);
    var compView_45:any = import24.viewFactory_TextInput0(this.viewUtils,this.injector(45),this._appEl_45);
    this._NgModel_45_4 = new import22.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_45_5 = this._NgModel_45_4.context;
    this._NgControlStatus_45_6 = new import23.Wrapper_NgControlStatus(this._NgControl_45_5);
    this._TextInput_45_7 = new import24.Wrapper_TextInput(this.parentInjector.get(import26.Config),this.parentInjector.get(import34.Form),this._Item_43_4.context,this.parentInjector.get(import29.App),this.parentInjector.get(import36.Platform),new import27.ElementRef(this._el_45),this.renderer,this._Content_9_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_45_5);
    this._appEl_45.initComponent(this._TextInput_45_7.context,([] as any[]),compView_45);
    compView_45.create(this._TextInput_45_7.context,([] as any[]),(null as any));
    this._text_46 = this.renderer.createText((null as any),'\n              ',(null as any));
    this._query_Label_43_0.reset(([] as any[]));
    this._Item_43_4.context.contentLabel = this._query_Label_43_0.first;
    compView_43.create(this._Item_43_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_44,
        this._text_46
      ]
      ),
      ([] as any[]).concat([this._el_45]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_47 = this.renderer.createText(this._el_39,'\n            ',(null as any));
    this._text_48 = this.renderer.createText(this._el_37,'\n          ',(null as any));
    this._text_49 = this.renderer.createText(this._el_35,'\n        ',(null as any));
    this._text_50 = this.renderer.createText(this._el_33,'\n    ',(null as any));
    this._text_51 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_52 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_52_3 = new import18.Wrapper_Card(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_52),this.renderer);
    this._text_53 = this.renderer.createText(this._el_52,'\n        ',(null as any));
    this._el_54 = this.renderer.createElement(this._el_52,'ion-card-content',(null as any));
    this.renderer.setElementAttribute(this._el_54,'class','field-with-icon');
    this._CardContent_54_3 = new import18.Wrapper_CardContent(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_54),this.renderer);
    this._text_55 = this.renderer.createText(this._el_54,'\n            ',(null as any));
    this._el_56 = this.renderer.createElement(this._el_54,'div',(null as any));
    this.renderer.setElementAttribute(this._el_56,'class','row');
    this._text_57 = this.renderer.createText(this._el_56,'\n              ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_56,'div',(null as any));
    this.renderer.setElementAttribute(this._el_58,'class','col');
    this._text_59 = this.renderer.createText(this._el_58,'\n                ',(null as any));
    this._el_60 = this.renderer.createElement(this._el_58,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_60,'class','medium');
    this.renderer.setElementAttribute(this._el_60,'name','ios-unlock-outline');
    this.renderer.setElementAttribute(this._el_60,'role','img');
    this._Icon_60_3 = new import19.Wrapper_Icon(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_60),this.renderer);
    this._text_61 = this.renderer.createText(this._el_58,'\n                ',(null as any));
    this._el_62 = this.renderer.createElement(this._el_58,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_62,'class','item item-block');
    this._appEl_62 = new import3.AppElement(62,58,this,this._el_62);
    var compView_62:any = import20.viewFactory_Item0(this.viewUtils,this.injector(62),this._appEl_62);
    this._Item_62_4 = new import20.Wrapper_Item(this.parentInjector.get(import34.Form),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_62),this.renderer,this.parentInjector.get(import35.ItemReorder,(null as any)));
    this._ItemContent_62_5 = new import20.Wrapper_ItemContent();
    this._query_Label_62_0 = new import21.QueryList<any>();
    this._query_Button_62_1 = new import21.QueryList<any>();
    this._query_Icon_62_2 = new import21.QueryList<any>();
    this._appEl_62.initComponent(this._Item_62_4.context,([] as any[]),compView_62);
    this._text_63 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._el_64 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_64,'placeholder','Password');
    this.renderer.setElementAttribute(this._el_64,'type','password');
    this._appEl_64 = new import3.AppElement(64,62,this,this._el_64);
    var compView_64:any = import24.viewFactory_TextInput0(this.viewUtils,this.injector(64),this._appEl_64);
    this._NgModel_64_4 = new import22.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_64_5 = this._NgModel_64_4.context;
    this._NgControlStatus_64_6 = new import23.Wrapper_NgControlStatus(this._NgControl_64_5);
    this._TextInput_64_7 = new import24.Wrapper_TextInput(this.parentInjector.get(import26.Config),this.parentInjector.get(import34.Form),this._Item_62_4.context,this.parentInjector.get(import29.App),this.parentInjector.get(import36.Platform),new import27.ElementRef(this._el_64),this.renderer,this._Content_9_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_64_5);
    this._appEl_64.initComponent(this._TextInput_64_7.context,([] as any[]),compView_64);
    compView_64.create(this._TextInput_64_7.context,([] as any[]),(null as any));
    this._text_65 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._query_Label_62_0.reset(([] as any[]));
    this._Item_62_4.context.contentLabel = this._query_Label_62_0.first;
    compView_62.create(this._Item_62_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_63,
        this._text_65
      ]
      ),
      ([] as any[]).concat([this._el_64]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_66 = this.renderer.createText(this._el_58,'\n              ',(null as any));
    this._text_67 = this.renderer.createText(this._el_56,'\n            ',(null as any));
    this._text_68 = this.renderer.createText(this._el_54,'\n        ',(null as any));
    this._text_69 = this.renderer.createText(this._el_52,'\n    ',(null as any));
    this._text_70 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_71 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this.renderer.setElementAttribute(this._el_71,'class','mg-bt-20');
    this._Card_71_3 = new import18.Wrapper_Card(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_71),this.renderer);
    this._text_72 = this.renderer.createText(this._el_71,'\n        ',(null as any));
    this._el_73 = this.renderer.createElement(this._el_71,'ion-card-content',(null as any));
    this.renderer.setElementAttribute(this._el_73,'class','field-with-icon');
    this._CardContent_73_3 = new import18.Wrapper_CardContent(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_73),this.renderer);
    this._text_74 = this.renderer.createText(this._el_73,'\n            ',(null as any));
    this._el_75 = this.renderer.createElement(this._el_73,'div',(null as any));
    this.renderer.setElementAttribute(this._el_75,'class','row');
    this._text_76 = this.renderer.createText(this._el_75,'\n              ',(null as any));
    this._el_77 = this.renderer.createElement(this._el_75,'div',(null as any));
    this.renderer.setElementAttribute(this._el_77,'class','col');
    this._text_78 = this.renderer.createText(this._el_77,'\n                ',(null as any));
    this._el_79 = this.renderer.createElement(this._el_77,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_79,'class','medium');
    this.renderer.setElementAttribute(this._el_79,'name','ios-unlock-outline');
    this.renderer.setElementAttribute(this._el_79,'role','img');
    this._Icon_79_3 = new import19.Wrapper_Icon(this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_79),this.renderer);
    this._text_80 = this.renderer.createText(this._el_77,'\n                ',(null as any));
    this._el_81 = this.renderer.createElement(this._el_77,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_81,'class','item item-block');
    this._appEl_81 = new import3.AppElement(81,77,this,this._el_81);
    var compView_81:any = import20.viewFactory_Item0(this.viewUtils,this.injector(81),this._appEl_81);
    this._Item_81_4 = new import20.Wrapper_Item(this.parentInjector.get(import34.Form),this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_81),this.renderer,this.parentInjector.get(import35.ItemReorder,(null as any)));
    this._ItemContent_81_5 = new import20.Wrapper_ItemContent();
    this._query_Label_81_0 = new import21.QueryList<any>();
    this._query_Button_81_1 = new import21.QueryList<any>();
    this._query_Icon_81_2 = new import21.QueryList<any>();
    this._appEl_81.initComponent(this._Item_81_4.context,([] as any[]),compView_81);
    this._text_82 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._el_83 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_83,'placeholder','Re-password');
    this.renderer.setElementAttribute(this._el_83,'type','password');
    this._appEl_83 = new import3.AppElement(83,81,this,this._el_83);
    var compView_83:any = import24.viewFactory_TextInput0(this.viewUtils,this.injector(83),this._appEl_83);
    this._NgModel_83_4 = new import22.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_83_5 = this._NgModel_83_4.context;
    this._NgControlStatus_83_6 = new import23.Wrapper_NgControlStatus(this._NgControl_83_5);
    this._TextInput_83_7 = new import24.Wrapper_TextInput(this.parentInjector.get(import26.Config),this.parentInjector.get(import34.Form),this._Item_81_4.context,this.parentInjector.get(import29.App),this.parentInjector.get(import36.Platform),new import27.ElementRef(this._el_83),this.renderer,this._Content_9_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_83_5);
    this._appEl_83.initComponent(this._TextInput_83_7.context,([] as any[]),compView_83);
    compView_83.create(this._TextInput_83_7.context,([] as any[]),(null as any));
    this._text_84 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._query_Label_81_0.reset(([] as any[]));
    this._Item_81_4.context.contentLabel = this._query_Label_81_0.first;
    compView_81.create(this._Item_81_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_82,
        this._text_84
      ]
      ),
      ([] as any[]).concat([this._el_83]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_85 = this.renderer.createText(this._el_77,'\n              ',(null as any));
    this._text_86 = this.renderer.createText(this._el_75,'\n            ',(null as any));
    this._text_87 = this.renderer.createText(this._el_73,'\n        ',(null as any));
    this._text_88 = this.renderer.createText(this._el_71,'\n    ',(null as any));
    this._text_89 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_90 = this.renderer.createElement((null as any),'br',(null as any));
    this._text_91 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_92 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_92,'block','');
    this.renderer.setElementAttribute(this._el_92,'class','primary-btn');
    this.renderer.setElementAttribute(this._el_92,'ion-button','');
    this._appEl_92 = new import3.AppElement(92,9,this,this._el_92);
    var compView_92:any = import25.viewFactory_Button0(this.viewUtils,this.injector(92),this._appEl_92);
    this._Button_92_4 = new import25.Wrapper_Button((null as any),'',this.parentInjector.get(import26.Config),new import27.ElementRef(this._el_92),this.renderer);
    this._appEl_92.initComponent(this._Button_92_4.context,([] as any[]),compView_92);
    this._text_93 = this.renderer.createText((null as any),'Sign up',(null as any));
    compView_92.create(this._Button_92_4.context,[([] as any[]).concat([this._text_93])],(null as any));
    this._text_94 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_13,
        this._el_14,
        this._text_32,
        this._el_33,
        this._text_51,
        this._el_52,
        this._text_70,
        this._el_71,
        this._text_89,
        this._el_90,
        this._text_91,
        this._el_92,
        this._text_94
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_95 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this._expr_4 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_26,'ngModelChange',this.eventHandler(this._handle_ngModelChange_26_0.bind(this)));
    const subscription_0:any = this._NgModel_26_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_26_0.bind(this)));
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    this._expr_11 = import7.UNINITIALIZED;
    this._expr_12 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_45,'ngModelChange',this.eventHandler(this._handle_ngModelChange_45_0.bind(this)));
    const subscription_1:any = this._NgModel_45_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_45_0.bind(this)));
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    this._expr_21 = import7.UNINITIALIZED;
    this._expr_22 = import7.UNINITIALIZED;
    this._expr_23 = import7.UNINITIALIZED;
    this._expr_24 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_64,'ngModelChange',this.eventHandler(this._handle_ngModelChange_64_0.bind(this)));
    const subscription_2:any = this._NgModel_64_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_64_0.bind(this)));
    this._expr_31 = import7.UNINITIALIZED;
    this._expr_32 = import7.UNINITIALIZED;
    this._expr_33 = import7.UNINITIALIZED;
    this._expr_34 = import7.UNINITIALIZED;
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_83,'ngModelChange',this.eventHandler(this._handle_ngModelChange_83_0.bind(this)));
    const subscription_3:any = this._NgModel_83_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_83_0.bind(this)));
    this._expr_43 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    this._expr_45 = import7.UNINITIALIZED;
    this._expr_46 = import7.UNINITIALIZED;
    this._expr_47 = import7.UNINITIALIZED;
    this._expr_48 = import7.UNINITIALIZED;
    this._expr_52 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_92,'click',this.eventHandler(this._handle_click_92_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._text_13,
      this._el_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._el_26,
      this._text_27,
      this._text_28,
      this._text_29,
      this._text_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._el_35,
      this._text_36,
      this._el_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._el_41,
      this._text_42,
      this._el_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._el_52,
      this._text_53,
      this._el_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._el_64,
      this._text_65,
      this._text_66,
      this._text_67,
      this._text_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._text_85,
      this._text_86,
      this._text_87,
      this._text_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._text_94,
      this._text_95
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import37.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import38.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import30.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import39.Icon) && (22 === requestNodeIndex))) { return this._Icon_22_3.context; }
    if (((token === import40.NgModel) && (26 === requestNodeIndex))) { return this._NgModel_26_4.context; }
    if (((token === import41.NgControl) && (26 === requestNodeIndex))) { return this._NgControl_26_5; }
    if (((token === import42.NgControlStatus) && (26 === requestNodeIndex))) { return this._NgControlStatus_26_6.context; }
    if (((token === import43.TextInput) && (26 === requestNodeIndex))) { return this._TextInput_26_7.context; }
    if (((token === import44.Item) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._Item_24_4.context; }
    if (((token === import44.ItemContent) && ((24 <= requestNodeIndex) && (requestNodeIndex <= 27)))) { return this._ItemContent_24_5.context; }
    if (((token === import45.CardContent) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 30)))) { return this._CardContent_16_3.context; }
    if (((token === import45.Card) && ((14 <= requestNodeIndex) && (requestNodeIndex <= 31)))) { return this._Card_14_3.context; }
    if (((token === import39.Icon) && (41 === requestNodeIndex))) { return this._Icon_41_3.context; }
    if (((token === import40.NgModel) && (45 === requestNodeIndex))) { return this._NgModel_45_4.context; }
    if (((token === import41.NgControl) && (45 === requestNodeIndex))) { return this._NgControl_45_5; }
    if (((token === import42.NgControlStatus) && (45 === requestNodeIndex))) { return this._NgControlStatus_45_6.context; }
    if (((token === import43.TextInput) && (45 === requestNodeIndex))) { return this._TextInput_45_7.context; }
    if (((token === import44.Item) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._Item_43_4.context; }
    if (((token === import44.ItemContent) && ((43 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._ItemContent_43_5.context; }
    if (((token === import45.CardContent) && ((35 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._CardContent_35_3.context; }
    if (((token === import45.Card) && ((33 <= requestNodeIndex) && (requestNodeIndex <= 50)))) { return this._Card_33_3.context; }
    if (((token === import39.Icon) && (60 === requestNodeIndex))) { return this._Icon_60_3.context; }
    if (((token === import40.NgModel) && (64 === requestNodeIndex))) { return this._NgModel_64_4.context; }
    if (((token === import41.NgControl) && (64 === requestNodeIndex))) { return this._NgControl_64_5; }
    if (((token === import42.NgControlStatus) && (64 === requestNodeIndex))) { return this._NgControlStatus_64_6.context; }
    if (((token === import43.TextInput) && (64 === requestNodeIndex))) { return this._TextInput_64_7.context; }
    if (((token === import44.Item) && ((62 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._Item_62_4.context; }
    if (((token === import44.ItemContent) && ((62 <= requestNodeIndex) && (requestNodeIndex <= 65)))) { return this._ItemContent_62_5.context; }
    if (((token === import45.CardContent) && ((54 <= requestNodeIndex) && (requestNodeIndex <= 68)))) { return this._CardContent_54_3.context; }
    if (((token === import45.Card) && ((52 <= requestNodeIndex) && (requestNodeIndex <= 69)))) { return this._Card_52_3.context; }
    if (((token === import39.Icon) && (79 === requestNodeIndex))) { return this._Icon_79_3.context; }
    if (((token === import40.NgModel) && (83 === requestNodeIndex))) { return this._NgModel_83_4.context; }
    if (((token === import41.NgControl) && (83 === requestNodeIndex))) { return this._NgControl_83_5; }
    if (((token === import42.NgControlStatus) && (83 === requestNodeIndex))) { return this._NgControlStatus_83_6.context; }
    if (((token === import43.TextInput) && (83 === requestNodeIndex))) { return this._TextInput_83_7.context; }
    if (((token === import44.Item) && ((81 <= requestNodeIndex) && (requestNodeIndex <= 84)))) { return this._Item_81_4.context; }
    if (((token === import44.ItemContent) && ((81 <= requestNodeIndex) && (requestNodeIndex <= 84)))) { return this._ItemContent_81_5.context; }
    if (((token === import45.CardContent) && ((73 <= requestNodeIndex) && (requestNodeIndex <= 87)))) { return this._CardContent_73_3.context; }
    if (((token === import45.Card) && ((71 <= requestNodeIndex) && (requestNodeIndex <= 88)))) { return this._Card_71_3.context; }
    if (((token === import46.Button) && ((92 <= requestNodeIndex) && (requestNodeIndex <= 93)))) { return this._Button_92_4.context; }
    if (((token === import47.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 94)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    this._Card_14_3.detectChangesInternal(this,this._el_14,throwOnChange);
    this._CardContent_16_3.detectChangesInternal(this,this._el_16,throwOnChange);
    const currVal_3:any = 'ios-person-outline';
    this._Icon_22_3.check_name(currVal_3,throwOnChange,false);
    this._Icon_22_3.detectChangesInternal(this,this._el_22,throwOnChange);
    if (this._Item_24_4.detectChangesInternal(this,this._el_24,throwOnChange)) { this._appEl_24.componentView.markAsCheckOnce(); }
    this._ItemContent_24_5.detectChangesInternal(this,this._el_24,throwOnChange);
    const currVal_6:any = this.context.name;
    this._NgModel_26_4.check_model(currVal_6,throwOnChange,false);
    this._NgModel_26_4.detectChangesInternal(this,this._el_26,throwOnChange);
    this._NgControlStatus_26_6.detectChangesInternal(this,this._el_26,throwOnChange);
    const currVal_13:any = 'Name';
    this._TextInput_26_7.check_placeholder(currVal_13,throwOnChange,false);
    const currVal_14:any = 'text';
    this._TextInput_26_7.check_type(currVal_14,throwOnChange,false);
    this._TextInput_26_7.detectChangesInternal(this,this._el_26,throwOnChange);
    this._Card_33_3.detectChangesInternal(this,this._el_33,throwOnChange);
    this._CardContent_35_3.detectChangesInternal(this,this._el_35,throwOnChange);
    const currVal_15:any = 'ios-mail-outline';
    this._Icon_41_3.check_name(currVal_15,throwOnChange,false);
    this._Icon_41_3.detectChangesInternal(this,this._el_41,throwOnChange);
    if (this._Item_43_4.detectChangesInternal(this,this._el_43,throwOnChange)) { this._appEl_43.componentView.markAsCheckOnce(); }
    this._ItemContent_43_5.detectChangesInternal(this,this._el_43,throwOnChange);
    const currVal_18:any = this.context.email;
    this._NgModel_45_4.check_model(currVal_18,throwOnChange,false);
    this._NgModel_45_4.detectChangesInternal(this,this._el_45,throwOnChange);
    this._NgControlStatus_45_6.detectChangesInternal(this,this._el_45,throwOnChange);
    const currVal_25:any = 'Email Address';
    this._TextInput_45_7.check_placeholder(currVal_25,throwOnChange,false);
    const currVal_26:any = 'email';
    this._TextInput_45_7.check_type(currVal_26,throwOnChange,false);
    this._TextInput_45_7.detectChangesInternal(this,this._el_45,throwOnChange);
    this._Card_52_3.detectChangesInternal(this,this._el_52,throwOnChange);
    this._CardContent_54_3.detectChangesInternal(this,this._el_54,throwOnChange);
    const currVal_27:any = 'ios-unlock-outline';
    this._Icon_60_3.check_name(currVal_27,throwOnChange,false);
    this._Icon_60_3.detectChangesInternal(this,this._el_60,throwOnChange);
    if (this._Item_62_4.detectChangesInternal(this,this._el_62,throwOnChange)) { this._appEl_62.componentView.markAsCheckOnce(); }
    this._ItemContent_62_5.detectChangesInternal(this,this._el_62,throwOnChange);
    const currVal_30:any = this.context.password;
    this._NgModel_64_4.check_model(currVal_30,throwOnChange,false);
    this._NgModel_64_4.detectChangesInternal(this,this._el_64,throwOnChange);
    this._NgControlStatus_64_6.detectChangesInternal(this,this._el_64,throwOnChange);
    const currVal_37:any = 'Password';
    this._TextInput_64_7.check_placeholder(currVal_37,throwOnChange,false);
    const currVal_38:any = 'password';
    this._TextInput_64_7.check_type(currVal_38,throwOnChange,false);
    this._TextInput_64_7.detectChangesInternal(this,this._el_64,throwOnChange);
    this._Card_71_3.detectChangesInternal(this,this._el_71,throwOnChange);
    this._CardContent_73_3.detectChangesInternal(this,this._el_73,throwOnChange);
    const currVal_39:any = 'ios-unlock-outline';
    this._Icon_79_3.check_name(currVal_39,throwOnChange,false);
    this._Icon_79_3.detectChangesInternal(this,this._el_79,throwOnChange);
    if (this._Item_81_4.detectChangesInternal(this,this._el_81,throwOnChange)) { this._appEl_81.componentView.markAsCheckOnce(); }
    this._ItemContent_81_5.detectChangesInternal(this,this._el_81,throwOnChange);
    const currVal_42:any = this.context.repassword;
    this._NgModel_83_4.check_model(currVal_42,throwOnChange,false);
    this._NgModel_83_4.detectChangesInternal(this,this._el_83,throwOnChange);
    this._NgControlStatus_83_6.detectChangesInternal(this,this._el_83,throwOnChange);
    const currVal_49:any = 'Re-password';
    this._TextInput_83_7.check_placeholder(currVal_49,throwOnChange,false);
    const currVal_50:any = 'password';
    this._TextInput_83_7.check_type(currVal_50,throwOnChange,false);
    this._TextInput_83_7.detectChangesInternal(this,this._el_83,throwOnChange);
    const currVal_53:any = '';
    this._Button_92_4.check_block(currVal_53,throwOnChange,false);
    if (this._Button_92_4.detectChangesInternal(this,this._el_92,throwOnChange)) { this._appEl_92.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_24_1.dirty) {
        this._query_Button_24_1.reset(([] as any[]));
        this._Item_24_4.context._buttons = this._query_Button_24_1;
        this._query_Button_24_1.notifyOnChanges();
      }
      if (this._query_Icon_24_2.dirty) {
        this._query_Icon_24_2.reset(([] as any[]));
        this._Item_24_4.context._icons = this._query_Icon_24_2;
        this._query_Icon_24_2.notifyOnChanges();
      }
      if (this._query_Button_43_1.dirty) {
        this._query_Button_43_1.reset(([] as any[]));
        this._Item_43_4.context._buttons = this._query_Button_43_1;
        this._query_Button_43_1.notifyOnChanges();
      }
      if (this._query_Icon_43_2.dirty) {
        this._query_Icon_43_2.reset(([] as any[]));
        this._Item_43_4.context._icons = this._query_Icon_43_2;
        this._query_Icon_43_2.notifyOnChanges();
      }
      if (this._query_Button_62_1.dirty) {
        this._query_Button_62_1.reset(([] as any[]));
        this._Item_62_4.context._buttons = this._query_Button_62_1;
        this._query_Button_62_1.notifyOnChanges();
      }
      if (this._query_Icon_62_2.dirty) {
        this._query_Icon_62_2.reset(([] as any[]));
        this._Item_62_4.context._icons = this._query_Icon_62_2;
        this._query_Icon_62_2.notifyOnChanges();
      }
      if (this._query_Button_81_1.dirty) {
        this._query_Button_81_1.reset(([] as any[]));
        this._Item_81_4.context._buttons = this._query_Button_81_1;
        this._query_Button_81_1.notifyOnChanges();
      }
      if (this._query_Icon_81_2.dirty) {
        this._query_Icon_81_2.reset(([] as any[]));
        this._Item_81_4.context._icons = this._query_Icon_81_2;
        this._query_Icon_81_2.notifyOnChanges();
      }
      this._TextInput_26_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_24_4.context.ngAfterContentInit(); }
      this._TextInput_45_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_43_4.context.ngAfterContentInit(); }
      this._TextInput_64_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_62_4.context.ngAfterContentInit(); }
      this._TextInput_83_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_81_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_92_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_9_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_4:any = this._Icon_22_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementClass(this._el_22,'hide',currVal_4);
      this._expr_4 = currVal_4;
    }
    const currVal_7:any = this._NgControlStatus_26_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_26,'ng-untouched',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_26_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_26,'ng-touched',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_26_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_26,'ng-pristine',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_26_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_26,'ng-dirty',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_11:any = this._NgControlStatus_26_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_26,'ng-valid',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_12:any = this._NgControlStatus_26_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_12,currVal_12)) {
      this.renderer.setElementClass(this._el_26,'ng-invalid',currVal_12);
      this._expr_12 = currVal_12;
    }
    const currVal_16:any = this._Icon_41_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_41,'hide',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_19:any = this._NgControlStatus_45_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_45,'ng-untouched',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_45_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_45,'ng-touched',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_45_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_45,'ng-pristine',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_45_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_45,'ng-dirty',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_45_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_45,'ng-valid',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_45_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_45,'ng-invalid',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_28:any = this._Icon_60_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_60,'hide',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_31:any = this._NgControlStatus_64_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_31,currVal_31)) {
      this.renderer.setElementClass(this._el_64,'ng-untouched',currVal_31);
      this._expr_31 = currVal_31;
    }
    const currVal_32:any = this._NgControlStatus_64_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementClass(this._el_64,'ng-touched',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_33:any = this._NgControlStatus_64_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_33,currVal_33)) {
      this.renderer.setElementClass(this._el_64,'ng-pristine',currVal_33);
      this._expr_33 = currVal_33;
    }
    const currVal_34:any = this._NgControlStatus_64_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_34,currVal_34)) {
      this.renderer.setElementClass(this._el_64,'ng-dirty',currVal_34);
      this._expr_34 = currVal_34;
    }
    const currVal_35:any = this._NgControlStatus_64_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_64,'ng-valid',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_64_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_64,'ng-invalid',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_40:any = this._Icon_79_3.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_79,'hide',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_43:any = this._NgControlStatus_83_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_43,currVal_43)) {
      this.renderer.setElementClass(this._el_83,'ng-untouched',currVal_43);
      this._expr_43 = currVal_43;
    }
    const currVal_44:any = this._NgControlStatus_83_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementClass(this._el_83,'ng-touched',currVal_44);
      this._expr_44 = currVal_44;
    }
    const currVal_45:any = this._NgControlStatus_83_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_45,currVal_45)) {
      this.renderer.setElementClass(this._el_83,'ng-pristine',currVal_45);
      this._expr_45 = currVal_45;
    }
    const currVal_46:any = this._NgControlStatus_83_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_46,currVal_46)) {
      this.renderer.setElementClass(this._el_83,'ng-dirty',currVal_46);
      this._expr_46 = currVal_46;
    }
    const currVal_47:any = this._NgControlStatus_83_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_47,currVal_47)) {
      this.renderer.setElementClass(this._el_83,'ng-valid',currVal_47);
      this._expr_47 = currVal_47;
    }
    const currVal_48:any = this._NgControlStatus_83_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_48,currVal_48)) {
      this.renderer.setElementClass(this._el_83,'ng-invalid',currVal_48);
      this._expr_48 = currVal_48;
    }
    const currVal_52:any = this.context.disableSubmit;
    if (import4.checkBinding(throwOnChange,this._expr_52,currVal_52)) {
      this.renderer.setElementProperty(this._el_92,'disabled',currVal_52);
      this._expr_52 = currVal_52;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_22_3.context.ngOnDestroy();
    this._NgModel_26_4.context.ngOnDestroy();
    this._TextInput_26_7.context.ngOnDestroy();
    this._Icon_41_3.context.ngOnDestroy();
    this._NgModel_45_4.context.ngOnDestroy();
    this._TextInput_45_7.context.ngOnDestroy();
    this._Icon_60_3.context.ngOnDestroy();
    this._NgModel_64_4.context.ngOnDestroy();
    this._TextInput_64_7.context.ngOnDestroy();
    this._Icon_79_3.context.ngOnDestroy();
    this._NgModel_83_4.context.ngOnDestroy();
    this._TextInput_83_7.context.ngOnDestroy();
    this._Content_9_4.context.ngOnDestroy();
  }
  private _handle_ngModelChange_26_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.name = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_45_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.email = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_64_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.password = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_83_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.repassword = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_92_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.signUpEmail()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SignupPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.SignupPage> {
  if ((renderType_SignupPage === (null as any))) { (renderType_SignupPage = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,styles_SignupPage,{})); }
  return new _View_SignupPage0(viewUtils,parentInjector,declarationEl);
}