/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './signup';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/http/src/http';
import * as import10 from 'ionic-angular/components/alert/alert';
import * as import11 from 'ionic-angular/components/loading/loading';
import * as import12 from '@angular/core/src/metadata/view';
import * as import13 from '@angular/core/src/linker/component_factory';
import * as import14 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import15 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import16 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import17 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import18 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import20 from '@angular/core/src/linker/query_list';
import * as import21 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import22 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/input/input.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import25 from 'ionic-angular/config/config';
import * as import26 from '@angular/core/src/linker/element_ref';
import * as import27 from 'ionic-angular/navigation/view-controller';
import * as import28 from 'ionic-angular/components/app/app';
import * as import29 from 'ionic-angular/components/toolbar/toolbar';
import * as import30 from 'ionic-angular/util/keyboard';
import * as import31 from '@angular/core/src/zone/ng_zone';
import * as import32 from 'ionic-angular/components/tabs/tabs';
import * as import33 from 'ionic-angular/util/form';
import * as import34 from 'ionic-angular/components/item/item-reorder';
import * as import35 from 'ionic-angular/platform/platform';
import * as import36 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import37 from 'ionic-angular/components/navbar/navbar';
import * as import38 from '@angular/forms/src/directives/ng_model';
import * as import39 from '@angular/forms/src/directives/ng_control';
import * as import40 from '@angular/forms/src/directives/ng_control_status';
import * as import41 from 'ionic-angular/components/input/input';
import * as import42 from 'ionic-angular/components/item/item';
import * as import43 from 'ionic-angular/components/card/card';
import * as import44 from 'ionic-angular/components/button/button';
import * as import45 from 'ionic-angular/components/content/content';
export class Wrapper_SignupPage {
  context:import0.SignupPage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any) {
    this.changed = false;
    this.context = new import0.SignupPage(p0,p1,p2,p3);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_SignupPage_Host:import2.RenderComponentType = (null as any);
class _View_SignupPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _SignupPage_0_4:Wrapper_SignupPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SignupPage_Host0,renderType_SignupPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-signup',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_SignupPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._SignupPage_0_4 = new Wrapper_SignupPage(this.parentInjector.get(import8.NavController),this.parentInjector.get(import9.Http),this.parentInjector.get(import10.AlertController),this.parentInjector.get(import11.LoadingController));
    this._appEl_0.initComponent(this._SignupPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._SignupPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.SignupPage) && (0 === requestNodeIndex))) { return this._SignupPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._SignupPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_SignupPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_SignupPage_Host === (null as any))) { (renderType_SignupPage_Host = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_SignupPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const SignupPageNgFactory:import13.ComponentFactory<import0.SignupPage> = new import13.ComponentFactory<import0.SignupPage>('page-signup',viewFactory_SignupPage_Host0,import0.SignupPage);
const styles_SignupPage:any[] = ([] as any[]);
var renderType_SignupPage:import2.RenderComponentType = (null as any);
class _View_SignupPage0 extends import1.AppView<import0.SignupPage> {
  _el_0:any;
  _Header_0_3:import14.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import15.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import16.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import17.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _Card_16_3:import18.Wrapper_Card;
  _text_17:any;
  _el_18:any;
  _CardContent_18_3:import18.Wrapper_CardContent;
  _text_19:any;
  _el_20:any;
  /*private*/ _appEl_20:import3.AppElement;
  _Item_20_4:import19.Wrapper_Item;
  _ItemContent_20_5:import19.Wrapper_ItemContent;
  _query_Label_20_0:import20.QueryList<any>;
  _query_Button_20_1:import20.QueryList<any>;
  _query_Icon_20_2:import20.QueryList<any>;
  _text_21:any;
  _el_22:any;
  /*private*/ _appEl_22:import3.AppElement;
  _NgModel_22_4:import21.Wrapper_NgModel;
  _NgControl_22_5:any;
  _NgControlStatus_22_6:import22.Wrapper_NgControlStatus;
  _TextInput_22_7:import23.Wrapper_TextInput;
  _text_23:any;
  _text_24:any;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _Card_27_3:import18.Wrapper_Card;
  _text_28:any;
  _el_29:any;
  _CardContent_29_3:import18.Wrapper_CardContent;
  _text_30:any;
  _el_31:any;
  /*private*/ _appEl_31:import3.AppElement;
  _Item_31_4:import19.Wrapper_Item;
  _ItemContent_31_5:import19.Wrapper_ItemContent;
  _query_Label_31_0:import20.QueryList<any>;
  _query_Button_31_1:import20.QueryList<any>;
  _query_Icon_31_2:import20.QueryList<any>;
  _text_32:any;
  _el_33:any;
  /*private*/ _appEl_33:import3.AppElement;
  _NgModel_33_4:import21.Wrapper_NgModel;
  _NgControl_33_5:any;
  _NgControlStatus_33_6:import22.Wrapper_NgControlStatus;
  _TextInput_33_7:import23.Wrapper_TextInput;
  _text_34:any;
  _text_35:any;
  _text_36:any;
  _text_37:any;
  _el_38:any;
  _Card_38_3:import18.Wrapper_Card;
  _text_39:any;
  _el_40:any;
  _CardContent_40_3:import18.Wrapper_CardContent;
  _text_41:any;
  _el_42:any;
  /*private*/ _appEl_42:import3.AppElement;
  _Item_42_4:import19.Wrapper_Item;
  _ItemContent_42_5:import19.Wrapper_ItemContent;
  _query_Label_42_0:import20.QueryList<any>;
  _query_Button_42_1:import20.QueryList<any>;
  _query_Icon_42_2:import20.QueryList<any>;
  _text_43:any;
  _el_44:any;
  /*private*/ _appEl_44:import3.AppElement;
  _NgModel_44_4:import21.Wrapper_NgModel;
  _NgControl_44_5:any;
  _NgControlStatus_44_6:import22.Wrapper_NgControlStatus;
  _TextInput_44_7:import23.Wrapper_TextInput;
  _text_45:any;
  _text_46:any;
  _text_47:any;
  _text_48:any;
  _el_49:any;
  _Card_49_3:import18.Wrapper_Card;
  _text_50:any;
  _el_51:any;
  _CardContent_51_3:import18.Wrapper_CardContent;
  _text_52:any;
  _el_53:any;
  /*private*/ _appEl_53:import3.AppElement;
  _Item_53_4:import19.Wrapper_Item;
  _ItemContent_53_5:import19.Wrapper_ItemContent;
  _query_Label_53_0:import20.QueryList<any>;
  _query_Button_53_1:import20.QueryList<any>;
  _query_Icon_53_2:import20.QueryList<any>;
  _text_54:any;
  _el_55:any;
  /*private*/ _appEl_55:import3.AppElement;
  _NgModel_55_4:import21.Wrapper_NgModel;
  _NgControl_55_5:any;
  _NgControlStatus_55_6:import22.Wrapper_NgControlStatus;
  _TextInput_55_7:import23.Wrapper_TextInput;
  _text_56:any;
  _text_57:any;
  _text_58:any;
  _text_59:any;
  _el_60:any;
  _text_61:any;
  _el_62:any;
  /*private*/ _appEl_62:import3.AppElement;
  _Button_62_4:import24.Wrapper_Button;
  _text_63:any;
  _text_64:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_5:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_7:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_9:any;
  /*private*/ _expr_10:any;
  /*private*/ _expr_15:any;
  /*private*/ _expr_16:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_18:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_25:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_28:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_35:any;
  /*private*/ _expr_36:any;
  /*private*/ _expr_37:any;
  /*private*/ _expr_38:any;
  /*private*/ _expr_39:any;
  /*private*/ _expr_40:any;
  /*private*/ _expr_44:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_SignupPage0,renderType_SignupPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import14.Wrapper_Header(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import27.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import15.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import15.Wrapper_Navbar(this.parentInjector.get(import28.App),this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import16.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import16.Wrapper_ToolbarTitle(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import29.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'SIGN UP',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'padding','');
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import17.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import17.Wrapper_Content(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import28.App),this.parentInjector.get(import30.Keyboard),this.parentInjector.get(import31.NgZone),this.parentInjector.get(import27.ViewController,(null as any)),this.parentInjector.get(import32.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'br',(null as any));
    this._text_12 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_13 = this.renderer.createElement((null as any),'h2',(null as any));
    this.renderer.setElementAttribute(this._el_13,'style','color:#9b9b9b;text-align: center;font-weight: bold;');
    this._text_14 = this.renderer.createText(this._el_13,'Please fill up details below',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_16_3 = new import18.Wrapper_Card(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_16),this.renderer);
    this._text_17 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'ion-card-content',(null as any));
    this._CardContent_18_3 = new import18.Wrapper_CardContent(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_18),this.renderer);
    this._text_19 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','item item-block');
    this._appEl_20 = new import3.AppElement(20,18,this,this._el_20);
    var compView_20:any = import19.viewFactory_Item0(this.viewUtils,this.injector(20),this._appEl_20);
    this._Item_20_4 = new import19.Wrapper_Item(this.parentInjector.get(import33.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_20),this.renderer,this.parentInjector.get(import34.ItemReorder,(null as any)));
    this._ItemContent_20_5 = new import19.Wrapper_ItemContent();
    this._query_Label_20_0 = new import20.QueryList<any>();
    this._query_Button_20_1 = new import20.QueryList<any>();
    this._query_Icon_20_2 = new import20.QueryList<any>();
    this._appEl_20.initComponent(this._Item_20_4.context,([] as any[]),compView_20);
    this._text_21 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_22,'placeholder','Name');
    this.renderer.setElementAttribute(this._el_22,'type','text');
    this._appEl_22 = new import3.AppElement(22,20,this,this._el_22);
    var compView_22:any = import23.viewFactory_TextInput0(this.viewUtils,this.injector(22),this._appEl_22);
    this._NgModel_22_4 = new import21.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_22_5 = this._NgModel_22_4.context;
    this._NgControlStatus_22_6 = new import22.Wrapper_NgControlStatus(this._NgControl_22_5);
    this._TextInput_22_7 = new import23.Wrapper_TextInput(this.parentInjector.get(import25.Config),this.parentInjector.get(import33.Form),this._Item_20_4.context,this.parentInjector.get(import28.App),this.parentInjector.get(import35.Platform),new import26.ElementRef(this._el_22),this.renderer,this._Content_9_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_22_5);
    this._appEl_22.initComponent(this._TextInput_22_7.context,([] as any[]),compView_22);
    compView_22.create(this._TextInput_22_7.context,([] as any[]),(null as any));
    this._text_23 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_20_0.reset(([] as any[]));
    this._Item_20_4.context.contentLabel = this._query_Label_20_0.first;
    compView_20.create(this._Item_20_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_21,
        this._text_23
      ]
      ),
      ([] as any[]).concat([this._el_22]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_24 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._text_25 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._text_26 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_27 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_27_3 = new import18.Wrapper_Card(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_27),this.renderer);
    this._text_28 = this.renderer.createText(this._el_27,'\n        ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_27,'ion-card-content',(null as any));
    this._CardContent_29_3 = new import18.Wrapper_CardContent(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_29),this.renderer);
    this._text_30 = this.renderer.createText(this._el_29,'\n            ',(null as any));
    this._el_31 = this.renderer.createElement(this._el_29,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','item item-block');
    this._appEl_31 = new import3.AppElement(31,29,this,this._el_31);
    var compView_31:any = import19.viewFactory_Item0(this.viewUtils,this.injector(31),this._appEl_31);
    this._Item_31_4 = new import19.Wrapper_Item(this.parentInjector.get(import33.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_31),this.renderer,this.parentInjector.get(import34.ItemReorder,(null as any)));
    this._ItemContent_31_5 = new import19.Wrapper_ItemContent();
    this._query_Label_31_0 = new import20.QueryList<any>();
    this._query_Button_31_1 = new import20.QueryList<any>();
    this._query_Icon_31_2 = new import20.QueryList<any>();
    this._appEl_31.initComponent(this._Item_31_4.context,([] as any[]),compView_31);
    this._text_32 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_33 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_33,'placeholder','Email Address');
    this.renderer.setElementAttribute(this._el_33,'type','email');
    this._appEl_33 = new import3.AppElement(33,31,this,this._el_33);
    var compView_33:any = import23.viewFactory_TextInput0(this.viewUtils,this.injector(33),this._appEl_33);
    this._NgModel_33_4 = new import21.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_33_5 = this._NgModel_33_4.context;
    this._NgControlStatus_33_6 = new import22.Wrapper_NgControlStatus(this._NgControl_33_5);
    this._TextInput_33_7 = new import23.Wrapper_TextInput(this.parentInjector.get(import25.Config),this.parentInjector.get(import33.Form),this._Item_31_4.context,this.parentInjector.get(import28.App),this.parentInjector.get(import35.Platform),new import26.ElementRef(this._el_33),this.renderer,this._Content_9_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_33_5);
    this._appEl_33.initComponent(this._TextInput_33_7.context,([] as any[]),compView_33);
    compView_33.create(this._TextInput_33_7.context,([] as any[]),(null as any));
    this._text_34 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_31_0.reset(([] as any[]));
    this._Item_31_4.context.contentLabel = this._query_Label_31_0.first;
    compView_31.create(this._Item_31_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_32,
        this._text_34
      ]
      ),
      ([] as any[]).concat([this._el_33]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_35 = this.renderer.createText(this._el_29,'\n        ',(null as any));
    this._text_36 = this.renderer.createText(this._el_27,'\n    ',(null as any));
    this._text_37 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_38 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_38_3 = new import18.Wrapper_Card(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_38),this.renderer);
    this._text_39 = this.renderer.createText(this._el_38,'\n        ',(null as any));
    this._el_40 = this.renderer.createElement(this._el_38,'ion-card-content',(null as any));
    this._CardContent_40_3 = new import18.Wrapper_CardContent(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_40),this.renderer);
    this._text_41 = this.renderer.createText(this._el_40,'\n            ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_40,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','item item-block');
    this._appEl_42 = new import3.AppElement(42,40,this,this._el_42);
    var compView_42:any = import19.viewFactory_Item0(this.viewUtils,this.injector(42),this._appEl_42);
    this._Item_42_4 = new import19.Wrapper_Item(this.parentInjector.get(import33.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_42),this.renderer,this.parentInjector.get(import34.ItemReorder,(null as any)));
    this._ItemContent_42_5 = new import19.Wrapper_ItemContent();
    this._query_Label_42_0 = new import20.QueryList<any>();
    this._query_Button_42_1 = new import20.QueryList<any>();
    this._query_Icon_42_2 = new import20.QueryList<any>();
    this._appEl_42.initComponent(this._Item_42_4.context,([] as any[]),compView_42);
    this._text_43 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_44 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_44,'placeholder','Password');
    this.renderer.setElementAttribute(this._el_44,'type','password');
    this._appEl_44 = new import3.AppElement(44,42,this,this._el_44);
    var compView_44:any = import23.viewFactory_TextInput0(this.viewUtils,this.injector(44),this._appEl_44);
    this._NgModel_44_4 = new import21.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_44_5 = this._NgModel_44_4.context;
    this._NgControlStatus_44_6 = new import22.Wrapper_NgControlStatus(this._NgControl_44_5);
    this._TextInput_44_7 = new import23.Wrapper_TextInput(this.parentInjector.get(import25.Config),this.parentInjector.get(import33.Form),this._Item_42_4.context,this.parentInjector.get(import28.App),this.parentInjector.get(import35.Platform),new import26.ElementRef(this._el_44),this.renderer,this._Content_9_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_44_5);
    this._appEl_44.initComponent(this._TextInput_44_7.context,([] as any[]),compView_44);
    compView_44.create(this._TextInput_44_7.context,([] as any[]),(null as any));
    this._text_45 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_42_0.reset(([] as any[]));
    this._Item_42_4.context.contentLabel = this._query_Label_42_0.first;
    compView_42.create(this._Item_42_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_43,
        this._text_45
      ]
      ),
      ([] as any[]).concat([this._el_44]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_46 = this.renderer.createText(this._el_40,'\n        ',(null as any));
    this._text_47 = this.renderer.createText(this._el_38,'\n    ',(null as any));
    this._text_48 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_49 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_49_3 = new import18.Wrapper_Card(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_49),this.renderer);
    this._text_50 = this.renderer.createText(this._el_49,'\n        ',(null as any));
    this._el_51 = this.renderer.createElement(this._el_49,'ion-card-content',(null as any));
    this._CardContent_51_3 = new import18.Wrapper_CardContent(this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_51),this.renderer);
    this._text_52 = this.renderer.createText(this._el_51,'\n            ',(null as any));
    this._el_53 = this.renderer.createElement(this._el_51,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_53,'class','item item-block');
    this._appEl_53 = new import3.AppElement(53,51,this,this._el_53);
    var compView_53:any = import19.viewFactory_Item0(this.viewUtils,this.injector(53),this._appEl_53);
    this._Item_53_4 = new import19.Wrapper_Item(this.parentInjector.get(import33.Form),this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_53),this.renderer,this.parentInjector.get(import34.ItemReorder,(null as any)));
    this._ItemContent_53_5 = new import19.Wrapper_ItemContent();
    this._query_Label_53_0 = new import20.QueryList<any>();
    this._query_Button_53_1 = new import20.QueryList<any>();
    this._query_Icon_53_2 = new import20.QueryList<any>();
    this._appEl_53.initComponent(this._Item_53_4.context,([] as any[]),compView_53);
    this._text_54 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_55 = this.renderer.createElement((null as any),'ion-input',(null as any));
    this.renderer.setElementAttribute(this._el_55,'placeholder','Re-password');
    this.renderer.setElementAttribute(this._el_55,'type','password');
    this._appEl_55 = new import3.AppElement(55,53,this,this._el_55);
    var compView_55:any = import23.viewFactory_TextInput0(this.viewUtils,this.injector(55),this._appEl_55);
    this._NgModel_55_4 = new import21.Wrapper_NgModel((null as any),(null as any),(null as any),(null as any));
    this._NgControl_55_5 = this._NgModel_55_4.context;
    this._NgControlStatus_55_6 = new import22.Wrapper_NgControlStatus(this._NgControl_55_5);
    this._TextInput_55_7 = new import23.Wrapper_TextInput(this.parentInjector.get(import25.Config),this.parentInjector.get(import33.Form),this._Item_53_4.context,this.parentInjector.get(import28.App),this.parentInjector.get(import35.Platform),new import26.ElementRef(this._el_55),this.renderer,this._Content_9_4.context,this.parentInjector.get(import8.NavController,(null as any)),this._NgControl_55_5);
    this._appEl_55.initComponent(this._TextInput_55_7.context,([] as any[]),compView_55);
    compView_55.create(this._TextInput_55_7.context,([] as any[]),(null as any));
    this._text_56 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_53_0.reset(([] as any[]));
    this._Item_53_4.context.contentLabel = this._query_Label_53_0.first;
    compView_53.create(this._Item_53_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_54,
        this._text_56
      ]
      ),
      ([] as any[]).concat([this._el_55]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_57 = this.renderer.createText(this._el_51,'\n        ',(null as any));
    this._text_58 = this.renderer.createText(this._el_49,'\n    ',(null as any));
    this._text_59 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_60 = this.renderer.createElement((null as any),'br',(null as any));
    this._text_61 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_62 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_62,'block','');
    this.renderer.setElementAttribute(this._el_62,'ion-button','');
    this.renderer.setElementAttribute(this._el_62,'style','color:#ffffff;background-color:#f85394;font-weight: bold;');
    this._appEl_62 = new import3.AppElement(62,9,this,this._el_62);
    var compView_62:any = import24.viewFactory_Button0(this.viewUtils,this.injector(62),this._appEl_62);
    this._Button_62_4 = new import24.Wrapper_Button((null as any),'',this.parentInjector.get(import25.Config),new import26.ElementRef(this._el_62),this.renderer);
    this._appEl_62.initComponent(this._Button_62_4.context,([] as any[]),compView_62);
    this._text_63 = this.renderer.createText((null as any),'Sign up',(null as any));
    compView_62.create(this._Button_62_4.context,[([] as any[]).concat([this._text_63])],(null as any));
    this._text_64 = this.renderer.createText((null as any),'\n',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_12,
        this._el_13,
        this._text_15,
        this._el_16,
        this._text_26,
        this._el_27,
        this._text_37,
        this._el_38,
        this._text_48,
        this._el_49,
        this._text_59,
        this._el_60,
        this._text_61,
        this._el_62,
        this._text_64
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_22,'ngModelChange',this.eventHandler(this._handle_ngModelChange_22_0.bind(this)));
    const subscription_0:any = this._NgModel_22_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_22_0.bind(this)));
    this._expr_5 = import7.UNINITIALIZED;
    this._expr_6 = import7.UNINITIALIZED;
    this._expr_7 = import7.UNINITIALIZED;
    this._expr_8 = import7.UNINITIALIZED;
    this._expr_9 = import7.UNINITIALIZED;
    this._expr_10 = import7.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_33,'ngModelChange',this.eventHandler(this._handle_ngModelChange_33_0.bind(this)));
    const subscription_1:any = this._NgModel_33_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_33_0.bind(this)));
    this._expr_15 = import7.UNINITIALIZED;
    this._expr_16 = import7.UNINITIALIZED;
    this._expr_17 = import7.UNINITIALIZED;
    this._expr_18 = import7.UNINITIALIZED;
    this._expr_19 = import7.UNINITIALIZED;
    this._expr_20 = import7.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_44,'ngModelChange',this.eventHandler(this._handle_ngModelChange_44_0.bind(this)));
    const subscription_2:any = this._NgModel_44_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_44_0.bind(this)));
    this._expr_25 = import7.UNINITIALIZED;
    this._expr_26 = import7.UNINITIALIZED;
    this._expr_27 = import7.UNINITIALIZED;
    this._expr_28 = import7.UNINITIALIZED;
    this._expr_29 = import7.UNINITIALIZED;
    this._expr_30 = import7.UNINITIALIZED;
    var disposable_3:Function = this.renderer.listen(this._el_55,'ngModelChange',this.eventHandler(this._handle_ngModelChange_55_0.bind(this)));
    const subscription_3:any = this._NgModel_55_4.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_55_0.bind(this)));
    this._expr_35 = import7.UNINITIALIZED;
    this._expr_36 = import7.UNINITIALIZED;
    this._expr_37 = import7.UNINITIALIZED;
    this._expr_38 = import7.UNINITIALIZED;
    this._expr_39 = import7.UNINITIALIZED;
    this._expr_40 = import7.UNINITIALIZED;
    this._expr_44 = import7.UNINITIALIZED;
    var disposable_4:Function = this.renderer.listen(this._el_62,'click',this.eventHandler(this._handle_click_62_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._text_36,
      this._text_37,
      this._el_38,
      this._text_39,
      this._el_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._text_46,
      this._text_47,
      this._text_48,
      this._el_49,
      this._text_50,
      this._el_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._text_57,
      this._text_58,
      this._text_59,
      this._el_60,
      this._text_61,
      this._el_62,
      this._text_63,
      this._text_64
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4
    ]
    ,[
      subscription_0,
      subscription_1,
      subscription_2,
      subscription_3
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import36.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import37.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import29.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import38.NgModel) && (22 === requestNodeIndex))) { return this._NgModel_22_4.context; }
    if (((token === import39.NgControl) && (22 === requestNodeIndex))) { return this._NgControl_22_5; }
    if (((token === import40.NgControlStatus) && (22 === requestNodeIndex))) { return this._NgControlStatus_22_6.context; }
    if (((token === import41.TextInput) && (22 === requestNodeIndex))) { return this._TextInput_22_7.context; }
    if (((token === import42.Item) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._Item_20_4.context; }
    if (((token === import42.ItemContent) && ((20 <= requestNodeIndex) && (requestNodeIndex <= 23)))) { return this._ItemContent_20_5.context; }
    if (((token === import43.CardContent) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 24)))) { return this._CardContent_18_3.context; }
    if (((token === import43.Card) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 25)))) { return this._Card_16_3.context; }
    if (((token === import38.NgModel) && (33 === requestNodeIndex))) { return this._NgModel_33_4.context; }
    if (((token === import39.NgControl) && (33 === requestNodeIndex))) { return this._NgControl_33_5; }
    if (((token === import40.NgControlStatus) && (33 === requestNodeIndex))) { return this._NgControlStatus_33_6.context; }
    if (((token === import41.TextInput) && (33 === requestNodeIndex))) { return this._TextInput_33_7.context; }
    if (((token === import42.Item) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._Item_31_4.context; }
    if (((token === import42.ItemContent) && ((31 <= requestNodeIndex) && (requestNodeIndex <= 34)))) { return this._ItemContent_31_5.context; }
    if (((token === import43.CardContent) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 35)))) { return this._CardContent_29_3.context; }
    if (((token === import43.Card) && ((27 <= requestNodeIndex) && (requestNodeIndex <= 36)))) { return this._Card_27_3.context; }
    if (((token === import38.NgModel) && (44 === requestNodeIndex))) { return this._NgModel_44_4.context; }
    if (((token === import39.NgControl) && (44 === requestNodeIndex))) { return this._NgControl_44_5; }
    if (((token === import40.NgControlStatus) && (44 === requestNodeIndex))) { return this._NgControlStatus_44_6.context; }
    if (((token === import41.TextInput) && (44 === requestNodeIndex))) { return this._TextInput_44_7.context; }
    if (((token === import42.Item) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._Item_42_4.context; }
    if (((token === import42.ItemContent) && ((42 <= requestNodeIndex) && (requestNodeIndex <= 45)))) { return this._ItemContent_42_5.context; }
    if (((token === import43.CardContent) && ((40 <= requestNodeIndex) && (requestNodeIndex <= 46)))) { return this._CardContent_40_3.context; }
    if (((token === import43.Card) && ((38 <= requestNodeIndex) && (requestNodeIndex <= 47)))) { return this._Card_38_3.context; }
    if (((token === import38.NgModel) && (55 === requestNodeIndex))) { return this._NgModel_55_4.context; }
    if (((token === import39.NgControl) && (55 === requestNodeIndex))) { return this._NgControl_55_5; }
    if (((token === import40.NgControlStatus) && (55 === requestNodeIndex))) { return this._NgControlStatus_55_6.context; }
    if (((token === import41.TextInput) && (55 === requestNodeIndex))) { return this._TextInput_55_7.context; }
    if (((token === import42.Item) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._Item_53_4.context; }
    if (((token === import42.ItemContent) && ((53 <= requestNodeIndex) && (requestNodeIndex <= 56)))) { return this._ItemContent_53_5.context; }
    if (((token === import43.CardContent) && ((51 <= requestNodeIndex) && (requestNodeIndex <= 57)))) { return this._CardContent_51_3.context; }
    if (((token === import43.Card) && ((49 <= requestNodeIndex) && (requestNodeIndex <= 58)))) { return this._Card_49_3.context; }
    if (((token === import44.Button) && ((62 <= requestNodeIndex) && (requestNodeIndex <= 63)))) { return this._Button_62_4.context; }
    if (((token === import45.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 64)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    this._Card_16_3.detectChangesInternal(this,this._el_16,throwOnChange);
    this._CardContent_18_3.detectChangesInternal(this,this._el_18,throwOnChange);
    if (this._Item_20_4.detectChangesInternal(this,this._el_20,throwOnChange)) { this._appEl_20.componentView.markAsCheckOnce(); }
    this._ItemContent_20_5.detectChangesInternal(this,this._el_20,throwOnChange);
    const currVal_4:any = this.context.name;
    this._NgModel_22_4.check_model(currVal_4,throwOnChange,false);
    this._NgModel_22_4.detectChangesInternal(this,this._el_22,throwOnChange);
    this._NgControlStatus_22_6.detectChangesInternal(this,this._el_22,throwOnChange);
    const currVal_11:any = 'Name';
    this._TextInput_22_7.check_placeholder(currVal_11,throwOnChange,false);
    const currVal_12:any = 'text';
    this._TextInput_22_7.check_type(currVal_12,throwOnChange,false);
    this._TextInput_22_7.detectChangesInternal(this,this._el_22,throwOnChange);
    this._Card_27_3.detectChangesInternal(this,this._el_27,throwOnChange);
    this._CardContent_29_3.detectChangesInternal(this,this._el_29,throwOnChange);
    if (this._Item_31_4.detectChangesInternal(this,this._el_31,throwOnChange)) { this._appEl_31.componentView.markAsCheckOnce(); }
    this._ItemContent_31_5.detectChangesInternal(this,this._el_31,throwOnChange);
    const currVal_14:any = this.context.email;
    this._NgModel_33_4.check_model(currVal_14,throwOnChange,false);
    this._NgModel_33_4.detectChangesInternal(this,this._el_33,throwOnChange);
    this._NgControlStatus_33_6.detectChangesInternal(this,this._el_33,throwOnChange);
    const currVal_21:any = 'Email Address';
    this._TextInput_33_7.check_placeholder(currVal_21,throwOnChange,false);
    const currVal_22:any = 'email';
    this._TextInput_33_7.check_type(currVal_22,throwOnChange,false);
    this._TextInput_33_7.detectChangesInternal(this,this._el_33,throwOnChange);
    this._Card_38_3.detectChangesInternal(this,this._el_38,throwOnChange);
    this._CardContent_40_3.detectChangesInternal(this,this._el_40,throwOnChange);
    if (this._Item_42_4.detectChangesInternal(this,this._el_42,throwOnChange)) { this._appEl_42.componentView.markAsCheckOnce(); }
    this._ItemContent_42_5.detectChangesInternal(this,this._el_42,throwOnChange);
    const currVal_24:any = this.context.password;
    this._NgModel_44_4.check_model(currVal_24,throwOnChange,false);
    this._NgModel_44_4.detectChangesInternal(this,this._el_44,throwOnChange);
    this._NgControlStatus_44_6.detectChangesInternal(this,this._el_44,throwOnChange);
    const currVal_31:any = 'Password';
    this._TextInput_44_7.check_placeholder(currVal_31,throwOnChange,false);
    const currVal_32:any = 'password';
    this._TextInput_44_7.check_type(currVal_32,throwOnChange,false);
    this._TextInput_44_7.detectChangesInternal(this,this._el_44,throwOnChange);
    this._Card_49_3.detectChangesInternal(this,this._el_49,throwOnChange);
    this._CardContent_51_3.detectChangesInternal(this,this._el_51,throwOnChange);
    if (this._Item_53_4.detectChangesInternal(this,this._el_53,throwOnChange)) { this._appEl_53.componentView.markAsCheckOnce(); }
    this._ItemContent_53_5.detectChangesInternal(this,this._el_53,throwOnChange);
    const currVal_34:any = this.context.repassword;
    this._NgModel_55_4.check_model(currVal_34,throwOnChange,false);
    this._NgModel_55_4.detectChangesInternal(this,this._el_55,throwOnChange);
    this._NgControlStatus_55_6.detectChangesInternal(this,this._el_55,throwOnChange);
    const currVal_41:any = 'Re-password';
    this._TextInput_55_7.check_placeholder(currVal_41,throwOnChange,false);
    const currVal_42:any = 'password';
    this._TextInput_55_7.check_type(currVal_42,throwOnChange,false);
    this._TextInput_55_7.detectChangesInternal(this,this._el_55,throwOnChange);
    const currVal_45:any = '';
    this._Button_62_4.check_block(currVal_45,throwOnChange,false);
    if (this._Button_62_4.detectChangesInternal(this,this._el_62,throwOnChange)) { this._appEl_62.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_20_1.dirty) {
        this._query_Button_20_1.reset(([] as any[]));
        this._Item_20_4.context._buttons = this._query_Button_20_1;
        this._query_Button_20_1.notifyOnChanges();
      }
      if (this._query_Icon_20_2.dirty) {
        this._query_Icon_20_2.reset(([] as any[]));
        this._Item_20_4.context._icons = this._query_Icon_20_2;
        this._query_Icon_20_2.notifyOnChanges();
      }
      if (this._query_Button_31_1.dirty) {
        this._query_Button_31_1.reset(([] as any[]));
        this._Item_31_4.context._buttons = this._query_Button_31_1;
        this._query_Button_31_1.notifyOnChanges();
      }
      if (this._query_Icon_31_2.dirty) {
        this._query_Icon_31_2.reset(([] as any[]));
        this._Item_31_4.context._icons = this._query_Icon_31_2;
        this._query_Icon_31_2.notifyOnChanges();
      }
      if (this._query_Button_42_1.dirty) {
        this._query_Button_42_1.reset(([] as any[]));
        this._Item_42_4.context._buttons = this._query_Button_42_1;
        this._query_Button_42_1.notifyOnChanges();
      }
      if (this._query_Icon_42_2.dirty) {
        this._query_Icon_42_2.reset(([] as any[]));
        this._Item_42_4.context._icons = this._query_Icon_42_2;
        this._query_Icon_42_2.notifyOnChanges();
      }
      if (this._query_Button_53_1.dirty) {
        this._query_Button_53_1.reset(([] as any[]));
        this._Item_53_4.context._buttons = this._query_Button_53_1;
        this._query_Button_53_1.notifyOnChanges();
      }
      if (this._query_Icon_53_2.dirty) {
        this._query_Icon_53_2.reset(([] as any[]));
        this._Item_53_4.context._icons = this._query_Icon_53_2;
        this._query_Icon_53_2.notifyOnChanges();
      }
      this._TextInput_22_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_20_4.context.ngAfterContentInit(); }
      this._TextInput_33_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_31_4.context.ngAfterContentInit(); }
      this._TextInput_44_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_42_4.context.ngAfterContentInit(); }
      this._TextInput_55_7.context.ngAfterContentChecked();
      if ((this.numberOfChecks === 0)) { this._Item_53_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_62_4.context.ngAfterContentInit(); }
    }
    const currVal_0:any = this._Navbar_2_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_2_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_9_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_5:any = this._NgControlStatus_22_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_5,currVal_5)) {
      this.renderer.setElementClass(this._el_22,'ng-untouched',currVal_5);
      this._expr_5 = currVal_5;
    }
    const currVal_6:any = this._NgControlStatus_22_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_22,'ng-touched',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_7:any = this._NgControlStatus_22_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_7,currVal_7)) {
      this.renderer.setElementClass(this._el_22,'ng-pristine',currVal_7);
      this._expr_7 = currVal_7;
    }
    const currVal_8:any = this._NgControlStatus_22_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setElementClass(this._el_22,'ng-dirty',currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_9:any = this._NgControlStatus_22_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_9,currVal_9)) {
      this.renderer.setElementClass(this._el_22,'ng-valid',currVal_9);
      this._expr_9 = currVal_9;
    }
    const currVal_10:any = this._NgControlStatus_22_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_10,currVal_10)) {
      this.renderer.setElementClass(this._el_22,'ng-invalid',currVal_10);
      this._expr_10 = currVal_10;
    }
    const currVal_15:any = this._NgControlStatus_33_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_15,currVal_15)) {
      this.renderer.setElementClass(this._el_33,'ng-untouched',currVal_15);
      this._expr_15 = currVal_15;
    }
    const currVal_16:any = this._NgControlStatus_33_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_16,currVal_16)) {
      this.renderer.setElementClass(this._el_33,'ng-touched',currVal_16);
      this._expr_16 = currVal_16;
    }
    const currVal_17:any = this._NgControlStatus_33_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_33,'ng-pristine',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_18:any = this._NgControlStatus_33_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_18,currVal_18)) {
      this.renderer.setElementClass(this._el_33,'ng-dirty',currVal_18);
      this._expr_18 = currVal_18;
    }
    const currVal_19:any = this._NgControlStatus_33_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_33,'ng-valid',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_33_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_33,'ng-invalid',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_25:any = this._NgControlStatus_44_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_25,currVal_25)) {
      this.renderer.setElementClass(this._el_44,'ng-untouched',currVal_25);
      this._expr_25 = currVal_25;
    }
    const currVal_26:any = this._NgControlStatus_44_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_44,'ng-touched',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = this._NgControlStatus_44_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setElementClass(this._el_44,'ng-pristine',currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_28:any = this._NgControlStatus_44_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_28,currVal_28)) {
      this.renderer.setElementClass(this._el_44,'ng-dirty',currVal_28);
      this._expr_28 = currVal_28;
    }
    const currVal_29:any = this._NgControlStatus_44_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_44,'ng-valid',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = this._NgControlStatus_44_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setElementClass(this._el_44,'ng-invalid',currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_35:any = this._NgControlStatus_55_6.context.ngClassUntouched;
    if (import4.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementClass(this._el_55,'ng-untouched',currVal_35);
      this._expr_35 = currVal_35;
    }
    const currVal_36:any = this._NgControlStatus_55_6.context.ngClassTouched;
    if (import4.checkBinding(throwOnChange,this._expr_36,currVal_36)) {
      this.renderer.setElementClass(this._el_55,'ng-touched',currVal_36);
      this._expr_36 = currVal_36;
    }
    const currVal_37:any = this._NgControlStatus_55_6.context.ngClassPristine;
    if (import4.checkBinding(throwOnChange,this._expr_37,currVal_37)) {
      this.renderer.setElementClass(this._el_55,'ng-pristine',currVal_37);
      this._expr_37 = currVal_37;
    }
    const currVal_38:any = this._NgControlStatus_55_6.context.ngClassDirty;
    if (import4.checkBinding(throwOnChange,this._expr_38,currVal_38)) {
      this.renderer.setElementClass(this._el_55,'ng-dirty',currVal_38);
      this._expr_38 = currVal_38;
    }
    const currVal_39:any = this._NgControlStatus_55_6.context.ngClassValid;
    if (import4.checkBinding(throwOnChange,this._expr_39,currVal_39)) {
      this.renderer.setElementClass(this._el_55,'ng-valid',currVal_39);
      this._expr_39 = currVal_39;
    }
    const currVal_40:any = this._NgControlStatus_55_6.context.ngClassInvalid;
    if (import4.checkBinding(throwOnChange,this._expr_40,currVal_40)) {
      this.renderer.setElementClass(this._el_55,'ng-invalid',currVal_40);
      this._expr_40 = currVal_40;
    }
    const currVal_44:any = this.context.disableSubmit;
    if (import4.checkBinding(throwOnChange,this._expr_44,currVal_44)) {
      this.renderer.setElementProperty(this._el_62,'disabled',currVal_44);
      this._expr_44 = currVal_44;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._NgModel_22_4.context.ngOnDestroy();
    this._TextInput_22_7.context.ngOnDestroy();
    this._NgModel_33_4.context.ngOnDestroy();
    this._TextInput_33_7.context.ngOnDestroy();
    this._NgModel_44_4.context.ngOnDestroy();
    this._TextInput_44_7.context.ngOnDestroy();
    this._NgModel_55_4.context.ngOnDestroy();
    this._TextInput_55_7.context.ngOnDestroy();
    this._Content_9_4.context.ngOnDestroy();
  }
  private _handle_ngModelChange_22_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.name = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_33_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.email = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_44_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.password = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_55_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.repassword = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_62_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.signUpEmail()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_SignupPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.SignupPage> {
  if ((renderType_SignupPage === (null as any))) { (renderType_SignupPage = viewUtils.createRenderComponentType('',0,import12.ViewEncapsulation.None,styles_SignupPage,{})); }
  return new _View_SignupPage0(viewUtils,parentInjector,declarationEl);
}