/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './profile';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from 'ionic-native/dist/es5/plugins/facebook';
import * as import5 from '@angular/core/src/linker/view_utils';
import * as import6 from '@angular/core/src/di/injector';
import * as import7 from '@angular/core/src/linker/view_type';
import * as import8 from '@angular/core/src/change_detection/change_detection';
import * as import9 from 'ionic-angular/navigation/nav-controller';
import * as import10 from 'ionic-angular/navigation/nav-params';
import * as import11 from 'ionic-angular/components/app/app';
import * as import12 from 'ionic-angular/components/alert/alert';
import * as import13 from 'ionic-angular/util/events';
import * as import14 from '@angular/http/src/http';
import * as import15 from 'ionic-angular/components/loading/loading';
import * as import16 from '@angular/core/src/metadata/view';
import * as import17 from '@angular/core/src/linker/component_factory';
import * as import18 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import19 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import20 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import21 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import22 from '../../node_modules/ionic-angular/components/card/card.ngfactory';
import * as import23 from '../../node_modules/ionic-angular/components/icon/icon.ngfactory';
import * as import24 from '../../node_modules/ionic-angular/components/item/item.ngfactory';
import * as import25 from '@angular/core/src/linker/query_list';
import * as import26 from '../../node_modules/ionic-angular/components/datetime/datetime.ngfactory';
import * as import27 from '../../node_modules/@angular/forms/src/directives/ng_model.ngfactory';
import * as import28 from '../../node_modules/@angular/forms/src/directives/ng_control_status.ngfactory';
import * as import29 from '../../node_modules/ionic-angular/components/button/button.ngfactory';
import * as import30 from 'ionic-angular/config/config';
import * as import31 from '@angular/core/src/linker/element_ref';
import * as import32 from 'ionic-angular/navigation/view-controller';
import * as import33 from 'ionic-angular/components/toolbar/toolbar';
import * as import34 from 'ionic-angular/util/keyboard';
import * as import35 from '@angular/core/src/zone/ng_zone';
import * as import36 from 'ionic-angular/components/tabs/tabs';
import * as import37 from 'ionic-angular/util/form';
import * as import38 from 'ionic-angular/components/item/item-reorder';
import * as import39 from 'ionic-angular/components/picker/picker';
import * as import40 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import41 from 'ionic-angular/components/navbar/navbar';
import * as import42 from 'ionic-angular/components/icon/icon';
import * as import43 from 'ionic-angular/components/item/item';
import * as import44 from 'ionic-angular/components/datetime/datetime';
import * as import45 from '@angular/forms/src/directives/control_value_accessor';
import * as import46 from '@angular/forms/src/directives/ng_model';
import * as import47 from '@angular/forms/src/directives/ng_control';
import * as import48 from '@angular/forms/src/directives/ng_control_status';
import * as import49 from 'ionic-angular/components/card/card';
import * as import50 from 'ionic-angular/components/button/button';
import * as import51 from 'ionic-angular/components/content/content';
import * as import52 from '@angular/core/src/security';
export class Wrapper_ProfilePage {
  context:import0.ProfilePage;
  changed:boolean;
  constructor(p0:any,p1:any,p2:any,p3:any,p4:any,p5:any,p6:any) {
    this.changed = false;
    this.context = new import0.ProfilePage(p0,p1,p2,p3,p4,p5,p6);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    if (!throwOnChange) { if ((view.numberOfChecks === 0)) { this.context.ngOnInit(); } }
    return changed;
  }
}
var renderType_ProfilePage_Host:import2.RenderComponentType = (null as any);
class _View_ProfilePage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _ProfilePage_0_4:Wrapper_ProfilePage;
  __Facebook_0_5:import4.Facebook;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_ProfilePage_Host0,renderType_ProfilePage_Host,import7.ViewType.HOST,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  get _Facebook_0_5():import4.Facebook {
    if ((this.__Facebook_0_5 == (null as any))) { (this.__Facebook_0_5 = new import4.Facebook()); }
    return this.__Facebook_0_5;
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-profile',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_ProfilePage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._ProfilePage_0_4 = new Wrapper_ProfilePage(this.parentInjector.get(import9.NavController),this.parentInjector.get(import10.NavParams),this.parentInjector.get(import11.App),this.parentInjector.get(import12.AlertController),this.parentInjector.get(import13.Events),this.parentInjector.get(import14.Http),this.parentInjector.get(import15.LoadingController));
    this._appEl_0.initComponent(this._ProfilePage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._ProfilePage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.ProfilePage) && (0 === requestNodeIndex))) { return this._ProfilePage_0_4.context; }
    if (((token === import4.Facebook) && (0 === requestNodeIndex))) { return this._Facebook_0_5; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._ProfilePage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_ProfilePage_Host0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_ProfilePage_Host === (null as any))) { (renderType_ProfilePage_Host = viewUtils.createRenderComponentType('',0,import16.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_ProfilePage_Host0(viewUtils,parentInjector,declarationEl);
}
export const ProfilePageNgFactory:import17.ComponentFactory<import0.ProfilePage> = new import17.ComponentFactory<import0.ProfilePage>('page-profile',viewFactory_ProfilePage_Host0,import0.ProfilePage);
const styles_ProfilePage:any[] = ([] as any[]);
var renderType_ProfilePage:import2.RenderComponentType = (null as any);
class _View_ProfilePage0 extends import1.AppView<import0.ProfilePage> {
  _el_0:any;
  _Header_0_3:import18.Wrapper_Header;
  _text_1:any;
  _el_2:any;
  /*private*/ _appEl_2:import3.AppElement;
  _Navbar_2_4:import19.Wrapper_Navbar;
  _text_3:any;
  _el_4:any;
  /*private*/ _appEl_4:import3.AppElement;
  _ToolbarTitle_4_4:import20.Wrapper_ToolbarTitle;
  _text_5:any;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _el_9:any;
  /*private*/ _appEl_9:import3.AppElement;
  _Content_9_4:import21.Wrapper_Content;
  _text_10:any;
  _el_11:any;
  _text_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _Card_16_3:import22.Wrapper_Card;
  _text_17:any;
  _el_18:any;
  _CardContent_18_3:import22.Wrapper_CardContent;
  _text_19:any;
  _el_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _el_24:any;
  _Icon_24_3:import23.Wrapper_Icon;
  _text_25:any;
  _text_26:any;
  _el_27:any;
  _text_28:any;
  _el_29:any;
  /*private*/ _appEl_29:import3.AppElement;
  _Item_29_4:import24.Wrapper_Item;
  _ItemContent_29_5:import24.Wrapper_ItemContent;
  _query_Label_29_0:import25.QueryList<any>;
  _query_Button_29_1:import25.QueryList<any>;
  _query_Icon_29_2:import25.QueryList<any>;
  _text_30:any;
  _el_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _text_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _el_44:any;
  _Icon_44_3:import23.Wrapper_Icon;
  _text_45:any;
  _el_46:any;
  /*private*/ _appEl_46:import3.AppElement;
  _Item_46_4:import24.Wrapper_Item;
  _ItemContent_46_5:import24.Wrapper_ItemContent;
  _query_Label_46_0:import25.QueryList<any>;
  _query_Button_46_1:import25.QueryList<any>;
  _query_Icon_46_2:import25.QueryList<any>;
  _text_47:any;
  _el_48:any;
  /*private*/ _appEl_48:import3.AppElement;
  _DateTime_48_4:import26.Wrapper_DateTime;
  _NG_VALUE_ACCESSOR_48_5:any[];
  _NgModel_48_6:import27.Wrapper_NgModel;
  _NgControl_48_7:any;
  _NgControlStatus_48_8:import28.Wrapper_NgControlStatus;
  _text_49:any;
  _text_50:any;
  _text_51:any;
  _text_52:any;
  _text_53:any;
  _text_54:any;
  _el_55:any;
  _Card_55_3:import22.Wrapper_Card;
  _text_56:any;
  _el_57:any;
  _CardContent_57_3:import22.Wrapper_CardContent;
  _text_58:any;
  _el_59:any;
  _Icon_59_3:import23.Wrapper_Icon;
  _text_60:any;
  _el_61:any;
  /*private*/ _appEl_61:import3.AppElement;
  _Item_61_4:import24.Wrapper_Item;
  _ItemContent_61_5:import24.Wrapper_ItemContent;
  _query_Label_61_0:import25.QueryList<any>;
  _query_Button_61_1:import25.QueryList<any>;
  _query_Icon_61_2:import25.QueryList<any>;
  _text_62:any;
  _el_63:any;
  _text_64:any;
  _el_65:any;
  _text_66:any;
  _text_67:any;
  _el_68:any;
  _text_69:any;
  _text_70:any;
  _text_71:any;
  _text_72:any;
  _text_73:any;
  _text_74:any;
  _el_75:any;
  _Card_75_3:import22.Wrapper_Card;
  _text_76:any;
  _el_77:any;
  _CardContent_77_3:import22.Wrapper_CardContent;
  _text_78:any;
  _el_79:any;
  _Icon_79_3:import23.Wrapper_Icon;
  _text_80:any;
  _el_81:any;
  /*private*/ _appEl_81:import3.AppElement;
  _Item_81_4:import24.Wrapper_Item;
  _ItemContent_81_5:import24.Wrapper_ItemContent;
  _query_Label_81_0:import25.QueryList<any>;
  _query_Button_81_1:import25.QueryList<any>;
  _query_Icon_81_2:import25.QueryList<any>;
  _text_82:any;
  _el_83:any;
  _text_84:any;
  _el_85:any;
  _text_86:any;
  _text_87:any;
  _el_88:any;
  _text_89:any;
  _text_90:any;
  _text_91:any;
  _text_92:any;
  _text_93:any;
  _text_94:any;
  _el_95:any;
  /*private*/ _appEl_95:import3.AppElement;
  _Button_95_4:import29.Wrapper_Button;
  _text_96:any;
  _text_97:any;
  _el_98:any;
  /*private*/ _appEl_98:import3.AppElement;
  _Button_98_4:import29.Wrapper_Button;
  _text_99:any;
  _text_100:any;
  _text_101:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  /*private*/ _expr_3:any;
  /*private*/ _expr_4:any;
  /*private*/ _expr_6:any;
  /*private*/ _expr_8:any;
  /*private*/ _expr_11:any;
  /*private*/ _expr_17:any;
  /*private*/ _expr_19:any;
  /*private*/ _expr_20:any;
  /*private*/ _expr_21:any;
  /*private*/ _expr_22:any;
  /*private*/ _expr_23:any;
  /*private*/ _expr_24:any;
  /*private*/ _expr_26:any;
  /*private*/ _expr_27:any;
  /*private*/ _expr_29:any;
  /*private*/ _expr_30:any;
  /*private*/ _expr_32:any;
  /*private*/ _expr_35:any;
  constructor(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement) {
    super(_View_ProfilePage0,renderType_ProfilePage,import7.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import8.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._el_0 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_0_3 = new import18.Wrapper_Header(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_0),this.renderer,this.parentInjector.get(import32.ViewController,(null as any)));
    this._text_1 = this.renderer.createText(this._el_0,'\n    ',(null as any));
    this._el_2 = this.renderer.createElement(this._el_0,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_2,'class','toolbar');
    this.renderer.setElementAttribute(this._el_2,'hideBackButton','');
    this._appEl_2 = new import3.AppElement(2,0,this,this._el_2);
    var compView_2:any = import19.viewFactory_Navbar0(this.viewUtils,this.injector(2),this._appEl_2);
    this._Navbar_2_4 = new import19.Wrapper_Navbar(this.parentInjector.get(import11.App),this.parentInjector.get(import32.ViewController,(null as any)),this.parentInjector.get(import9.NavController,(null as any)),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_2),this.renderer);
    this._appEl_2.initComponent(this._Navbar_2_4.context,([] as any[]),compView_2);
    this._text_3 = this.renderer.createText((null as any),'\n        ',(null as any));
    this._el_4 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_4 = new import3.AppElement(4,2,this,this._el_4);
    var compView_4:any = import20.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(4),this._appEl_4);
    this._ToolbarTitle_4_4 = new import20.Wrapper_ToolbarTitle(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_4),this.renderer,this.parentInjector.get(import33.Toolbar,(null as any)),this._Navbar_2_4.context);
    this._appEl_4.initComponent(this._ToolbarTitle_4_4.context,([] as any[]),compView_4);
    this._text_5 = this.renderer.createText((null as any),'Profile',(null as any));
    compView_4.create(this._ToolbarTitle_4_4.context,[([] as any[]).concat([this._text_5])],(null as any));
    this._text_6 = this.renderer.createText((null as any),'\n    ',(null as any));
    compView_2.create(this._Navbar_2_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_3,
        this._el_4,
        this._text_6
      ]
      )
    ]
    ,(null as any));
    this._text_7 = this.renderer.createText(this._el_0,'\n',(null as any));
    this._text_8 = this.renderer.createText(parentRenderNode,'\n\n',(null as any));
    this._el_9 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_9,'padding','');
    this._appEl_9 = new import3.AppElement(9,(null as any),this,this._el_9);
    var compView_9:any = import21.viewFactory_Content0(this.viewUtils,this.injector(9),this._appEl_9);
    this._Content_9_4 = new import21.Wrapper_Content(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_9),this.renderer,this.parentInjector.get(import11.App),this.parentInjector.get(import34.Keyboard),this.parentInjector.get(import35.NgZone),this.parentInjector.get(import32.ViewController,(null as any)),this.parentInjector.get(import36.Tabs,(null as any)));
    this._appEl_9.initComponent(this._Content_9_4.context,([] as any[]),compView_9);
    this._text_10 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_11 = this.renderer.createElement((null as any),'div',(null as any));
    this.renderer.setElementAttribute(this._el_11,'class','profile-img-wrapper');
    this._text_12 = this.renderer.createText(this._el_11,'\n        ',(null as any));
    this._el_13 = this.renderer.createElement(this._el_11,'img',(null as any));
    this.renderer.setElementAttribute(this._el_13,'class','profile-img');
    this.renderer.setElementAttribute(this._el_13,'id','profile_image');
    this._text_14 = this.renderer.createText(this._el_11,'\n    ',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_16_3 = new import22.Wrapper_Card(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_16),this.renderer);
    this._text_17 = this.renderer.createText(this._el_16,'\n        ',(null as any));
    this._el_18 = this.renderer.createElement(this._el_16,'ion-card-content',(null as any));
    this.renderer.setElementAttribute(this._el_18,'class','field-with-icon birthdate');
    this._CardContent_18_3 = new import22.Wrapper_CardContent(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_18),this.renderer);
    this._text_19 = this.renderer.createText(this._el_18,'\n            ',(null as any));
    this._el_20 = this.renderer.createElement(this._el_18,'div',(null as any));
    this.renderer.setElementAttribute(this._el_20,'class','row');
    this._text_21 = this.renderer.createText(this._el_20,'\n              ',(null as any));
    this._el_22 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_22,'class','col col-10');
    this._text_23 = this.renderer.createText(this._el_22,'\n                ',(null as any));
    this._el_24 = this.renderer.createElement(this._el_22,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_24,'class','medium');
    this.renderer.setElementAttribute(this._el_24,'name','ios-calendar-outline');
    this.renderer.setElementAttribute(this._el_24,'role','img');
    this._Icon_24_3 = new import23.Wrapper_Icon(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_24),this.renderer);
    this._text_25 = this.renderer.createText(this._el_22,'\n              ',(null as any));
    this._text_26 = this.renderer.createText(this._el_20,'\n              ',(null as any));
    this._el_27 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_27,'class','col col-80 birthday-selector');
    this._text_28 = this.renderer.createText(this._el_27,'\n                ',(null as any));
    this._el_29 = this.renderer.createElement(this._el_27,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_29,'class','item item-block');
    this._appEl_29 = new import3.AppElement(29,27,this,this._el_29);
    var compView_29:any = import24.viewFactory_Item0(this.viewUtils,this.injector(29),this._appEl_29);
    this._Item_29_4 = new import24.Wrapper_Item(this.parentInjector.get(import37.Form),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_29),this.renderer,this.parentInjector.get(import38.ItemReorder,(null as any)));
    this._ItemContent_29_5 = new import24.Wrapper_ItemContent();
    this._query_Label_29_0 = new import25.QueryList<any>();
    this._query_Button_29_1 = new import25.QueryList<any>();
    this._query_Icon_29_2 = new import25.QueryList<any>();
    this._appEl_29.initComponent(this._Item_29_4.context,([] as any[]),compView_29);
    this._text_30 = this.renderer.createText((null as any),'\n                  ',(null as any));
    this._el_31 = this.renderer.createElement((null as any),'label',(null as any));
    this.renderer.setElementAttribute(this._el_31,'class','item item-input');
    this._text_32 = this.renderer.createText(this._el_31,'\n                    ',(null as any));
    this._el_33 = this.renderer.createElement(this._el_31,'span',(null as any));
    this.renderer.setElementAttribute(this._el_33,'class','input-label');
    this._text_34 = this.renderer.createText(this._el_33,'Birthday : ',(null as any));
    this._text_35 = this.renderer.createText(this._el_31,'\n                    ',(null as any));
    this._el_36 = this.renderer.createElement(this._el_31,'span',(null as any));
    this.renderer.setElementAttribute(this._el_36,'class','input-data');
    this._text_37 = this.renderer.createText(this._el_36,'',(null as any));
    this._text_38 = this.renderer.createText(this._el_31,'\n                  ',(null as any));
    this._text_39 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._query_Label_29_0.reset(([] as any[]));
    this._Item_29_4.context.contentLabel = this._query_Label_29_0.first;
    compView_29.create(this._Item_29_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_30,
        this._el_31,
        this._text_39
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_40 = this.renderer.createText(this._el_27,'\n              ',(null as any));
    this._text_41 = this.renderer.createText(this._el_20,'\n              ',(null as any));
    this._el_42 = this.renderer.createElement(this._el_20,'div',(null as any));
    this.renderer.setElementAttribute(this._el_42,'class','col col-10');
    this._text_43 = this.renderer.createText(this._el_42,'\n                ',(null as any));
    this._el_44 = this.renderer.createElement(this._el_42,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_44,'class','medium pink-color');
    this.renderer.setElementAttribute(this._el_44,'name','md-create');
    this.renderer.setElementAttribute(this._el_44,'role','img');
    this._Icon_44_3 = new import23.Wrapper_Icon(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_44),this.renderer);
    this._text_45 = this.renderer.createText(this._el_42,'\n                ',(null as any));
    this._el_46 = this.renderer.createElement(this._el_42,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_46,'class','item item-block');
    this.renderer.setElementAttribute(this._el_46,'hidden','true');
    this.renderer.setElementAttribute(this._el_46,'no-lines','');
    this._appEl_46 = new import3.AppElement(46,42,this,this._el_46);
    var compView_46:any = import24.viewFactory_Item0(this.viewUtils,this.injector(46),this._appEl_46);
    this._Item_46_4 = new import24.Wrapper_Item(this.parentInjector.get(import37.Form),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_46),this.renderer,this.parentInjector.get(import38.ItemReorder,(null as any)));
    this._ItemContent_46_5 = new import24.Wrapper_ItemContent();
    this._query_Label_46_0 = new import25.QueryList<any>();
    this._query_Button_46_1 = new import25.QueryList<any>();
    this._query_Icon_46_2 = new import25.QueryList<any>();
    this._appEl_46.initComponent(this._Item_46_4.context,([] as any[]),compView_46);
    this._text_47 = this.renderer.createText((null as any),'\n                    ',(null as any));
    this._el_48 = this.renderer.createElement((null as any),'ion-datetime',(null as any));
    this.renderer.setElementAttribute(this._el_48,'displayFormat','DD MMM, YYYY');
    this.renderer.setElementAttribute(this._el_48,'text-center','');
    this._appEl_48 = new import3.AppElement(48,46,this,this._el_48);
    var compView_48:any = import26.viewFactory_DateTime0(this.viewUtils,this.injector(48),this._appEl_48);
    this._DateTime_48_4 = new import26.Wrapper_DateTime(this.parentInjector.get(import37.Form),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_48),this.renderer,this._Item_46_4.context,this.parentInjector.get(import39.PickerController,(null as any)));
    this._NG_VALUE_ACCESSOR_48_5 = [this._DateTime_48_4.context];
    this._NgModel_48_6 = new import27.Wrapper_NgModel((null as any),(null as any),(null as any),this._NG_VALUE_ACCESSOR_48_5);
    this._NgControl_48_7 = this._NgModel_48_6.context;
    this._NgControlStatus_48_8 = new import28.Wrapper_NgControlStatus(this._NgControl_48_7);
    this._appEl_48.initComponent(this._DateTime_48_4.context,([] as any[]),compView_48);
    compView_48.create(this._DateTime_48_4.context,([] as any[]),(null as any));
    this._text_49 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._query_Label_46_0.reset(([] as any[]));
    this._Item_46_4.context.contentLabel = this._query_Label_46_0.first;
    compView_46.create(this._Item_46_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_47,
        this._text_49
      ]
      ),
      ([] as any[]).concat([this._el_48]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_50 = this.renderer.createText(this._el_42,'\n              ',(null as any));
    this._text_51 = this.renderer.createText(this._el_20,'\n            ',(null as any));
    this._text_52 = this.renderer.createText(this._el_18,'\n        ',(null as any));
    this._text_53 = this.renderer.createText(this._el_16,'\n    ',(null as any));
    this._text_54 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_55 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_55_3 = new import22.Wrapper_Card(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_55),this.renderer);
    this._text_56 = this.renderer.createText(this._el_55,'\n        ',(null as any));
    this._el_57 = this.renderer.createElement(this._el_55,'ion-card-content',(null as any));
    this.renderer.setElementAttribute(this._el_57,'class','field-with-icon');
    this._CardContent_57_3 = new import22.Wrapper_CardContent(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_57),this.renderer);
    this._text_58 = this.renderer.createText(this._el_57,'\n            ',(null as any));
    this._el_59 = this.renderer.createElement(this._el_57,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_59,'class','medium');
    this.renderer.setElementAttribute(this._el_59,'name','ios-mail-outline');
    this.renderer.setElementAttribute(this._el_59,'role','img');
    this._Icon_59_3 = new import23.Wrapper_Icon(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_59),this.renderer);
    this._text_60 = this.renderer.createText(this._el_57,'\n            ',(null as any));
    this._el_61 = this.renderer.createElement(this._el_57,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_61,'class','item item-block');
    this._appEl_61 = new import3.AppElement(61,57,this,this._el_61);
    var compView_61:any = import24.viewFactory_Item0(this.viewUtils,this.injector(61),this._appEl_61);
    this._Item_61_4 = new import24.Wrapper_Item(this.parentInjector.get(import37.Form),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_61),this.renderer,this.parentInjector.get(import38.ItemReorder,(null as any)));
    this._ItemContent_61_5 = new import24.Wrapper_ItemContent();
    this._query_Label_61_0 = new import25.QueryList<any>();
    this._query_Button_61_1 = new import25.QueryList<any>();
    this._query_Icon_61_2 = new import25.QueryList<any>();
    this._appEl_61.initComponent(this._Item_61_4.context,([] as any[]),compView_61);
    this._text_62 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_63 = this.renderer.createElement((null as any),'label',(null as any));
    this.renderer.setElementAttribute(this._el_63,'class','item item-input');
    this._text_64 = this.renderer.createText(this._el_63,'\n                ',(null as any));
    this._el_65 = this.renderer.createElement(this._el_63,'span',(null as any));
    this.renderer.setElementAttribute(this._el_65,'class','input-label');
    this._text_66 = this.renderer.createText(this._el_65,'Email : ',(null as any));
    this._text_67 = this.renderer.createText(this._el_63,'\n                ',(null as any));
    this._el_68 = this.renderer.createElement(this._el_63,'span',(null as any));
    this.renderer.setElementAttribute(this._el_68,'class','input-data');
    this._text_69 = this.renderer.createText(this._el_68,'',(null as any));
    this._text_70 = this.renderer.createText(this._el_63,'\n              ',(null as any));
    this._text_71 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_61_0.reset(([] as any[]));
    this._Item_61_4.context.contentLabel = this._query_Label_61_0.first;
    compView_61.create(this._Item_61_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_62,
        this._el_63,
        this._text_71
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_72 = this.renderer.createText(this._el_57,'\n        ',(null as any));
    this._text_73 = this.renderer.createText(this._el_55,'\n    ',(null as any));
    this._text_74 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_75 = this.renderer.createElement((null as any),'ion-card',(null as any));
    this._Card_75_3 = new import22.Wrapper_Card(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_75),this.renderer);
    this._text_76 = this.renderer.createText(this._el_75,'\n        ',(null as any));
    this._el_77 = this.renderer.createElement(this._el_75,'ion-card-content',(null as any));
    this.renderer.setElementAttribute(this._el_77,'class','field-with-icon');
    this._CardContent_77_3 = new import22.Wrapper_CardContent(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_77),this.renderer);
    this._text_78 = this.renderer.createText(this._el_77,'\n            ',(null as any));
    this._el_79 = this.renderer.createElement(this._el_77,'ion-icon',(null as any));
    this.renderer.setElementAttribute(this._el_79,'class','medium');
    this.renderer.setElementAttribute(this._el_79,'name','ios-person-outline');
    this.renderer.setElementAttribute(this._el_79,'role','img');
    this._Icon_79_3 = new import23.Wrapper_Icon(this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_79),this.renderer);
    this._text_80 = this.renderer.createText(this._el_77,'\n            ',(null as any));
    this._el_81 = this.renderer.createElement(this._el_77,'ion-item',(null as any));
    this.renderer.setElementAttribute(this._el_81,'class','item item-block');
    this._appEl_81 = new import3.AppElement(81,77,this,this._el_81);
    var compView_81:any = import24.viewFactory_Item0(this.viewUtils,this.injector(81),this._appEl_81);
    this._Item_81_4 = new import24.Wrapper_Item(this.parentInjector.get(import37.Form),this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_81),this.renderer,this.parentInjector.get(import38.ItemReorder,(null as any)));
    this._ItemContent_81_5 = new import24.Wrapper_ItemContent();
    this._query_Label_81_0 = new import25.QueryList<any>();
    this._query_Button_81_1 = new import25.QueryList<any>();
    this._query_Icon_81_2 = new import25.QueryList<any>();
    this._appEl_81.initComponent(this._Item_81_4.context,([] as any[]),compView_81);
    this._text_82 = this.renderer.createText((null as any),'\n                ',(null as any));
    this._el_83 = this.renderer.createElement((null as any),'label',(null as any));
    this.renderer.setElementAttribute(this._el_83,'class','item item-input');
    this._text_84 = this.renderer.createText(this._el_83,'\n                  ',(null as any));
    this._el_85 = this.renderer.createElement(this._el_83,'span',(null as any));
    this.renderer.setElementAttribute(this._el_85,'class','input-label');
    this._text_86 = this.renderer.createText(this._el_85,'Name : ',(null as any));
    this._text_87 = this.renderer.createText(this._el_83,'\n                  ',(null as any));
    this._el_88 = this.renderer.createElement(this._el_83,'span',(null as any));
    this.renderer.setElementAttribute(this._el_88,'class','input-data');
    this._text_89 = this.renderer.createText(this._el_88,'',(null as any));
    this._text_90 = this.renderer.createText(this._el_83,'\n              ',(null as any));
    this._text_91 = this.renderer.createText((null as any),'\n            ',(null as any));
    this._query_Label_81_0.reset(([] as any[]));
    this._Item_81_4.context.contentLabel = this._query_Label_81_0.first;
    compView_81.create(this._Item_81_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_82,
        this._el_83,
        this._text_91
      ]
      ),
      ([] as any[]),
      ([] as any[])
    ]
    ,(null as any));
    this._text_92 = this.renderer.createText(this._el_77,'\n        ',(null as any));
    this._text_93 = this.renderer.createText(this._el_75,'\n    ',(null as any));
    this._text_94 = this.renderer.createText((null as any),'\n\n    ',(null as any));
    this._el_95 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_95,'block','');
    this.renderer.setElementAttribute(this._el_95,'class','primary-btn');
    this.renderer.setElementAttribute(this._el_95,'ion-button','');
    this._appEl_95 = new import3.AppElement(95,9,this,this._el_95);
    var compView_95:any = import29.viewFactory_Button0(this.viewUtils,this.injector(95),this._appEl_95);
    this._Button_95_4 = new import29.Wrapper_Button((null as any),'',this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_95),this.renderer);
    this._appEl_95.initComponent(this._Button_95_4.context,([] as any[]),compView_95);
    this._text_96 = this.renderer.createText((null as any),'Save',(null as any));
    compView_95.create(this._Button_95_4.context,[([] as any[]).concat([this._text_96])],(null as any));
    this._text_97 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_98 = this.renderer.createElement((null as any),'button',(null as any));
    this.renderer.setElementAttribute(this._el_98,'block','');
    this.renderer.setElementAttribute(this._el_98,'class','logout-btn');
    this.renderer.setElementAttribute(this._el_98,'ion-button','');
    this._appEl_98 = new import3.AppElement(98,9,this,this._el_98);
    var compView_98:any = import29.viewFactory_Button0(this.viewUtils,this.injector(98),this._appEl_98);
    this._Button_98_4 = new import29.Wrapper_Button((null as any),'',this.parentInjector.get(import30.Config),new import31.ElementRef(this._el_98),this.renderer);
    this._appEl_98.initComponent(this._Button_98_4.context,([] as any[]),compView_98);
    this._text_99 = this.renderer.createText((null as any),'Logout',(null as any));
    compView_98.create(this._Button_98_4.context,[([] as any[]).concat([this._text_99])],(null as any));
    this._text_100 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_9.create(this._Content_9_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_10,
        this._el_11,
        this._text_15,
        this._el_16,
        this._text_54,
        this._el_55,
        this._text_74,
        this._el_75,
        this._text_94,
        this._el_95,
        this._text_97,
        this._el_98,
        this._text_100
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_101 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_1 = import8.UNINITIALIZED;
    this._expr_2 = import8.UNINITIALIZED;
    this._expr_3 = import8.UNINITIALIZED;
    this._expr_4 = import8.UNINITIALIZED;
    this._expr_6 = import8.UNINITIALIZED;
    var disposable_0:Function = this.renderer.listen(this._el_27,'click',this.eventHandler(this._handle_click_27_0.bind(this)));
    this._expr_8 = import8.UNINITIALIZED;
    var disposable_1:Function = this.renderer.listen(this._el_42,'click',this.eventHandler(this._handle_click_42_0.bind(this)));
    this._expr_11 = import8.UNINITIALIZED;
    var disposable_2:Function = this.renderer.listen(this._el_48,'ionChange',this.eventHandler(this._handle_ionChange_48_0.bind(this)));
    var disposable_3:Function = this.renderer.listen(this._el_48,'ngModelChange',this.eventHandler(this._handle_ngModelChange_48_1.bind(this)));
    var disposable_4:Function = this.renderer.listen(this._el_48,'click',this.eventHandler(this._handle_click_48_2.bind(this)));
    var disposable_5:Function = this.renderer.listen(this._el_48,'keyup.space',this.eventHandler(this._handle_keyup_space_48_3.bind(this)));
    this._expr_17 = import8.UNINITIALIZED;
    const subscription_0:any = this._DateTime_48_4.context.ionChange.subscribe(this.eventHandler(this._handle_ionChange_48_0.bind(this)));
    const subscription_1:any = this._NgModel_48_6.context.update.subscribe(this.eventHandler(this._handle_ngModelChange_48_1.bind(this)));
    this._expr_19 = import8.UNINITIALIZED;
    this._expr_20 = import8.UNINITIALIZED;
    this._expr_21 = import8.UNINITIALIZED;
    this._expr_22 = import8.UNINITIALIZED;
    this._expr_23 = import8.UNINITIALIZED;
    this._expr_24 = import8.UNINITIALIZED;
    this._expr_26 = import8.UNINITIALIZED;
    this._expr_27 = import8.UNINITIALIZED;
    this._expr_29 = import8.UNINITIALIZED;
    this._expr_30 = import8.UNINITIALIZED;
    this._expr_32 = import8.UNINITIALIZED;
    var disposable_6:Function = this.renderer.listen(this._el_95,'click',this.eventHandler(this._handle_click_95_0.bind(this)));
    this._expr_35 = import8.UNINITIALIZED;
    var disposable_7:Function = this.renderer.listen(this._el_98,'click',this.eventHandler(this._handle_click_98_0.bind(this)));
    this.init(([] as any[]),[
      this._el_0,
      this._text_1,
      this._el_2,
      this._text_3,
      this._el_4,
      this._text_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._el_9,
      this._text_10,
      this._el_11,
      this._text_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._el_18,
      this._text_19,
      this._el_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._el_24,
      this._text_25,
      this._text_26,
      this._el_27,
      this._text_28,
      this._el_29,
      this._text_30,
      this._el_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._text_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._el_44,
      this._text_45,
      this._el_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._text_50,
      this._text_51,
      this._text_52,
      this._text_53,
      this._text_54,
      this._el_55,
      this._text_56,
      this._el_57,
      this._text_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._el_63,
      this._text_64,
      this._el_65,
      this._text_66,
      this._text_67,
      this._el_68,
      this._text_69,
      this._text_70,
      this._text_71,
      this._text_72,
      this._text_73,
      this._text_74,
      this._el_75,
      this._text_76,
      this._el_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._el_81,
      this._text_82,
      this._el_83,
      this._text_84,
      this._el_85,
      this._text_86,
      this._text_87,
      this._el_88,
      this._text_89,
      this._text_90,
      this._text_91,
      this._text_92,
      this._text_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._text_97,
      this._el_98,
      this._text_99,
      this._text_100,
      this._text_101
    ]
    ,[
      disposable_0,
      disposable_1,
      disposable_2,
      disposable_3,
      disposable_4,
      disposable_5,
      disposable_6,
      disposable_7
    ]
    ,[
      subscription_0,
      subscription_1
    ]
    );
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import40.ToolbarTitle) && ((4 <= requestNodeIndex) && (requestNodeIndex <= 5)))) { return this._ToolbarTitle_4_4.context; }
    if (((token === import41.Navbar) && ((2 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._Navbar_2_4.context; }
    if (((token === import33.Header) && ((0 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Header_0_3.context; }
    if (((token === import42.Icon) && (24 === requestNodeIndex))) { return this._Icon_24_3.context; }
    if (((token === import43.Item) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._Item_29_4.context; }
    if (((token === import43.ItemContent) && ((29 <= requestNodeIndex) && (requestNodeIndex <= 39)))) { return this._ItemContent_29_5.context; }
    if (((token === import42.Icon) && (44 === requestNodeIndex))) { return this._Icon_44_3.context; }
    if (((token === import44.DateTime) && (48 === requestNodeIndex))) { return this._DateTime_48_4.context; }
    if (((token === import45.NG_VALUE_ACCESSOR) && (48 === requestNodeIndex))) { return this._NG_VALUE_ACCESSOR_48_5; }
    if (((token === import46.NgModel) && (48 === requestNodeIndex))) { return this._NgModel_48_6.context; }
    if (((token === import47.NgControl) && (48 === requestNodeIndex))) { return this._NgControl_48_7; }
    if (((token === import48.NgControlStatus) && (48 === requestNodeIndex))) { return this._NgControlStatus_48_8.context; }
    if (((token === import43.Item) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._Item_46_4.context; }
    if (((token === import43.ItemContent) && ((46 <= requestNodeIndex) && (requestNodeIndex <= 49)))) { return this._ItemContent_46_5.context; }
    if (((token === import49.CardContent) && ((18 <= requestNodeIndex) && (requestNodeIndex <= 52)))) { return this._CardContent_18_3.context; }
    if (((token === import49.Card) && ((16 <= requestNodeIndex) && (requestNodeIndex <= 53)))) { return this._Card_16_3.context; }
    if (((token === import42.Icon) && (59 === requestNodeIndex))) { return this._Icon_59_3.context; }
    if (((token === import43.Item) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 71)))) { return this._Item_61_4.context; }
    if (((token === import43.ItemContent) && ((61 <= requestNodeIndex) && (requestNodeIndex <= 71)))) { return this._ItemContent_61_5.context; }
    if (((token === import49.CardContent) && ((57 <= requestNodeIndex) && (requestNodeIndex <= 72)))) { return this._CardContent_57_3.context; }
    if (((token === import49.Card) && ((55 <= requestNodeIndex) && (requestNodeIndex <= 73)))) { return this._Card_55_3.context; }
    if (((token === import42.Icon) && (79 === requestNodeIndex))) { return this._Icon_79_3.context; }
    if (((token === import43.Item) && ((81 <= requestNodeIndex) && (requestNodeIndex <= 91)))) { return this._Item_81_4.context; }
    if (((token === import43.ItemContent) && ((81 <= requestNodeIndex) && (requestNodeIndex <= 91)))) { return this._ItemContent_81_5.context; }
    if (((token === import49.CardContent) && ((77 <= requestNodeIndex) && (requestNodeIndex <= 92)))) { return this._CardContent_77_3.context; }
    if (((token === import49.Card) && ((75 <= requestNodeIndex) && (requestNodeIndex <= 93)))) { return this._Card_75_3.context; }
    if (((token === import50.Button) && ((95 <= requestNodeIndex) && (requestNodeIndex <= 96)))) { return this._Button_95_4.context; }
    if (((token === import50.Button) && ((98 <= requestNodeIndex) && (requestNodeIndex <= 99)))) { return this._Button_98_4.context; }
    if (((token === import51.Content) && ((9 <= requestNodeIndex) && (requestNodeIndex <= 100)))) { return this._Content_9_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_0_3.detectChangesInternal(this,this._el_0,throwOnChange);
    const currVal_0:any = '';
    this._Navbar_2_4.check_hideBackButton(currVal_0,throwOnChange,false);
    this._Navbar_2_4.detectChangesInternal(this,this._el_2,throwOnChange);
    if (this._ToolbarTitle_4_4.detectChangesInternal(this,this._el_4,throwOnChange)) { this._appEl_4.componentView.markAsCheckOnce(); }
    if (this._Content_9_4.detectChangesInternal(this,this._el_9,throwOnChange)) { this._appEl_9.componentView.markAsCheckOnce(); }
    this._Card_16_3.detectChangesInternal(this,this._el_16,throwOnChange);
    this._CardContent_18_3.detectChangesInternal(this,this._el_18,throwOnChange);
    const currVal_5:any = 'ios-calendar-outline';
    this._Icon_24_3.check_name(currVal_5,throwOnChange,false);
    this._Icon_24_3.detectChangesInternal(this,this._el_24,throwOnChange);
    if (this._Item_29_4.detectChangesInternal(this,this._el_29,throwOnChange)) { this._appEl_29.componentView.markAsCheckOnce(); }
    this._ItemContent_29_5.detectChangesInternal(this,this._el_29,throwOnChange);
    const currVal_10:any = 'md-create';
    this._Icon_44_3.check_name(currVal_10,throwOnChange,false);
    this._Icon_44_3.detectChangesInternal(this,this._el_44,throwOnChange);
    if (this._Item_46_4.detectChangesInternal(this,this._el_46,throwOnChange)) { this._appEl_46.componentView.markAsCheckOnce(); }
    this._ItemContent_46_5.detectChangesInternal(this,this._el_46,throwOnChange);
    const currVal_16:any = 'DD MMM, YYYY';
    this._DateTime_48_4.check_displayFormat(currVal_16,throwOnChange,false);
    this._DateTime_48_4.detectChangesInternal(this,this._el_48,throwOnChange);
    const currVal_18:any = this.context.date;
    this._NgModel_48_6.check_model(currVal_18,throwOnChange,false);
    this._NgModel_48_6.detectChangesInternal(this,this._el_48,throwOnChange);
    this._NgControlStatus_48_8.detectChangesInternal(this,this._el_48,throwOnChange);
    this._Card_55_3.detectChangesInternal(this,this._el_55,throwOnChange);
    this._CardContent_57_3.detectChangesInternal(this,this._el_57,throwOnChange);
    const currVal_25:any = 'ios-mail-outline';
    this._Icon_59_3.check_name(currVal_25,throwOnChange,false);
    this._Icon_59_3.detectChangesInternal(this,this._el_59,throwOnChange);
    if (this._Item_61_4.detectChangesInternal(this,this._el_61,throwOnChange)) { this._appEl_61.componentView.markAsCheckOnce(); }
    this._ItemContent_61_5.detectChangesInternal(this,this._el_61,throwOnChange);
    this._Card_75_3.detectChangesInternal(this,this._el_75,throwOnChange);
    this._CardContent_77_3.detectChangesInternal(this,this._el_77,throwOnChange);
    const currVal_28:any = 'ios-person-outline';
    this._Icon_79_3.check_name(currVal_28,throwOnChange,false);
    this._Icon_79_3.detectChangesInternal(this,this._el_79,throwOnChange);
    if (this._Item_81_4.detectChangesInternal(this,this._el_81,throwOnChange)) { this._appEl_81.componentView.markAsCheckOnce(); }
    this._ItemContent_81_5.detectChangesInternal(this,this._el_81,throwOnChange);
    const currVal_33:any = '';
    this._Button_95_4.check_block(currVal_33,throwOnChange,false);
    if (this._Button_95_4.detectChangesInternal(this,this._el_95,throwOnChange)) { this._appEl_95.componentView.markAsCheckOnce(); }
    const currVal_36:any = '';
    this._Button_98_4.check_block(currVal_36,throwOnChange,false);
    if (this._Button_98_4.detectChangesInternal(this,this._el_98,throwOnChange)) { this._appEl_98.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    if (!throwOnChange) {
      if (this._query_Button_29_1.dirty) {
        this._query_Button_29_1.reset(([] as any[]));
        this._Item_29_4.context._buttons = this._query_Button_29_1;
        this._query_Button_29_1.notifyOnChanges();
      }
      if (this._query_Icon_29_2.dirty) {
        this._query_Icon_29_2.reset(([] as any[]));
        this._Item_29_4.context._icons = this._query_Icon_29_2;
        this._query_Icon_29_2.notifyOnChanges();
      }
      if (this._query_Button_46_1.dirty) {
        this._query_Button_46_1.reset(([] as any[]));
        this._Item_46_4.context._buttons = this._query_Button_46_1;
        this._query_Button_46_1.notifyOnChanges();
      }
      if (this._query_Icon_46_2.dirty) {
        this._query_Icon_46_2.reset(([] as any[]));
        this._Item_46_4.context._icons = this._query_Icon_46_2;
        this._query_Icon_46_2.notifyOnChanges();
      }
      if (this._query_Button_61_1.dirty) {
        this._query_Button_61_1.reset(([] as any[]));
        this._Item_61_4.context._buttons = this._query_Button_61_1;
        this._query_Button_61_1.notifyOnChanges();
      }
      if (this._query_Icon_61_2.dirty) {
        this._query_Icon_61_2.reset(([] as any[]));
        this._Item_61_4.context._icons = this._query_Icon_61_2;
        this._query_Icon_61_2.notifyOnChanges();
      }
      if (this._query_Button_81_1.dirty) {
        this._query_Button_81_1.reset(([] as any[]));
        this._Item_81_4.context._buttons = this._query_Button_81_1;
        this._query_Button_81_1.notifyOnChanges();
      }
      if (this._query_Icon_81_2.dirty) {
        this._query_Icon_81_2.reset(([] as any[]));
        this._Item_81_4.context._icons = this._query_Icon_81_2;
        this._query_Icon_81_2.notifyOnChanges();
      }
      if ((this.numberOfChecks === 0)) { this._Item_29_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._DateTime_48_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_46_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_61_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Item_81_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_95_4.context.ngAfterContentInit(); }
      if ((this.numberOfChecks === 0)) { this._Button_98_4.context.ngAfterContentInit(); }
    }
    const currVal_1:any = this._Navbar_2_4.context._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementProperty(this._el_2,'hidden',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Navbar_2_4.context._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_2,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    const currVal_3:any = this._Content_9_4.context._sbPadding;
    if (import5.checkBinding(throwOnChange,this._expr_3,currVal_3)) {
      this.renderer.setElementClass(this._el_9,'statusbar-padding',currVal_3);
      this._expr_3 = currVal_3;
    }
    const currVal_4:any = import5.interpolate(1,'',this.context.image,'');
    if (import5.checkBinding(throwOnChange,this._expr_4,currVal_4)) {
      this.renderer.setElementProperty(this._el_13,'src',this.viewUtils.sanitizer.sanitize(import52.SecurityContext.URL,currVal_4));
      this._expr_4 = currVal_4;
    }
    const currVal_6:any = this._Icon_24_3.context._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_6,currVal_6)) {
      this.renderer.setElementClass(this._el_24,'hide',currVal_6);
      this._expr_6 = currVal_6;
    }
    const currVal_8:any = import5.interpolate(3,' ',this.context.day,' ',this.context.month,' ',this.context.year,' ');
    if (import5.checkBinding(throwOnChange,this._expr_8,currVal_8)) {
      this.renderer.setText(this._text_37,currVal_8);
      this._expr_8 = currVal_8;
    }
    const currVal_11:any = this._Icon_44_3.context._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_11,currVal_11)) {
      this.renderer.setElementClass(this._el_44,'hide',currVal_11);
      this._expr_11 = currVal_11;
    }
    const currVal_17:any = this._DateTime_48_4.context._disabled;
    if (import5.checkBinding(throwOnChange,this._expr_17,currVal_17)) {
      this.renderer.setElementClass(this._el_48,'datetime-disabled',currVal_17);
      this._expr_17 = currVal_17;
    }
    const currVal_19:any = this._NgControlStatus_48_8.context.ngClassUntouched;
    if (import5.checkBinding(throwOnChange,this._expr_19,currVal_19)) {
      this.renderer.setElementClass(this._el_48,'ng-untouched',currVal_19);
      this._expr_19 = currVal_19;
    }
    const currVal_20:any = this._NgControlStatus_48_8.context.ngClassTouched;
    if (import5.checkBinding(throwOnChange,this._expr_20,currVal_20)) {
      this.renderer.setElementClass(this._el_48,'ng-touched',currVal_20);
      this._expr_20 = currVal_20;
    }
    const currVal_21:any = this._NgControlStatus_48_8.context.ngClassPristine;
    if (import5.checkBinding(throwOnChange,this._expr_21,currVal_21)) {
      this.renderer.setElementClass(this._el_48,'ng-pristine',currVal_21);
      this._expr_21 = currVal_21;
    }
    const currVal_22:any = this._NgControlStatus_48_8.context.ngClassDirty;
    if (import5.checkBinding(throwOnChange,this._expr_22,currVal_22)) {
      this.renderer.setElementClass(this._el_48,'ng-dirty',currVal_22);
      this._expr_22 = currVal_22;
    }
    const currVal_23:any = this._NgControlStatus_48_8.context.ngClassValid;
    if (import5.checkBinding(throwOnChange,this._expr_23,currVal_23)) {
      this.renderer.setElementClass(this._el_48,'ng-valid',currVal_23);
      this._expr_23 = currVal_23;
    }
    const currVal_24:any = this._NgControlStatus_48_8.context.ngClassInvalid;
    if (import5.checkBinding(throwOnChange,this._expr_24,currVal_24)) {
      this.renderer.setElementClass(this._el_48,'ng-invalid',currVal_24);
      this._expr_24 = currVal_24;
    }
    const currVal_26:any = this._Icon_59_3.context._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_26,currVal_26)) {
      this.renderer.setElementClass(this._el_59,'hide',currVal_26);
      this._expr_26 = currVal_26;
    }
    const currVal_27:any = import5.interpolate(1,'',this.context.data.email,'');
    if (import5.checkBinding(throwOnChange,this._expr_27,currVal_27)) {
      this.renderer.setText(this._text_69,currVal_27);
      this._expr_27 = currVal_27;
    }
    const currVal_29:any = this._Icon_79_3.context._hidden;
    if (import5.checkBinding(throwOnChange,this._expr_29,currVal_29)) {
      this.renderer.setElementClass(this._el_79,'hide',currVal_29);
      this._expr_29 = currVal_29;
    }
    const currVal_30:any = import5.interpolate(1,'',this.context.data.name,'');
    if (import5.checkBinding(throwOnChange,this._expr_30,currVal_30)) {
      this.renderer.setText(this._text_89,currVal_30);
      this._expr_30 = currVal_30;
    }
    const currVal_32:any = this.context.disableSubmit;
    if (import5.checkBinding(throwOnChange,this._expr_32,currVal_32)) {
      this.renderer.setElementProperty(this._el_95,'disabled',currVal_32);
      this._expr_32 = currVal_32;
    }
    const currVal_35:any = this.context.disableSubmit;
    if (import5.checkBinding(throwOnChange,this._expr_35,currVal_35)) {
      this.renderer.setElementProperty(this._el_98,'disabled',currVal_35);
      this._expr_35 = currVal_35;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_2_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Icon_24_3.context.ngOnDestroy();
    this._Icon_44_3.context.ngOnDestroy();
    this._DateTime_48_4.context.ngOnDestroy();
    this._NgModel_48_6.context.ngOnDestroy();
    this._Icon_59_3.context.ngOnDestroy();
    this._Icon_79_3.context.ngOnDestroy();
    this._Content_9_4.context.ngOnDestroy();
  }
  private _handle_click_27_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_48_4.context.open()) !== false);
    return (true && pd_0);
  }
  private _handle_click_42_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_48_4.context.open()) !== false);
    return (true && pd_0);
  }
  private _handle_ionChange_48_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.dateChanged($event)) !== false);
    return (true && pd_0);
  }
  private _handle_ngModelChange_48_1($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>(this.context.date = $event)) !== false);
    return (true && pd_0);
  }
  private _handle_click_48_2($event:any):boolean {
    this._appEl_48.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_48_4.context._click($event)) !== false);
    return (true && pd_0);
  }
  private _handle_keyup_space_48_3($event:any):boolean {
    this._appEl_48.componentView.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this._DateTime_48_4.context._keyup()) !== false);
    return (true && pd_0);
  }
  private _handle_click_95_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.submit()) !== false);
    return (true && pd_0);
  }
  private _handle_click_98_0($event:any):boolean {
    this.markPathToRootAsCheckOnce();
    const pd_0:any = ((<any>this.context.logout()) !== false);
    return (true && pd_0);
  }
}
export function viewFactory_ProfilePage0(viewUtils:import5.ViewUtils,parentInjector:import6.Injector,declarationEl:import3.AppElement):import1.AppView<import0.ProfilePage> {
  if ((renderType_ProfilePage === (null as any))) { (renderType_ProfilePage = viewUtils.createRenderComponentType('',0,import16.ViewEncapsulation.None,styles_ProfilePage,{})); }
  return new _View_ProfilePage0(viewUtils,parentInjector,declarationEl);
}