/**
 * This file is generated by the Angular 2 template compiler.
 * Do not edit.
 */
 /* tslint:disable */

import * as import0 from './privacy-policy';
import * as import1 from '@angular/core/src/linker/view';
import * as import2 from '@angular/core/src/render/api';
import * as import3 from '@angular/core/src/linker/element';
import * as import4 from '@angular/core/src/linker/view_utils';
import * as import5 from '@angular/core/src/di/injector';
import * as import6 from '@angular/core/src/linker/view_type';
import * as import7 from '@angular/core/src/change_detection/change_detection';
import * as import8 from 'ionic-angular/navigation/nav-controller';
import * as import9 from '@angular/core/src/metadata/view';
import * as import10 from '@angular/core/src/linker/component_factory';
import * as import11 from '../../node_modules/ionic-angular/components/toolbar/toolbar.ngfactory';
import * as import12 from '../../node_modules/ionic-angular/components/navbar/navbar.ngfactory';
import * as import13 from '../../node_modules/ionic-angular/components/toolbar/toolbar-title.ngfactory';
import * as import14 from '../../node_modules/ionic-angular/components/content/content.ngfactory';
import * as import15 from 'ionic-angular/config/config';
import * as import16 from '@angular/core/src/linker/element_ref';
import * as import17 from 'ionic-angular/navigation/view-controller';
import * as import18 from 'ionic-angular/components/app/app';
import * as import19 from 'ionic-angular/components/toolbar/toolbar';
import * as import20 from 'ionic-angular/util/keyboard';
import * as import21 from '@angular/core/src/zone/ng_zone';
import * as import22 from 'ionic-angular/components/tabs/tabs';
import * as import23 from 'ionic-angular/components/toolbar/toolbar-title';
import * as import24 from 'ionic-angular/components/navbar/navbar';
import * as import25 from 'ionic-angular/components/content/content';
export class Wrapper_PrivacyPolicyPage {
  context:import0.PrivacyPolicyPage;
  changed:boolean;
  constructor(p0:any) {
    this.changed = false;
    this.context = new import0.PrivacyPolicyPage(p0);
  }
  detectChangesInternal(view:import1.AppView<any>,el:any,throwOnChange:boolean):boolean {
    var changed:any = this.changed;
    this.changed = false;
    return changed;
  }
}
var renderType_PrivacyPolicyPage_Host:import2.RenderComponentType = (null as any);
class _View_PrivacyPolicyPage_Host0 extends import1.AppView<any> {
  _el_0:any;
  /*private*/ _appEl_0:import3.AppElement;
  _PrivacyPolicyPage_0_4:Wrapper_PrivacyPolicyPage;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PrivacyPolicyPage_Host0,renderType_PrivacyPolicyPage_Host,import6.ViewType.HOST,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    this._el_0 = this.selectOrCreateHostElement('page-privacy-policy',rootSelector,(null as any));
    this._appEl_0 = new import3.AppElement(0,(null as any),this,this._el_0);
    var compView_0:any = viewFactory_PrivacyPolicyPage0(this.viewUtils,this.injector(0),this._appEl_0);
    this._PrivacyPolicyPage_0_4 = new Wrapper_PrivacyPolicyPage(this.parentInjector.get(import8.NavController));
    this._appEl_0.initComponent(this._PrivacyPolicyPage_0_4.context,([] as any[]),compView_0);
    compView_0.create(this._PrivacyPolicyPage_0_4.context,this.projectableNodes,(null as any));
    this.init(([] as any[]).concat([this._el_0]),[this._el_0],([] as any[]),([] as any[]));
    return this._appEl_0;
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import0.PrivacyPolicyPage) && (0 === requestNodeIndex))) { return this._PrivacyPolicyPage_0_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._PrivacyPolicyPage_0_4.detectChangesInternal(this,this._el_0,throwOnChange);
    this.detectContentChildrenChanges(throwOnChange);
    this.detectViewChildrenChanges(throwOnChange);
  }
}
function viewFactory_PrivacyPolicyPage_Host0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<any> {
  if ((renderType_PrivacyPolicyPage_Host === (null as any))) { (renderType_PrivacyPolicyPage_Host = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,([] as any[]),{})); }
  return new _View_PrivacyPolicyPage_Host0(viewUtils,parentInjector,declarationEl);
}
export const PrivacyPolicyPageNgFactory:import10.ComponentFactory<import0.PrivacyPolicyPage> = new import10.ComponentFactory<import0.PrivacyPolicyPage>('page-privacy-policy',viewFactory_PrivacyPolicyPage_Host0,import0.PrivacyPolicyPage);
const styles_PrivacyPolicyPage:any[] = ([] as any[]);
var renderType_PrivacyPolicyPage:import2.RenderComponentType = (null as any);
class _View_PrivacyPolicyPage0 extends import1.AppView<import0.PrivacyPolicyPage> {
  _text_0:any;
  _el_1:any;
  _Header_1_3:import11.Wrapper_Header;
  _text_2:any;
  _el_3:any;
  /*private*/ _appEl_3:import3.AppElement;
  _Navbar_3_4:import12.Wrapper_Navbar;
  _text_4:any;
  _el_5:any;
  /*private*/ _appEl_5:import3.AppElement;
  _ToolbarTitle_5_4:import13.Wrapper_ToolbarTitle;
  _text_6:any;
  _text_7:any;
  _text_8:any;
  _text_9:any;
  _el_10:any;
  /*private*/ _appEl_10:import3.AppElement;
  _Content_10_4:import14.Wrapper_Content;
  _text_11:any;
  _el_12:any;
  _el_13:any;
  _text_14:any;
  _text_15:any;
  _el_16:any;
  _text_17:any;
  _text_18:any;
  _el_19:any;
  _text_20:any;
  _text_21:any;
  _el_22:any;
  _text_23:any;
  _text_24:any;
  _el_25:any;
  _text_26:any;
  _text_27:any;
  _el_28:any;
  _text_29:any;
  _el_30:any;
  _text_31:any;
  _text_32:any;
  _el_33:any;
  _text_34:any;
  _text_35:any;
  _el_36:any;
  _text_37:any;
  _text_38:any;
  _el_39:any;
  _text_40:any;
  _text_41:any;
  _el_42:any;
  _text_43:any;
  _text_44:any;
  _el_45:any;
  _text_46:any;
  _text_47:any;
  _el_48:any;
  _text_49:any;
  _el_50:any;
  _text_51:any;
  _text_52:any;
  _el_53:any;
  _text_54:any;
  _text_55:any;
  _el_56:any;
  _text_57:any;
  _el_58:any;
  _el_59:any;
  _text_60:any;
  _el_61:any;
  _text_62:any;
  _text_63:any;
  _el_64:any;
  _el_65:any;
  _text_66:any;
  _el_67:any;
  _text_68:any;
  _text_69:any;
  _text_70:any;
  _el_71:any;
  _text_72:any;
  _el_73:any;
  _text_74:any;
  _text_75:any;
  _el_76:any;
  _text_77:any;
  _text_78:any;
  _el_79:any;
  _text_80:any;
  _text_81:any;
  _el_82:any;
  _text_83:any;
  _el_84:any;
  _text_85:any;
  _text_86:any;
  _el_87:any;
  _text_88:any;
  _text_89:any;
  _el_90:any;
  _text_91:any;
  _el_92:any;
  _text_93:any;
  _text_94:any;
  _el_95:any;
  _text_96:any;
  _text_97:any;
  _text_98:any;
  _el_99:any;
  _text_100:any;
  _text_101:any;
  _el_102:any;
  _text_103:any;
  _el_104:any;
  _el_105:any;
  _text_106:any;
  _el_107:any;
  _text_108:any;
  _text_109:any;
  _el_110:any;
  _el_111:any;
  _text_112:any;
  _el_113:any;
  _text_114:any;
  _text_115:any;
  _text_116:any;
  _el_117:any;
  _text_118:any;
  _el_119:any;
  _text_120:any;
  _text_121:any;
  _el_122:any;
  _text_123:any;
  _text_124:any;
  _el_125:any;
  _text_126:any;
  _el_127:any;
  _el_128:any;
  _text_129:any;
  _el_130:any;
  _text_131:any;
  _el_132:any;
  _el_133:any;
  _text_134:any;
  _el_135:any;
  _text_136:any;
  _el_137:any;
  _text_138:any;
  _el_139:any;
  _text_140:any;
  _el_141:any;
  _text_142:any;
  _text_143:any;
  _text_144:any;
  _el_145:any;
  _el_146:any;
  _text_147:any;
  _el_148:any;
  _text_149:any;
  _el_150:any;
  _el_151:any;
  _text_152:any;
  _el_153:any;
  _text_154:any;
  _el_155:any;
  _text_156:any;
  _el_157:any;
  _text_158:any;
  _text_159:any;
  _text_160:any;
  _el_161:any;
  _text_162:any;
  _el_163:any;
  _text_164:any;
  _text_165:any;
  _el_166:any;
  _text_167:any;
  _el_168:any;
  _text_169:any;
  _el_170:any;
  _text_171:any;
  _el_172:any;
  _text_173:any;
  _el_174:any;
  _text_175:any;
  _text_176:any;
  _text_177:any;
  _el_178:any;
  _text_179:any;
  _el_180:any;
  _text_181:any;
  _el_182:any;
  _text_183:any;
  _el_184:any;
  _text_185:any;
  _text_186:any;
  _text_187:any;
  _el_188:any;
  _text_189:any;
  _el_190:any;
  _text_191:any;
  _el_192:any;
  _text_193:any;
  _el_194:any;
  _text_195:any;
  _text_196:any;
  _text_197:any;
  _el_198:any;
  _text_199:any;
  _el_200:any;
  _text_201:any;
  _el_202:any;
  _text_203:any;
  _el_204:any;
  _text_205:any;
  _text_206:any;
  _text_207:any;
  _el_208:any;
  _text_209:any;
  _el_210:any;
  _text_211:any;
  _el_212:any;
  _text_213:any;
  _el_214:any;
  _text_215:any;
  _text_216:any;
  _el_217:any;
  _text_218:any;
  _el_219:any;
  _text_220:any;
  _text_221:any;
  _text_222:any;
  _el_223:any;
  _text_224:any;
  _el_225:any;
  _text_226:any;
  _el_227:any;
  _text_228:any;
  _el_229:any;
  _text_230:any;
  _text_231:any;
  _text_232:any;
  _text_233:any;
  _el_234:any;
  _text_235:any;
  _el_236:any;
  _text_237:any;
  _text_238:any;
  _el_239:any;
  _text_240:any;
  _text_241:any;
  _el_242:any;
  _text_243:any;
  _el_244:any;
  _text_245:any;
  _text_246:any;
  _el_247:any;
  _text_248:any;
  _text_249:any;
  _el_250:any;
  _text_251:any;
  _text_252:any;
  _el_253:any;
  _text_254:any;
  _text_255:any;
  _el_256:any;
  _text_257:any;
  _text_258:any;
  _el_259:any;
  _text_260:any;
  _text_261:any;
  _el_262:any;
  _text_263:any;
  _text_264:any;
  _el_265:any;
  _text_266:any;
  _text_267:any;
  _text_268:any;
  _el_269:any;
  _text_270:any;
  _el_271:any;
  _text_272:any;
  _text_273:any;
  _el_274:any;
  _text_275:any;
  _text_276:any;
  _el_277:any;
  _text_278:any;
  _el_279:any;
  _text_280:any;
  _text_281:any;
  _el_282:any;
  _text_283:any;
  _text_284:any;
  _el_285:any;
  _text_286:any;
  _el_287:any;
  _text_288:any;
  _text_289:any;
  _el_290:any;
  _text_291:any;
  _el_292:any;
  _text_293:any;
  _text_294:any;
  _text_295:any;
  _text_296:any;
  /*private*/ _expr_0:any;
  /*private*/ _expr_1:any;
  /*private*/ _expr_2:any;
  constructor(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement) {
    super(_View_PrivacyPolicyPage0,renderType_PrivacyPolicyPage,import6.ViewType.COMPONENT,viewUtils,parentInjector,declarationEl,import7.ChangeDetectorStatus.CheckAlways);
  }
  createInternal(rootSelector:string):import3.AppElement {
    const parentRenderNode:any = this.renderer.createViewRoot(this.declarationAppElement.nativeElement);
    this._text_0 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._el_1 = this.renderer.createElement(parentRenderNode,'ion-header',(null as any));
    this._Header_1_3 = new import11.Wrapper_Header(this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_1),this.renderer,this.parentInjector.get(import17.ViewController,(null as any)));
    this._text_2 = this.renderer.createText(this._el_1,'\n\n  ',(null as any));
    this._el_3 = this.renderer.createElement(this._el_1,'ion-navbar',(null as any));
    this.renderer.setElementAttribute(this._el_3,'class','toolbar');
    this._appEl_3 = new import3.AppElement(3,1,this,this._el_3);
    var compView_3:any = import12.viewFactory_Navbar0(this.viewUtils,this.injector(3),this._appEl_3);
    this._Navbar_3_4 = new import12.Wrapper_Navbar(this.parentInjector.get(import18.App),this.parentInjector.get(import17.ViewController,(null as any)),this.parentInjector.get(import8.NavController,(null as any)),this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_3),this.renderer);
    this._appEl_3.initComponent(this._Navbar_3_4.context,([] as any[]),compView_3);
    this._text_4 = this.renderer.createText((null as any),'\n    ',(null as any));
    this._el_5 = this.renderer.createElement((null as any),'ion-title',(null as any));
    this._appEl_5 = new import3.AppElement(5,3,this,this._el_5);
    var compView_5:any = import13.viewFactory_ToolbarTitle0(this.viewUtils,this.injector(5),this._appEl_5);
    this._ToolbarTitle_5_4 = new import13.Wrapper_ToolbarTitle(this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_5),this.renderer,this.parentInjector.get(import19.Toolbar,(null as any)),this._Navbar_3_4.context);
    this._appEl_5.initComponent(this._ToolbarTitle_5_4.context,([] as any[]),compView_5);
    this._text_6 = this.renderer.createText((null as any),'Privacy Policy',(null as any));
    compView_5.create(this._ToolbarTitle_5_4.context,[([] as any[]).concat([this._text_6])],(null as any));
    this._text_7 = this.renderer.createText((null as any),'\n  ',(null as any));
    compView_3.create(this._Navbar_3_4.context,[
      ([] as any[]),
      ([] as any[]),
      ([] as any[]),
      ([] as any[]).concat([
        this._text_4,
        this._el_5,
        this._text_7
      ]
      )
    ]
    ,(null as any));
    this._text_8 = this.renderer.createText(this._el_1,'\n\n',(null as any));
    this._text_9 = this.renderer.createText(parentRenderNode,'\n\n\n',(null as any));
    this._el_10 = this.renderer.createElement(parentRenderNode,'ion-content',(null as any));
    this.renderer.setElementAttribute(this._el_10,'padding','');
    this._appEl_10 = new import3.AppElement(10,(null as any),this,this._el_10);
    var compView_10:any = import14.viewFactory_Content0(this.viewUtils,this.injector(10),this._appEl_10);
    this._Content_10_4 = new import14.Wrapper_Content(this.parentInjector.get(import15.Config),new import16.ElementRef(this._el_10),this.renderer,this.parentInjector.get(import18.App),this.parentInjector.get(import20.Keyboard),this.parentInjector.get(import21.NgZone),this.parentInjector.get(import17.ViewController,(null as any)),this.parentInjector.get(import22.Tabs,(null as any)));
    this._appEl_10.initComponent(this._Content_10_4.context,([] as any[]),compView_10);
    this._text_11 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_12 = this.renderer.createElement((null as any),'p',(null as any));
    this.renderer.setElementAttribute(this._el_12,'style','font-size: smaller;');
    this._el_13 = this.renderer.createElement(this._el_12,'i',(null as any));
    this._text_14 = this.renderer.createText(this._el_13,'(Last modified on 29/12/16)',(null as any));
    this._text_15 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_16 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_17 = this.renderer.createText(this._el_16,'We recognize that visitors, users, members and others (collectively or individually “Users”) who enter, use and/or visit Lisa Guru Horoscope App (collectively, including all content available on or through our application, to be collectively referred to as the “App”) should get the protection of their privacy and personal data because we know that they value their privacy. Therefore, we made this policy to prevent the internet fraud and secure your mobile phone or tablet device from danger such as virus.',(null as any));
    this._text_18 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_19 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_20 = this.renderer.createText(this._el_19,'This Privacy Policy provides important information regarding our use and disclosure of User information collected on or otherwise through the App. We provide this Privacy Policy to help you make an informed choice about whether to use or continue using our App.',(null as any));
    this._text_21 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_22 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_23 = this.renderer.createText(this._el_22,'This Privacy Policy is incorporated into, forms part of and is subject to the Terms of Service. Your use of the App and any personal information you provide on the App remains subject to the terms of this Privacy Policy and Terms of Service. In particular, you must be of the age of majority in order to use the App. To use our App, you have to confirm that your age is at least twenty years old, which is the minimum age requirement of majority under Thai law.',(null as any));
    this._text_24 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_25 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_26 = this.renderer.createText(this._el_25,'Please note that any information, text, software, script, image, graphic, photograph, sound, music, video, other audio or visual content, interactive feature or any other data or content in any media or format (collectively, the “Content”) posted or submitted at the discretion of Users onto the App becomes published content and is not considered personally identifiable information that is subject to this Privacy Policy.',(null as any));
    this._text_27 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_28 = this.renderer.createElement((null as any),'h6',(null as any));
    this._text_29 = this.renderer.createText(this._el_28,'Part 1',(null as any));
    this._el_30 = this.renderer.createElement(this._el_28,'br',(null as any));
    this._text_31 = this.renderer.createText(this._el_28,'\nInformation you provide to us\n',(null as any));
    this._text_32 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_33 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_34 = this.renderer.createText(this._el_33,'This Application collects some Personal Data from its Users. Among the types of Personal Data that this Application collects, by itself or through third parties, there are: first name, last name, date of birth and email address.',(null as any));
    this._text_35 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_36 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_37 = this.renderer.createText(this._el_36,'Other Personal Data collected may be described in other sections of this privacy policy or by dedicated explanation text contextually with the Data collection.',(null as any));
    this._text_38 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_39 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_40 = this.renderer.createText(this._el_39,'The Personal Data may be freely provided by the User, or collected automatically when using this Application.\nAny use of Cookies - or of other tracking tools - by this Application or by the owners of third party services used by this Application, unless stated otherwise, serves to identify Users and remember their preferences, for the sole purpose of providing the service required by the User.\n',(null as any));
    this._text_41 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_42 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_43 = this.renderer.createText(this._el_42,'Failure to provide certain Personal Data may make it impossible for this Application to provide its services.',(null as any));
    this._text_44 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_45 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_46 = this.renderer.createText(this._el_45,'Users are responsible for any Personal Data of third parties obtained, published or shared through this Application and confirm that they have the third party\'s consent to provide the Data to the Owner.',(null as any));
    this._text_47 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_48 = this.renderer.createElement((null as any),'h6',(null as any));
    this._text_49 = this.renderer.createText(this._el_48,'Part 2',(null as any));
    this._el_50 = this.renderer.createElement(this._el_48,'br',(null as any));
    this._text_51 = this.renderer.createText(this._el_48,'\nMode and place of processing the Data - Methods of processing\n',(null as any));
    this._text_52 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_53 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_54 = this.renderer.createText(this._el_53,'The Data Controller processes the Data of Users in a proper manner and shall take appropriate security measures to prevent unauthorized access, disclosure, modification, or unauthorized destruction of the Data.\nThe Data processing is carried out using computers and/or IT enabled tools, following organizational procedures and modes strictly related to the purposes indicated. In addition to the Data Controller, in some cases, the Data may be accessible to certain types of persons in charge, involved with the operation of the site (administration, sales, marketing, legal, system administration) or external parties (such as third party technical service providers, mail carriers, hosting providers, IT companies, communications agencies) appointed, if necessary, as Data Processors by the Owner. The updated list of these parties may be requested from the Data Controller at any time.\n',(null as any));
    this._text_55 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_56 = this.renderer.createElement((null as any),'ol',(null as any));
    this._text_57 = this.renderer.createText(this._el_56,'\n  ',(null as any));
    this._el_58 = this.renderer.createElement(this._el_56,'li',(null as any));
    this._el_59 = this.renderer.createElement(this._el_58,'b',(null as any));
    this._text_60 = this.renderer.createText(this._el_59,'Place',(null as any));
    this._el_61 = this.renderer.createElement(this._el_58,'br',(null as any));
    this._text_62 = this.renderer.createText(this._el_58,'\nThe Data is processed at the Data Controller\'s operating offices and in any other places where the parties involved with the processing are located. For further information, please contact the Data Controller.\n  ',(null as any));
    this._text_63 = this.renderer.createText(this._el_56,'\n  ',(null as any));
    this._el_64 = this.renderer.createElement(this._el_56,'li',(null as any));
    this._el_65 = this.renderer.createElement(this._el_64,'b',(null as any));
    this._text_66 = this.renderer.createText(this._el_65,'Retention time',(null as any));
    this._el_67 = this.renderer.createElement(this._el_64,'br',(null as any));
    this._text_68 = this.renderer.createText(this._el_64,'\n    The Data is kept for the time necessary to provide the service requested by the User, or stated by the purposes outlined in this document, and the User can always request that the Data Controller suspend or remove the data.\n  ',(null as any));
    this._text_69 = this.renderer.createText(this._el_56,'\n',(null as any));
    this._text_70 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_71 = this.renderer.createElement((null as any),'h6',(null as any));
    this._text_72 = this.renderer.createText(this._el_71,'Part 3',(null as any));
    this._el_73 = this.renderer.createElement(this._el_71,'br',(null as any));
    this._text_74 = this.renderer.createText(this._el_71,'\nThe use of the collected Data',(null as any));
    this._text_75 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_76 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_77 = this.renderer.createText(this._el_76,'The Data concerning the User is collected to allow the Owner to provide its services, as well as for the following purposes: Access to third party accounts and Registration and authentication. ',(null as any));
    this._text_78 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_79 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_80 = this.renderer.createText(this._el_79,'The Personal Data used for each purpose is outlined in the specific sections of this document.',(null as any));
    this._text_81 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_82 = this.renderer.createElement((null as any),'h6',(null as any));
    this._text_83 = this.renderer.createText(this._el_82,'Part 4',(null as any));
    this._el_84 = this.renderer.createElement(this._el_82,'br',(null as any));
    this._text_85 = this.renderer.createText(this._el_82,'\nFacebook permissions asked by this Application',(null as any));
    this._text_86 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_87 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_88 = this.renderer.createText(this._el_87,'This Application may ask for some Facebook permissions allowing it to perform actions with the User\'s Facebook account and to retrieve information, including Personal Data, from it.',(null as any));
    this._text_89 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_90 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_91 = this.renderer.createText(this._el_90,'For more information about the following permissions, refer to the ',(null as any));
    this._el_92 = this.renderer.createElement(this._el_90,'a',(null as any));
    this.renderer.setElementAttribute(this._el_92,'href','https://developers.facebook.com/docs/facebook-login/permissions');
    this.renderer.setElementAttribute(this._el_92,'target','_blank');
    this._text_93 = this.renderer.createText(this._el_92,'Facebook permissions documentation',(null as any));
    this._text_94 = this.renderer.createText(this._el_90,' to the ',(null as any));
    this._el_95 = this.renderer.createElement(this._el_90,'a',(null as any));
    this.renderer.setElementAttribute(this._el_95,'href','https://www.facebook.com/about/privacy/and');
    this.renderer.setElementAttribute(this._el_95,'target','_blank');
    this._text_96 = this.renderer.createText(this._el_95,'Facebook privacy policy',(null as any));
    this._text_97 = this.renderer.createText(this._el_90,'.',(null as any));
    this._text_98 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_99 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_100 = this.renderer.createText(this._el_99,'The permissions asked are the following:',(null as any));
    this._text_101 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_102 = this.renderer.createElement((null as any),'ol',(null as any));
    this._text_103 = this.renderer.createText(this._el_102,'\n  ',(null as any));
    this._el_104 = this.renderer.createElement(this._el_102,'li',(null as any));
    this._el_105 = this.renderer.createElement(this._el_104,'b',(null as any));
    this._text_106 = this.renderer.createText(this._el_105,'Basic information',(null as any));
    this._el_107 = this.renderer.createElement(this._el_104,'br',(null as any));
    this._text_108 = this.renderer.createText(this._el_104,'\n    By default, this includes certain User’s Data such as id, name, picture, gender, and their locale. Certain connections of the User, such as the Friends, are also available. If the User has made more of their Data public, more information will be available.\n  ',(null as any));
    this._text_109 = this.renderer.createText(this._el_102,'\n  ',(null as any));
    this._el_110 = this.renderer.createElement(this._el_102,'li',(null as any));
    this._el_111 = this.renderer.createElement(this._el_110,'b',(null as any));
    this._text_112 = this.renderer.createText(this._el_111,'About Me',(null as any));
    this._el_113 = this.renderer.createElement(this._el_110,'br',(null as any));
    this._text_114 = this.renderer.createText(this._el_110,'\n    Provides access to the \'About Me\' section of the profile.\n  ',(null as any));
    this._text_115 = this.renderer.createText(this._el_102,'\n',(null as any));
    this._text_116 = this.renderer.createText((null as any),'\n\n\n',(null as any));
    this._el_117 = this.renderer.createElement((null as any),'h6',(null as any));
    this._text_118 = this.renderer.createText(this._el_117,'Part 5',(null as any));
    this._el_119 = this.renderer.createElement(this._el_117,'br',(null as any));
    this._text_120 = this.renderer.createText(this._el_117,'\nDetailed information on the processing of Personal Data',(null as any));
    this._text_121 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_122 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_123 = this.renderer.createText(this._el_122,'Personal Data is collected for the following purposes and using the following services:',(null as any));
    this._text_124 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_125 = this.renderer.createElement((null as any),'ul',(null as any));
    this._text_126 = this.renderer.createText(this._el_125,'\n  ',(null as any));
    this._el_127 = this.renderer.createElement(this._el_125,'li',(null as any));
    this._el_128 = this.renderer.createElement(this._el_127,'b',(null as any));
    this._text_129 = this.renderer.createText(this._el_128,'Access to third party accounts',(null as any));
    this._el_130 = this.renderer.createElement(this._el_127,'br',(null as any));
    this._text_131 = this.renderer.createText(this._el_127,'\nThis type of service allows this Application to access Data from your account on a third party service and perform actions with it. These services are not activated automatically, but require explicit authorization by the User.\n  ',(null as any));
    this._el_132 = this.renderer.createElement(this._el_127,'br',(null as any));
    this._el_133 = this.renderer.createElement(this._el_127,'br',(null as any));
    this._text_134 = this.renderer.createText(this._el_127,'\n  ',(null as any));
    this._el_135 = this.renderer.createElement(this._el_127,'b',(null as any));
    this._text_136 = this.renderer.createText(this._el_135,'Facebook account access (This Application)',(null as any));
    this._el_137 = this.renderer.createElement(this._el_127,'br',(null as any));
    this._text_138 = this.renderer.createText(this._el_127,'\nThis service allows this Application to connect with the User\'s account on the Facebook social network, provided by Facebook, Inc.\nPermissions asked: About Me.',(null as any));
    this._el_139 = this.renderer.createElement(this._el_127,'br',(null as any));
    this._text_140 = this.renderer.createText(this._el_127,'\nPlace of processing: US – ',(null as any));
    this._el_141 = this.renderer.createElement(this._el_127,'a',(null as any));
    this.renderer.setElementAttribute(this._el_141,'href','https://www.facebook.com/policy.php');
    this.renderer.setElementAttribute(this._el_141,'target','_blank');
    this._text_142 = this.renderer.createText(this._el_141,'Privacy Policy',(null as any));
    this._text_143 = this.renderer.createText(this._el_127,'\n  ',(null as any));
    this._text_144 = this.renderer.createText(this._el_125,'\n\n  ',(null as any));
    this._el_145 = this.renderer.createElement(this._el_125,'li',(null as any));
    this._el_146 = this.renderer.createElement(this._el_145,'b',(null as any));
    this._text_147 = this.renderer.createText(this._el_146,'Registration and authentication',(null as any));
    this._el_148 = this.renderer.createElement(this._el_145,'br',(null as any));
    this._text_149 = this.renderer.createText(this._el_145,'\n    By registering or authenticating, Users allow this Application to identify them and give them access to dedicated services. Depending on what is described below, third parties may provide registration and authentication services. In this case, this Application will be able to access some Data, stored by these third party services, for registration or identification purposes.\n  ',(null as any));
    this._el_150 = this.renderer.createElement(this._el_145,'br',(null as any));
    this._el_151 = this.renderer.createElement(this._el_145,'br',(null as any));
    this._text_152 = this.renderer.createText(this._el_145,'\n  ',(null as any));
    this._el_153 = this.renderer.createElement(this._el_145,'b',(null as any));
    this._text_154 = this.renderer.createText(this._el_153,'Direct registration (This Application)',(null as any));
    this._el_155 = this.renderer.createElement(this._el_145,'br',(null as any));
    this._text_156 = this.renderer.createText(this._el_145,'\n  The User registers by filling out the registration form and providing the Personal Data directly to this Application.',(null as any));
    this._el_157 = this.renderer.createElement(this._el_145,'br',(null as any));
    this._text_158 = this.renderer.createText(this._el_145,'\n  Personal Data collected: first name, last name, email address and date of birth.\n  ',(null as any));
    this._text_159 = this.renderer.createText(this._el_125,'\n',(null as any));
    this._text_160 = this.renderer.createText((null as any),'\n\n\n\n',(null as any));
    this._el_161 = this.renderer.createElement((null as any),'h6',(null as any));
    this._text_162 = this.renderer.createText(this._el_161,'Part 6',(null as any));
    this._el_163 = this.renderer.createElement(this._el_161,'br',(null as any));
    this._text_164 = this.renderer.createText(this._el_161,'\nAdditional information about Data collection and processing',(null as any));
    this._text_165 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_166 = this.renderer.createElement((null as any),'ol',(null as any));
    this._text_167 = this.renderer.createText(this._el_166,'\n  ',(null as any));
    this._el_168 = this.renderer.createElement(this._el_166,'li',(null as any));
    this._text_169 = this.renderer.createText(this._el_168,'\n    ',(null as any));
    this._el_170 = this.renderer.createElement(this._el_168,'b',(null as any));
    this._text_171 = this.renderer.createText(this._el_170,'Legal action',(null as any));
    this._el_172 = this.renderer.createElement(this._el_168,'br',(null as any));
    this._text_173 = this.renderer.createText(this._el_168,'\n    ',(null as any));
    this._el_174 = this.renderer.createElement(this._el_168,'p',(null as any));
    this._text_175 = this.renderer.createText(this._el_174,'\n      The User\'s Personal Data may be used for legal purposes by the Data Controller, in Court or in the stages leading to possible legal action arising from improper use of this Application or the related services. The User declares to be aware that the Data Controller may be required to reveal personal data upon request of public authorities.\n    ',(null as any));
    this._text_176 = this.renderer.createText(this._el_168,'\n  ',(null as any));
    this._text_177 = this.renderer.createText(this._el_166,'\n  ',(null as any));
    this._el_178 = this.renderer.createElement(this._el_166,'li',(null as any));
    this._text_179 = this.renderer.createText(this._el_178,'\n    ',(null as any));
    this._el_180 = this.renderer.createElement(this._el_178,'b',(null as any));
    this._text_181 = this.renderer.createText(this._el_180,'Additional information about User\'s Personal Data',(null as any));
    this._el_182 = this.renderer.createElement(this._el_178,'br',(null as any));
    this._text_183 = this.renderer.createText(this._el_178,'\n    ',(null as any));
    this._el_184 = this.renderer.createElement(this._el_178,'p',(null as any));
    this._text_185 = this.renderer.createText(this._el_184,'\n      In addition to the information contained in this privacy policy, this Application may provide the User with additional and contextual information concerning particular services or the collection and processing of Personal Data upon request.\n    ',(null as any));
    this._text_186 = this.renderer.createText(this._el_178,'\n  ',(null as any));
    this._text_187 = this.renderer.createText(this._el_166,'\n  ',(null as any));
    this._el_188 = this.renderer.createElement(this._el_166,'li',(null as any));
    this._text_189 = this.renderer.createText(this._el_188,'\n    ',(null as any));
    this._el_190 = this.renderer.createElement(this._el_188,'b',(null as any));
    this._text_191 = this.renderer.createText(this._el_190,'System logs and maintenance',(null as any));
    this._el_192 = this.renderer.createElement(this._el_188,'br',(null as any));
    this._text_193 = this.renderer.createText(this._el_188,'\n    ',(null as any));
    this._el_194 = this.renderer.createElement(this._el_188,'p',(null as any));
    this._text_195 = this.renderer.createText(this._el_194,'\n      For operation and maintenance purposes, this Application and any third party services may collect files that record interaction with this Application (System logs) or use for this purpose other Personal Data (such as IP Address).\n    ',(null as any));
    this._text_196 = this.renderer.createText(this._el_188,'\n  ',(null as any));
    this._text_197 = this.renderer.createText(this._el_166,'\n  ',(null as any));
    this._el_198 = this.renderer.createElement(this._el_166,'li',(null as any));
    this._text_199 = this.renderer.createText(this._el_198,'\n    ',(null as any));
    this._el_200 = this.renderer.createElement(this._el_198,'b',(null as any));
    this._text_201 = this.renderer.createText(this._el_200,'Information not contained in this policy',(null as any));
    this._el_202 = this.renderer.createElement(this._el_198,'br',(null as any));
    this._text_203 = this.renderer.createText(this._el_198,'\n    ',(null as any));
    this._el_204 = this.renderer.createElement(this._el_198,'p',(null as any));
    this._text_205 = this.renderer.createText(this._el_204,'\n      More details concerning the collection or processing of Personal Data may be requested from the Data Controller at any time. Please see the contact information at the end of this document.\n    ',(null as any));
    this._text_206 = this.renderer.createText(this._el_198,'\n  ',(null as any));
    this._text_207 = this.renderer.createText(this._el_166,'\n  ',(null as any));
    this._el_208 = this.renderer.createElement(this._el_166,'li',(null as any));
    this._text_209 = this.renderer.createText(this._el_208,'\n    ',(null as any));
    this._el_210 = this.renderer.createElement(this._el_208,'b',(null as any));
    this._text_211 = this.renderer.createText(this._el_210,'The rights of Users',(null as any));
    this._el_212 = this.renderer.createElement(this._el_208,'br',(null as any));
    this._text_213 = this.renderer.createText(this._el_208,'\n    ',(null as any));
    this._el_214 = this.renderer.createElement(this._el_208,'p',(null as any));
    this._text_215 = this.renderer.createText(this._el_214,'\n      Users have the right, at any time, to know whether their Personal Data has been stored and can consult the Data Controller to learn about their contents and origin, to verify their accuracy or to ask for them to be supplemented, cancelled, updated or corrected, or for their transformation into anonymous format or to block any data held in violation of the law, as well as to oppose their treatment for any and all legitimate reasons. Requests should be sent to the Data Controller at the contact information set out below.\n    ',(null as any));
    this._text_216 = this.renderer.createText(this._el_208,'\n    ',(null as any));
    this._el_217 = this.renderer.createElement(this._el_208,'p',(null as any));
    this._text_218 = this.renderer.createText(this._el_217,'\n      This Application does not support “Do Not Track” requests.',(null as any));
    this._el_219 = this.renderer.createElement(this._el_217,'br',(null as any));
    this._text_220 = this.renderer.createText(this._el_217,'\nTo determine whether any of the third party services it uses honor the “Do Not Track” requests, please read their privacy policies.\n    ',(null as any));
    this._text_221 = this.renderer.createText(this._el_208,'\n  ',(null as any));
    this._text_222 = this.renderer.createText(this._el_166,'\n  ',(null as any));
    this._el_223 = this.renderer.createElement(this._el_166,'li',(null as any));
    this._text_224 = this.renderer.createText(this._el_223,'\n    ',(null as any));
    this._el_225 = this.renderer.createElement(this._el_223,'b',(null as any));
    this._text_226 = this.renderer.createText(this._el_225,'Changes to this privacy policy',(null as any));
    this._el_227 = this.renderer.createElement(this._el_223,'br',(null as any));
    this._text_228 = this.renderer.createText(this._el_223,'\n    ',(null as any));
    this._el_229 = this.renderer.createElement(this._el_223,'p',(null as any));
    this._text_230 = this.renderer.createText(this._el_229,'\n      The Data Controller reserves the right to make changes to this privacy policy at any time by giving notice to its Users on this page. It is strongly recommended to check this page often, referring to the date of the last modification listed at the bottom. If a User objects to any of the changes to the Policy, the User must cease using this Application and can request that the Data Controller remove the Personal Data. Unless stated otherwise, the then-current privacy policy applies to all Personal Data the Data Controller has about Users.\n    ',(null as any));
    this._text_231 = this.renderer.createText(this._el_223,'\n  ',(null as any));
    this._text_232 = this.renderer.createText(this._el_166,'\n',(null as any));
    this._text_233 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_234 = this.renderer.createElement((null as any),'h6',(null as any));
    this._text_235 = this.renderer.createText(this._el_234,'Part 7',(null as any));
    this._el_236 = this.renderer.createElement(this._el_234,'br',(null as any));
    this._text_237 = this.renderer.createText(this._el_234,'\nObligations concerning Registration and Account Security',(null as any));
    this._text_238 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_239 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_240 = this.renderer.createText(this._el_239,'Lisa Guru Horoscope App users provide their real names and information, and we need your help to keep it that way. Here are some commitments you make to us relating to registering and maintaining the security of your account:',(null as any));
    this._text_241 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_242 = this.renderer.createElement((null as any),'ol',(null as any));
    this._text_243 = this.renderer.createText(this._el_242,'\n  ',(null as any));
    this._el_244 = this.renderer.createElement(this._el_242,'li',(null as any));
    this._text_245 = this.renderer.createText(this._el_244,'\n    You will not provide any false personal information on Lisa Guru Horoscope App, or create an account for anyone other than yourself without permission.\n  ',(null as any));
    this._text_246 = this.renderer.createText(this._el_242,'\n  ',(null as any));
    this._el_247 = this.renderer.createElement(this._el_242,'li',(null as any));
    this._text_248 = this.renderer.createText(this._el_247,'\n    You will not use your personal profile for your own commercial gain (such as selling your status update to an advertiser).\n  ',(null as any));
    this._text_249 = this.renderer.createText(this._el_242,'\n  ',(null as any));
    this._el_250 = this.renderer.createElement(this._el_242,'li',(null as any));
    this._text_251 = this.renderer.createText(this._el_250,'\n    You will not use Lisa Guru Horoscope App if you are under 13.\n  ',(null as any));
    this._text_252 = this.renderer.createText(this._el_242,'\n  ',(null as any));
    this._el_253 = this.renderer.createElement(this._el_242,'li',(null as any));
    this._text_254 = this.renderer.createText(this._el_253,'\n    You will not use Lisa Guru Horoscope App if you are a convicted sex offender.\n  ',(null as any));
    this._text_255 = this.renderer.createText(this._el_242,'\n  ',(null as any));
    this._el_256 = this.renderer.createElement(this._el_242,'li',(null as any));
    this._text_257 = this.renderer.createText(this._el_256,'You will keep your contact information accurate and up-to-date.',(null as any));
    this._text_258 = this.renderer.createText(this._el_242,'\n  ',(null as any));
    this._el_259 = this.renderer.createElement(this._el_242,'li',(null as any));
    this._text_260 = this.renderer.createText(this._el_259,'You will not share your password, let anyone else access your account, or do anything else that might jeopardize the security of your account',(null as any));
    this._text_261 = this.renderer.createText(this._el_242,'\n  ',(null as any));
    this._el_262 = this.renderer.createElement(this._el_242,'li',(null as any));
    this._text_263 = this.renderer.createText(this._el_262,'\n    You will not transfer your account to anyone without first getting our written permission.\n  ',(null as any));
    this._text_264 = this.renderer.createText(this._el_242,'\n  ',(null as any));
    this._el_265 = this.renderer.createElement(this._el_242,'li',(null as any));
    this._text_266 = this.renderer.createText(this._el_265,'If you select a username for your account we reserve the right to remove or reclaim it if we believe appropriate (such as when a trademark owner complains about a username that does not closely relate to a user’s actual name).',(null as any));
    this._text_267 = this.renderer.createText(this._el_242,'\n',(null as any));
    this._text_268 = this.renderer.createText((null as any),'\n\n\n',(null as any));
    this._el_269 = this.renderer.createElement((null as any),'h6',(null as any));
    this._text_270 = this.renderer.createText(this._el_269,'Part 8',(null as any));
    this._el_271 = this.renderer.createElement(this._el_269,'br',(null as any));
    this._text_272 = this.renderer.createText(this._el_269,'\nCopyright',(null as any));
    this._text_273 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_274 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_275 = this.renderer.createText(this._el_274,'Editorial items appearing in Lisa Guru Horoscope App that were originally published by Lisa team in Thailand and are the copyright property of Burda (Thailand).',(null as any));
    this._text_276 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_277 = this.renderer.createElement((null as any),'h6',(null as any));
    this._text_278 = this.renderer.createText(this._el_277,'Part 9',(null as any));
    this._el_279 = this.renderer.createElement(this._el_277,'br',(null as any));
    this._text_280 = this.renderer.createText(this._el_277,'\nOther Terms',(null as any));
    this._text_281 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_282 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_283 = this.renderer.createText(this._el_282,'Changes. This Privacy Policy may be revised, amended or modified periodically. Unless stated otherwise, our current privacy policy applies to all information that we have about you and your account. If we make changes to this Privacy Policy we will send an update to you should there be an update which will link you back to the Privacy Section. Your use of the website signifies your acceptance and agreement to this Privacy Policy (as may be amend or revised from time to time).',(null as any));
    this._text_284 = this.renderer.createText((null as any),'\n\n',(null as any));
    this._el_285 = this.renderer.createElement((null as any),'h6',(null as any));
    this._text_286 = this.renderer.createText(this._el_285,'Part 10',(null as any));
    this._el_287 = this.renderer.createElement(this._el_285,'br',(null as any));
    this._text_288 = this.renderer.createText(this._el_285,'\nChannels for contacting us',(null as any));
    this._text_289 = this.renderer.createText((null as any),'\n',(null as any));
    this._el_290 = this.renderer.createElement((null as any),'p',(null as any));
    this._text_291 = this.renderer.createText(this._el_290,'\n  If you have any inquiries or suggestions, or wish to make a report of problem on using this App and this policy, you can contact us anytime you would like to do so according to the channels and contact detail that we provided in ',(null as any));
    this._el_292 = this.renderer.createElement(this._el_290,'a',(null as any));
    this.renderer.setElementAttribute(this._el_292,'href','https://lisaguru.com/contact-us/');
    this.renderer.setElementAttribute(this._el_292,'target','_blank');
    this._text_293 = this.renderer.createText(this._el_292,'https://lisaguru.com/contact-us/',(null as any));
    this._text_294 = this.renderer.createText(this._el_290,'.\n',(null as any));
    this._text_295 = this.renderer.createText((null as any),'\n\n',(null as any));
    compView_10.create(this._Content_10_4.context,[
      ([] as any[]),
      ([] as any[]).concat([
        this._text_11,
        this._el_12,
        this._text_15,
        this._el_16,
        this._text_18,
        this._el_19,
        this._text_21,
        this._el_22,
        this._text_24,
        this._el_25,
        this._text_27,
        this._el_28,
        this._text_32,
        this._el_33,
        this._text_35,
        this._el_36,
        this._text_38,
        this._el_39,
        this._text_41,
        this._el_42,
        this._text_44,
        this._el_45,
        this._text_47,
        this._el_48,
        this._text_52,
        this._el_53,
        this._text_55,
        this._el_56,
        this._text_70,
        this._el_71,
        this._text_75,
        this._el_76,
        this._text_78,
        this._el_79,
        this._text_81,
        this._el_82,
        this._text_86,
        this._el_87,
        this._text_89,
        this._el_90,
        this._text_98,
        this._el_99,
        this._text_101,
        this._el_102,
        this._text_116,
        this._el_117,
        this._text_121,
        this._el_122,
        this._text_124,
        this._el_125,
        this._text_160,
        this._el_161,
        this._text_165,
        this._el_166,
        this._text_233,
        this._el_234,
        this._text_238,
        this._el_239,
        this._text_241,
        this._el_242,
        this._text_268,
        this._el_269,
        this._text_273,
        this._el_274,
        this._text_276,
        this._el_277,
        this._text_281,
        this._el_282,
        this._text_284,
        this._el_285,
        this._text_289,
        this._el_290,
        this._text_295
      ]
      ),
      ([] as any[])
    ]
    ,(null as any));
    this._text_296 = this.renderer.createText(parentRenderNode,'\n',(null as any));
    this._expr_0 = import7.UNINITIALIZED;
    this._expr_1 = import7.UNINITIALIZED;
    this._expr_2 = import7.UNINITIALIZED;
    this.init(([] as any[]),[
      this._text_0,
      this._el_1,
      this._text_2,
      this._el_3,
      this._text_4,
      this._el_5,
      this._text_6,
      this._text_7,
      this._text_8,
      this._text_9,
      this._el_10,
      this._text_11,
      this._el_12,
      this._el_13,
      this._text_14,
      this._text_15,
      this._el_16,
      this._text_17,
      this._text_18,
      this._el_19,
      this._text_20,
      this._text_21,
      this._el_22,
      this._text_23,
      this._text_24,
      this._el_25,
      this._text_26,
      this._text_27,
      this._el_28,
      this._text_29,
      this._el_30,
      this._text_31,
      this._text_32,
      this._el_33,
      this._text_34,
      this._text_35,
      this._el_36,
      this._text_37,
      this._text_38,
      this._el_39,
      this._text_40,
      this._text_41,
      this._el_42,
      this._text_43,
      this._text_44,
      this._el_45,
      this._text_46,
      this._text_47,
      this._el_48,
      this._text_49,
      this._el_50,
      this._text_51,
      this._text_52,
      this._el_53,
      this._text_54,
      this._text_55,
      this._el_56,
      this._text_57,
      this._el_58,
      this._el_59,
      this._text_60,
      this._el_61,
      this._text_62,
      this._text_63,
      this._el_64,
      this._el_65,
      this._text_66,
      this._el_67,
      this._text_68,
      this._text_69,
      this._text_70,
      this._el_71,
      this._text_72,
      this._el_73,
      this._text_74,
      this._text_75,
      this._el_76,
      this._text_77,
      this._text_78,
      this._el_79,
      this._text_80,
      this._text_81,
      this._el_82,
      this._text_83,
      this._el_84,
      this._text_85,
      this._text_86,
      this._el_87,
      this._text_88,
      this._text_89,
      this._el_90,
      this._text_91,
      this._el_92,
      this._text_93,
      this._text_94,
      this._el_95,
      this._text_96,
      this._text_97,
      this._text_98,
      this._el_99,
      this._text_100,
      this._text_101,
      this._el_102,
      this._text_103,
      this._el_104,
      this._el_105,
      this._text_106,
      this._el_107,
      this._text_108,
      this._text_109,
      this._el_110,
      this._el_111,
      this._text_112,
      this._el_113,
      this._text_114,
      this._text_115,
      this._text_116,
      this._el_117,
      this._text_118,
      this._el_119,
      this._text_120,
      this._text_121,
      this._el_122,
      this._text_123,
      this._text_124,
      this._el_125,
      this._text_126,
      this._el_127,
      this._el_128,
      this._text_129,
      this._el_130,
      this._text_131,
      this._el_132,
      this._el_133,
      this._text_134,
      this._el_135,
      this._text_136,
      this._el_137,
      this._text_138,
      this._el_139,
      this._text_140,
      this._el_141,
      this._text_142,
      this._text_143,
      this._text_144,
      this._el_145,
      this._el_146,
      this._text_147,
      this._el_148,
      this._text_149,
      this._el_150,
      this._el_151,
      this._text_152,
      this._el_153,
      this._text_154,
      this._el_155,
      this._text_156,
      this._el_157,
      this._text_158,
      this._text_159,
      this._text_160,
      this._el_161,
      this._text_162,
      this._el_163,
      this._text_164,
      this._text_165,
      this._el_166,
      this._text_167,
      this._el_168,
      this._text_169,
      this._el_170,
      this._text_171,
      this._el_172,
      this._text_173,
      this._el_174,
      this._text_175,
      this._text_176,
      this._text_177,
      this._el_178,
      this._text_179,
      this._el_180,
      this._text_181,
      this._el_182,
      this._text_183,
      this._el_184,
      this._text_185,
      this._text_186,
      this._text_187,
      this._el_188,
      this._text_189,
      this._el_190,
      this._text_191,
      this._el_192,
      this._text_193,
      this._el_194,
      this._text_195,
      this._text_196,
      this._text_197,
      this._el_198,
      this._text_199,
      this._el_200,
      this._text_201,
      this._el_202,
      this._text_203,
      this._el_204,
      this._text_205,
      this._text_206,
      this._text_207,
      this._el_208,
      this._text_209,
      this._el_210,
      this._text_211,
      this._el_212,
      this._text_213,
      this._el_214,
      this._text_215,
      this._text_216,
      this._el_217,
      this._text_218,
      this._el_219,
      this._text_220,
      this._text_221,
      this._text_222,
      this._el_223,
      this._text_224,
      this._el_225,
      this._text_226,
      this._el_227,
      this._text_228,
      this._el_229,
      this._text_230,
      this._text_231,
      this._text_232,
      this._text_233,
      this._el_234,
      this._text_235,
      this._el_236,
      this._text_237,
      this._text_238,
      this._el_239,
      this._text_240,
      this._text_241,
      this._el_242,
      this._text_243,
      this._el_244,
      this._text_245,
      this._text_246,
      this._el_247,
      this._text_248,
      this._text_249,
      this._el_250,
      this._text_251,
      this._text_252,
      this._el_253,
      this._text_254,
      this._text_255,
      this._el_256,
      this._text_257,
      this._text_258,
      this._el_259,
      this._text_260,
      this._text_261,
      this._el_262,
      this._text_263,
      this._text_264,
      this._el_265,
      this._text_266,
      this._text_267,
      this._text_268,
      this._el_269,
      this._text_270,
      this._el_271,
      this._text_272,
      this._text_273,
      this._el_274,
      this._text_275,
      this._text_276,
      this._el_277,
      this._text_278,
      this._el_279,
      this._text_280,
      this._text_281,
      this._el_282,
      this._text_283,
      this._text_284,
      this._el_285,
      this._text_286,
      this._el_287,
      this._text_288,
      this._text_289,
      this._el_290,
      this._text_291,
      this._el_292,
      this._text_293,
      this._text_294,
      this._text_295,
      this._text_296
    ]
    ,([] as any[]),([] as any[]));
    return (null as any);
  }
  injectorGetInternal(token:any,requestNodeIndex:number,notFoundResult:any):any {
    if (((token === import23.ToolbarTitle) && ((5 <= requestNodeIndex) && (requestNodeIndex <= 6)))) { return this._ToolbarTitle_5_4.context; }
    if (((token === import24.Navbar) && ((3 <= requestNodeIndex) && (requestNodeIndex <= 7)))) { return this._Navbar_3_4.context; }
    if (((token === import19.Header) && ((1 <= requestNodeIndex) && (requestNodeIndex <= 8)))) { return this._Header_1_3.context; }
    if (((token === import25.Content) && ((10 <= requestNodeIndex) && (requestNodeIndex <= 295)))) { return this._Content_10_4.context; }
    return notFoundResult;
  }
  detectChangesInternal(throwOnChange:boolean):void {
    this._Header_1_3.detectChangesInternal(this,this._el_1,throwOnChange);
    this._Navbar_3_4.detectChangesInternal(this,this._el_3,throwOnChange);
    if (this._ToolbarTitle_5_4.detectChangesInternal(this,this._el_5,throwOnChange)) { this._appEl_5.componentView.markAsCheckOnce(); }
    if (this._Content_10_4.detectChangesInternal(this,this._el_10,throwOnChange)) { this._appEl_10.componentView.markAsCheckOnce(); }
    this.detectContentChildrenChanges(throwOnChange);
    const currVal_0:any = this._Navbar_3_4.context._hidden;
    if (import4.checkBinding(throwOnChange,this._expr_0,currVal_0)) {
      this.renderer.setElementProperty(this._el_3,'hidden',currVal_0);
      this._expr_0 = currVal_0;
    }
    const currVal_1:any = this._Navbar_3_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_1,currVal_1)) {
      this.renderer.setElementClass(this._el_3,'statusbar-padding',currVal_1);
      this._expr_1 = currVal_1;
    }
    const currVal_2:any = this._Content_10_4.context._sbPadding;
    if (import4.checkBinding(throwOnChange,this._expr_2,currVal_2)) {
      this.renderer.setElementClass(this._el_10,'statusbar-padding',currVal_2);
      this._expr_2 = currVal_2;
    }
    this.detectViewChildrenChanges(throwOnChange);
    if (!throwOnChange) { if ((this.numberOfChecks === 0)) { this._Navbar_3_4.context.ngAfterViewInit(); } }
  }
  destroyInternal():void {
    this._Content_10_4.context.ngOnDestroy();
  }
}
export function viewFactory_PrivacyPolicyPage0(viewUtils:import4.ViewUtils,parentInjector:import5.Injector,declarationEl:import3.AppElement):import1.AppView<import0.PrivacyPolicyPage> {
  if ((renderType_PrivacyPolicyPage === (null as any))) { (renderType_PrivacyPolicyPage = viewUtils.createRenderComponentType('',0,import9.ViewEncapsulation.None,styles_PrivacyPolicyPage,{})); }
  return new _View_PrivacyPolicyPage0(viewUtils,parentInjector,declarationEl);
}